// Practical phrase flashcards: the sentences the course teaches, gathered out of
// the chapters and grouped by the moment you would actually say them. Each card
// adds a short usage note so the learner gets context with the answer, not just
// a bare translation.
//
// A card is a whole sentence — single words live in the Common Words deck
// (`words.js`), so the two decks complement each other instead of overlapping.
export default {
  id: 'common-phrases',
  title: 'Common Phrases',
  breadcrumb: 'Phrases',
  defaultJapaneseFirst: false,
  twoStepReveal: false,
  intro:
    'Almost every sentence the chapters teach, grouped by moment — greeting, ordering, ' +
    'paying, asking the way, checking in, getting help. Cards start with English: say ' +
    'the Japanese, then tap once for the answer and a quick usage note.',
  scenarios: [
    {
      id: 'greetings-courtesies',
      title: 'Greetings & Courtesies',
      icon: '👋',
      blurb: 'Polite, dependable phrases for opening and smoothing everyday encounters.',
      words: [
        { jp: 'おはようございます', romaji: 'ohayou gozaimasu', en: 'Good morning', note: 'The polite morning greeting, normally used until around 10 a.m.' },
        { jp: 'こんにちは', romaji: 'konnichiwa', en: 'Hello / good day', note: 'The standard daytime greeting; the final は is pronounced wa.' },
        { jp: 'こんばんは', romaji: 'konbanwa', en: 'Good evening', note: 'Use this when greeting someone in the evening.' },
        { jp: 'おやすみなさい', romaji: 'oyasumi nasai', en: 'Good night', note: 'A parting phrase for the end of the day, not a greeting on arrival.' },
        { jp: 'ありがとうございます', romaji: 'arigatou gozaimasu', en: 'Thank you', note: 'The full polite form and the safest default with strangers or staff.' },
        { jp: 'どうも', romaji: 'doumo', en: 'Thanks / hi', note: 'A compact casual acknowledgement; useful, but less formal than arigatou gozaimasu.' },
        { jp: 'どういたしまして', romaji: 'dou itashimashite', en: 'You’re welcome', note: 'Correct but a little formal; staff more often just answer with another arigatou gozaimasu.' },
        { jp: 'はい', romaji: 'hai', en: 'Yes', note: 'Often also means “I hear you” rather than agreement with the whole statement.' },
        { jp: 'いいえ', romaji: 'iie', en: 'No', note: 'A direct no; Japanese often softens refusals with daijoubu desu or chotto instead.' },
        { jp: 'お願いします', romaji: 'onegai shimasu', en: 'Please', note: 'The workhorse for requesting an action or service; it literally asks a favour.' },
        { jp: 'どうぞ', romaji: 'douzo', en: 'Go ahead / here you are', note: 'Offers something to someone, or invites them to go first.' },
        { jp: '大丈夫です', romaji: 'daijoubu desu', en: 'It’s fine / I’m OK / no thanks', note: 'Context and gesture decide whether this accepts reassurance or politely declines an offer.' },
        { jp: '失礼します', romaji: 'shitsurei shimasu', en: 'Excuse me', note: 'Polite when entering, leaving, or interrupting; literally, “I am being rude.”' },
      ],
    },
    {
      id: 'getting-through',
      title: 'Getting Through an Interaction',
      icon: '💬',
      blurb: 'Point, ask, slow things down, and recover when the conversation outruns you.',
      words: [
        { jp: 'すみません', romaji: 'sumimasen', en: 'Excuse me / sorry / thank you', note: 'Say it briskly to get attention, softly to apologize or thank someone for their trouble, and while passing through a crowd.' },
        { jp: 'これをください', romaji: 'kore o kudasai', en: 'This one, please', note: 'Point as you say it. Kore means the item near you; kudasai asks someone to give it to you.' },
        { jp: 'いくらですか', romaji: 'ikura desu ka', en: 'How much is it?', note: 'A complete polite price question; pointing supplies the item.' },
        { jp: '〜はどこですか', romaji: '… wa doko desu ka', en: 'Where is …?', note: 'Put the place or thing before wa: toire wa doko desu ka? means “Where is the toilet?”' },
        { jp: '英語のメニューはありますか', romaji: 'eigo no menyuu wa arimasu ka', en: 'Do you have an English menu?', note: 'Arimasu ka asks whether an inanimate thing is available.' },
        { jp: 'わかりません', romaji: 'wakarimasen', en: 'I don’t understand', note: 'A polite negative. The missing subject is understood from the situation.' },
        { jp: '日本語がわかりません', romaji: 'nihongo ga wakarimasen', en: 'I don’t understand Japanese', note: 'With wakaru, the thing understood is marked by ga, not the object marker o.' },
        { jp: 'もう一度お願いします', romaji: 'mou ichido onegai shimasu', en: 'One more time, please', note: 'Use this to ask someone to repeat what they just said.' },
        { jp: 'もう一度言ってください', romaji: 'mou ichido itte kudasai', en: 'Please say that again', note: 'Itte is the te-form of iu (to say); slightly more explicit than mou ichido onegai shimasu.' },
        { jp: 'ゆっくりお願いします', romaji: 'yukkuri onegai shimasu', en: 'Slowly, please', note: 'A compact request for slower speech; combine it with mou ichido for a slow repeat.' },
        { jp: 'ゆっくり話してください', romaji: 'yukkuri hanashite kudasai', en: 'Please speak slowly', note: 'The full request: yukkuri (slowly) plus the te-form of hanasu (to speak).' },
        { jp: '英語ができますか', romaji: 'eigo ga dekimasu ka', en: 'Can you speak English?', note: 'Literally asks whether English is possible; polite and readily understood.' },
        { jp: '英語がわかる人はいますか', romaji: 'eigo ga wakaru hito wa imasu ka', en: 'Is there anyone who speaks English?', note: 'Wakaru hito is “a person who understands”; imasu is the verb of existence for people.' },
        { jp: 'ちょっと待ってください', romaji: 'chotto matte kudasai', en: 'Please wait a moment', note: 'Matte is the te-form of matsu, “wait”; kudasai turns it into a polite request.' },
        { jp: '書いてください', romaji: 'kaite kudasai', en: 'Please write it down', note: 'A useful extra when a name, address, or price is hard to catch by ear.' },
      ],
    },
    {
      id: 'introducing-yourself',
      title: 'Introducing Yourself',
      icon: '🤝',
      blurb: 'A four-part introduction you can prepare once and reuse everywhere.',
      words: [
        { jp: 'はじめまして', romaji: 'hajimemashite', en: 'Nice to meet you', note: 'Use only at a first meeting; it opens a self-introduction.' },
        { jp: '〜です', romaji: '[name] desu', en: 'I’m [name]', note: 'Put your name before desu. Japanese normally omits the word for “I” here.' },
        { jp: '〜から来ました', romaji: '[country] kara kimashita', en: 'I came from [country]', note: 'Replace the blank with your country; kara means “from,” and kimashita is polite past “came.”' },
        { jp: 'よろしくお願いします', romaji: 'yoroshiku onegai shimasu', en: 'Pleased to meet you', note: 'There is no exact English equivalent: it asks for goodwill and means something like “let’s get along.”' },
        { jp: 'どこから来ましたか', romaji: 'doko kara kimashita ka', en: 'Where are you from?', note: 'The same sentence you use about yourself, with doko (where) in place of the country and ka on the end.' },
        { jp: '日本は初めてです', romaji: 'nihon wa hajimete desu', en: 'It’s my first time in Japan', note: 'Hajimete means “the first time”; the topic は says what it is the first time of.' },
        { jp: '観光で来ました', romaji: 'kankou de kimashita', en: 'I’m here as a tourist', note: 'De marks the means or purpose: literally, “I came by way of sightseeing.”' },
        { jp: '私もです', romaji: 'watashi mo desu', en: 'Me too', note: 'Mo replaces は or が and means “also”; it never stacks with them.' },
      ],
    },
    {
      id: 'asking-questions',
      title: 'Questions That Get Answers',
      icon: '❓',
      blurb: 'Whole questions, ready to say — point at the thing and let the sentence do the rest.',
      words: [
        { jp: 'これは何ですか', romaji: 'kore wa nan desu ka', en: 'What is this?', note: 'Nani becomes nan before desu. Kore is the thing near you.' },
        { jp: 'あれは何ですか', romaji: 'are wa nan desu ka', en: 'What is that over there?', note: 'Are is the far one — away from both of you. Sore is the one near the listener.' },
        { jp: 'トイレはどこですか', romaji: 'toire wa doko desu ka', en: 'Where is the toilet?', note: 'The single most useful application of the … wa doko desu ka pattern.' },
        { jp: '〜はありますか', romaji: '… wa arimasu ka', en: 'Do you have …? / Is there a …?', note: 'Arimasu is for things and facilities; imasu is for people and animals.' },
        { jp: '〜がありますか', romaji: '… ga arimasu ka', en: 'Is there any …?', note: 'Ga presents the thing as new information; は would contrast it with something already mentioned.' },
        { jp: 'どうですか', romaji: 'dou desu ka', en: 'How is it? / What do you think?', note: 'Also an offer: hold something out and say dou desu ka to mean “care for this?”' },
        { jp: 'どれですか', romaji: 'dore desu ka', en: 'Which one is it?', note: 'Dore chooses among three or more; dochira is the politer choice between two.' },
        { jp: 'どうしてですか', romaji: 'doushite desu ka', en: 'Why is that?', note: 'Doushite and naze both mean why; doushite is the everyday one.' },
        { jp: '誰ですか', romaji: 'dare desu ka', en: 'Who is it?', note: 'Dare is “who”; donata is the formal version staff may use with you.' },
        { jp: 'これは日本語で何ですか', romaji: 'kore wa nihongo de nan desu ka', en: 'What is this in Japanese?', note: 'De marks the means — here, the language something is said in. The best question for collecting new words.' },
        { jp: '本当ですか', romaji: 'hontou desu ka', en: 'Really?', note: 'A genuine question or a mild expression of surprise, depending on your tone.' },
      ],
    },
    {
      id: 'polite-requests',
      title: 'Asking Someone To Do Something',
      icon: '🙏',
      blurb: 'Two patterns cover nearly every request: “please do X” and “may I do X?”',
      words: [
        { jp: '見せてください', romaji: 'misete kudasai', en: 'Please show me', note: 'Te-form plus kudasai is the standard polite request; misete comes from miseru (to show).' },
        { jp: '教えてください', romaji: 'oshiete kudasai', en: 'Please tell me', note: 'Oshieru covers both teaching and telling someone a fact, such as an address or a time.' },
        { jp: '助けてください', romaji: 'tasukete kudasai', en: 'Please help me', note: 'For real trouble. For a small favour, tetsudatte moraemasu ka sounds much lighter.' },
        { jp: '手伝ってもらえますか', romaji: 'tetsudatte moraemasu ka', en: 'Could you help me?', note: 'Te-form plus moraemasu ka asks for a favour and is softer than kudasai.' },
        { jp: '写真を撮ってもらえますか', romaji: 'shashin o totte moraemasu ka', en: 'Could you take a photo for me?', note: 'Hold the phone out as you say it; the request pattern does the rest.' },
        { jp: '写真を撮ってもいいですか', romaji: 'shashin o totte mo ii desu ka', en: 'May I take a photo?', note: 'Te-form plus mo ii desu ka asks permission — worth asking inside shops, temples and restaurants.' },
        { jp: '入ってもいいですか', romaji: 'haitte mo ii desu ka', en: 'May I go in?', note: 'Haitte is the te-form of hairu (to enter), which is irregular in this form.' },
        { jp: 'ここに座ってもいいですか', romaji: 'koko ni suwatte mo ii desu ka', en: 'May I sit here?', note: 'Ni marks the spot where you end up sitting.' },
        { jp: '試着してもいいですか', romaji: 'shichaku shite mo ii desu ka', en: 'May I try it on?', note: 'Shichaku suru is “to try on clothes”; suru verbs make their te-form as shite.' },
        { jp: 'ちょっといいですか', romaji: 'chotto ii desu ka', en: 'Do you have a moment?', note: 'A light way to open an interruption, softer than sumimasen on its own.' },
      ],
    },
    {
      id: 'reacting',
      title: 'Reacting & Apologising',
      icon: '💭',
      blurb: 'The noises and short replies that keep a Japanese conversation alive.',
      words: [
        { jp: 'そうですね', romaji: 'sou desu ne', en: 'That’s right / let me see', note: 'Agreement, or a pause for thought — ne invites the other person to agree with you.' },
        { jp: 'そうですか', romaji: 'sou desu ka', en: 'Oh, really?', note: 'Takes in what you were just told. Flat intonation, not the surprise an English “really?” carries.' },
        { jp: 'そうです', romaji: 'sou desu', en: 'That’s right', note: 'A plain confirmation, typically answering a yes-or-no question about a fact.' },
        { jp: 'なるほど', romaji: 'naruhodo', en: 'I see, that makes sense', note: 'Signals that an explanation has landed; slightly casual, so use it with people, not staff.' },
        { jp: 'いいですね', romaji: 'ii desu ne', en: 'That’s nice', note: 'The everyday way to approve of a plan, a place, or a suggestion.' },
        { jp: '違います', romaji: 'chigaimasu', en: 'That’s not right', note: 'Corrects a fact rather than refusing a request; softer than iie in most situations.' },
        { jp: '知りません', romaji: 'shirimasen', en: 'I don’t know', note: 'Can sound blunt. Wakarimasen is the gentler way to say you cannot help.' },
        { jp: 'ごめんなさい', romaji: 'gomen nasai', en: 'I’m sorry', note: 'A personal, more emotional apology than sumimasen — for something you actually did.' },
        { jp: '申し訳ありません', romaji: 'moushiwake arimasen', en: 'I deeply apologise', note: 'Formal and serious; you will hear staff use it, and rarely need it yourself.' },
        { jp: '大丈夫ですか', romaji: 'daijoubu desu ka', en: 'Are you OK?', note: 'The same daijoubu, turned into a question — for someone who trips, drops something, or looks unwell.' },
      ],
    },
    {
      id: 'around-food',
      title: 'Around the Table',
      icon: '🍜',
      blurb: 'The ritual phrases that bookend a Japanese meal, plus the ones that praise it.',
      words: [
        { jp: 'いただきます', romaji: 'itadakimasu', en: 'I gratefully receive', note: 'Said just before eating to acknowledge the food and everyone involved in providing it.' },
        { jp: 'ごちそうさまでした', romaji: 'gochisousama deshita', en: 'Thank you for the meal', note: 'Say it after eating, including when leaving a restaurant.' },
        { jp: 'おいしいです', romaji: 'oishii desu', en: 'It’s delicious', note: 'A simple compliment that is always warmly received.' },
        { jp: 'おいしかったです', romaji: 'oishikatta desu', en: 'It was delicious', note: 'The past of an i-adjective: drop the い and add かった. Never oishii deshita.' },
        { jp: '乾杯', romaji: 'kanpai', en: 'Cheers!', note: 'The toast, said with glasses raised. Wait for it before drinking.' },
        { jp: 'お腹がいっぱいです', romaji: 'onaka ga ippai desu', en: 'I’m full', note: 'Literally “my stomach is full”; a polite way to decline a second helping.' },
        { jp: 'お腹が空きました', romaji: 'onaka ga sukimashita', en: 'I’m hungry', note: 'Past tense in Japanese — the state of having become hungry.' },
      ],
    },
    {
      id: 'ordering',
      title: 'Ordering a Meal',
      icon: '🍱',
      blurb: 'From the door to the last order, in the sentences a restaurant expects.',
      words: [
        { jp: '二人です', romaji: 'futari desu', en: 'Two people, please', note: 'Say it at the door; people take the counter -nin, and two is the irregular futari.' },
        { jp: '予約していません', romaji: 'yoyaku shite imasen', en: 'We don’t have a reservation', note: 'The negative of yoyaku shite imasu, “I have a reservation.”' },
        { jp: 'メニューをお願いします', romaji: 'menyuu o onegai shimasu', en: 'The menu, please', note: 'O marks the thing you want; onegai shimasu asks for it politely.' },
        { jp: 'おすすめは何ですか', romaji: 'osusume wa nan desu ka', en: 'What do you recommend?', note: 'Osusume means a recommendation or house specialty.' },
        { jp: '注文をお願いします', romaji: 'chuumon o onegai shimasu', en: 'We’d like to order', note: 'Use it to call the staff over once you have decided.' },
        { jp: 'これを二つお願いします', romaji: 'kore o futatsu onegai shimasu', en: 'Two of these, please', note: 'The counter goes after the item, with no particle: kore o futatsu, not futatsu no kore.' },
        { jp: '同じものをください', romaji: 'onaji mono o kudasai', en: 'The same as that, please', note: 'Onaji mono is “the same thing”; point at the other table as you say it.' },
        { jp: '生ビールをお願いします', romaji: 'nama biiru o onegai shimasu', en: 'A draft beer, please', note: 'Nama means “raw”, and with beer it means draft.' },
        { jp: 'お茶をください', romaji: 'ocha o kudasai', en: 'Tea, please', note: 'The o- on ocha is polite decoration that has become part of the word.' },
        { jp: 'お水をください', romaji: 'o-mizu o kudasai', en: 'Water, please', note: 'Tap water is free and normally brought unasked; this is how you ask for more.' },
        { jp: 'お代わりください', romaji: 'okawari kudasai', en: 'Another one, please', note: 'Okawari is a refill of the same thing — rice, tea, a drink.' },
        { jp: '取り皿をください', romaji: 'torizara o kudasai', en: 'A small plate, please', note: 'The plate for taking your share from a dish everyone is sharing.' },
        { jp: '以上です', romaji: 'ijou desu', en: 'That’s all', note: 'Closes your order, so the staff know not to wait for more.' },
        { jp: 'すみません、これは何ですか', romaji: 'sumimasen, kore wa nan desu ka', en: 'Excuse me, what is this?', note: 'Attention-getter plus question — the standard way to ask about an item on the menu.' },
      ],
    },
    {
      id: 'dietary-needs',
      title: 'What You Can’t Eat',
      icon: '🥗',
      blurb: 'Be specific: “vegetarian” alone does not rule out fish stock in Japan.',
      words: [
        { jp: '私はベジタリアンです', romaji: 'watashi wa bejitarian desu', en: 'I am a vegetarian', note: 'Clearly says you are vegetarian, but it does not by itself rule out fish stock; ask about dashi if you need to avoid it.' },
        { jp: '肉が食べられません', romaji: 'niku ga taberaremasen', en: 'I can’t eat meat', note: 'The potential form takes ga, not o: it says the eating is not possible.' },
        { jp: '魚も食べません', romaji: 'sakana mo tabemasen', en: 'I don’t eat fish either', note: 'Mo (“also”) adds fish to what you already said you avoid.' },
        { jp: '肉が入っていないものはありますか', romaji: 'niku ga haitte inai mono wa arimasu ka', en: 'Do you have anything without meat?', note: 'Literally, “Is there a thing that does not contain meat?” It may still not exclude fish stock.' },
        { jp: 'これは何が入っていますか', romaji: 'kore wa nani ga haitte imasu ka', en: 'What’s in this?', note: 'Haitte imasu describes what is contained in something; the ingredient is marked by ga.' },
        { jp: '豚肉が入っていますか', romaji: 'butaniku ga haitte imasu ka', en: 'Does it contain pork?', note: 'Swap butaniku for gyuuniku (beef), toriniku (chicken) or sakana (fish).' },
        { jp: '出汁は魚ですか', romaji: 'dashi wa sakana desu ka', en: 'Is the stock made from fish?', note: 'Dashi is in almost everything savoury, and is usually made from bonito flakes.' },
        { jp: '〜のアレルギーがあります', romaji: '… no arerugii ga arimasu', en: 'I’m allergic to …', note: 'Put the food before no: tamago no arerugii ga arimasu, “I’m allergic to eggs.”' },
        { jp: '野菜だけでお願いします', romaji: 'yasai dake de onegai shimasu', en: 'Vegetables only, please', note: 'Dake means “only”; de marks it as the terms of the request.' },
        { jp: '辛くしないでください', romaji: 'karaku shinaide kudasai', en: 'Please don’t make it spicy', note: 'Nai de kudasai is the negative request: “please don’t …”' },
        { jp: 'わさび抜きでお願いします', romaji: 'wasabi nuki de onegai shimasu', en: 'Without wasabi, please', note: 'Nuki means “left out”; it attaches straight to the ingredient.' },
      ],
    },
    {
      id: 'paying-up',
      title: 'Paying',
      icon: '💴',
      blurb: 'Ask for the bill, split it, choose your method, and get a receipt.',
      words: [
        { jp: 'お会計お願いします', romaji: 'o-kaikei onegai shimasu', en: 'The bill, please', note: 'Use this when you are ready to pay; many restaurants expect payment at the register.' },
        { jp: '全部でいくらですか', romaji: 'zenbu de ikura desu ka', en: 'How much is it altogether?', note: 'Zenbu de means “in total” — de marks the terms the price is given under.' },
        { jp: '高いですね', romaji: 'takai desu ne', en: 'That’s expensive, isn’t it', note: 'Ne invites agreement. It is a comment, not a bargaining move — prices are fixed.' },
        { jp: '別々でお願いします', romaji: 'betsubetsu de onegai shimasu', en: 'Separate bills, please', note: 'Betsubetsu means “separately”; many small restaurants will decline and total everything.' },
        { jp: '一緒でお願いします', romaji: 'issho de onegai shimasu', en: 'All together, please', note: 'The opposite of betsubetsu — one bill for the table.' },
        { jp: 'カードで払えますか', romaji: 'kaado de haraemasu ka', en: 'Can I pay by card?', note: 'The potential form of harau (to pay); de marks the means of payment.' },
        { jp: 'カードは使えますか', romaji: 'kaado wa tsukaemasu ka', en: 'Can I use a card?', note: 'Potential of tsukau (to use). Cash still wins in small shops and shrines.' },
        { jp: '現金だけですか', romaji: 'genkin dake desu ka', en: 'Cash only?', note: 'Worth asking before you order, not after.' },
        { jp: 'カードでお願いします', romaji: 'kaado de onegai shimasu', en: 'By card, please', note: 'The answer to the staff’s o-shiharai wa? (“how will you pay?”).' },
        { jp: '現金でお願いします', romaji: 'genkin de onegai shimasu', en: 'Cash, please', note: 'Notes and coins go in the tray, not into the cashier’s hand.' },
        { jp: '一括でお願いします', romaji: 'ikkatsu de onegai shimasu', en: 'In one payment, please', note: 'The expected answer when a card machine asks about instalments.' },
        { jp: 'レシートをください', romaji: 'reshiito o kudasai', en: 'A receipt, please', note: 'The everyday till receipt.' },
        { jp: '領収書をください', romaji: 'ryoushuusho o kudasai', en: 'An official receipt, please', note: 'The formal, itemised receipt used for expenses — different from a reshiito.' },
        { jp: '免税できますか', romaji: 'menzei dekimasu ka', en: 'Can I buy tax-free?', note: 'Tax-free purchases need your passport and a minimum spend.' },
      ],
    },
    {
      id: 'shopping',
      title: 'In a Shop',
      icon: '🛍️',
      blurb: 'Browse, ask for another size, decide — or leave politely.',
      words: [
        { jp: 'これにします', romaji: 'kore ni shimasu', en: 'I’ll take this one', note: 'Ni shimasu is “I’ll go with …” — the standard way to announce a choice.' },
        { jp: '見てもいいですか', romaji: 'mite mo ii desu ka', en: 'May I look at it?', note: 'Worth asking before handling goods in a small shop.' },
        { jp: '他の色はありますか', romaji: 'hoka no iro wa arimasu ka', en: 'Do you have another colour?', note: 'Hoka no means “other”; swap iro for saizu (size) or dezain (design).' },
        { jp: 'もっと大きいのはありますか', romaji: 'motto ookii no wa arimasu ka', en: 'Do you have a bigger one?', note: 'The no here stands in for the noun: “a big one.”' },
        { jp: 'もっと小さいのはありますか', romaji: 'motto chiisai no wa arimasu ka', en: 'Do you have a smaller one?', note: 'Same pattern with the opposite adjective.' },
        { jp: 'Mサイズはありますか', romaji: 'emu saizu wa arimasu ka', en: 'Do you have a medium?', note: 'Japanese sizes run small — the M you know is often an L here.' },
        { jp: '試着室はどこですか', romaji: 'shichakushitsu wa doko desu ka', en: 'Where is the fitting room?', note: 'Shoes come off before you step in, and a face cover may be handed to you.' },
        { jp: 'ちょっと考えます', romaji: 'chotto kangaemasu', en: 'I’ll think about it', note: 'The polite exit from a shop when you do not want to buy.' },
        { jp: '袋をください', romaji: 'fukuro o kudasai', en: 'A bag, please', note: 'Bags are no longer free; expect a few yen.' },
        { jp: '袋は大丈夫です', romaji: 'fukuro wa daijoubu desu', en: 'I don’t need a bag', note: 'Daijoubu doing its other job: a polite refusal.' },
        { jp: '別々に包んでください', romaji: 'betsubetsu ni tsutsunde kudasai', en: 'Please wrap them separately', note: 'Useful for gifts; wrapping is often free and beautifully done.' },
        { jp: 'パスポートです', romaji: 'pasupooto desu', en: 'Here’s my passport', note: 'Hand it over for a tax-free purchase; a copy is not accepted.' },
        { jp: '免税カウンターはどこですか', romaji: 'menzei kauntaa wa doko desu ka', en: 'Where is the tax-free counter?', note: 'In department stores the refund is handled at one central desk.' },
      ],
    },
    {
      id: 'staff-say',
      title: 'What the Staff Will Say',
      icon: '🏪',
      blurb: 'You do not need to produce these — but recognising them is half of every transaction.',
      words: [
        { jp: 'いらっしゃいませ', romaji: 'irasshaimase', en: 'Welcome!', note: 'Called out as you enter a shop. No reply is expected — a nod is plenty.' },
        { jp: '何名様ですか', romaji: 'nanmei-sama desu ka', en: 'How many people?', note: 'The honorific version of nannin. Answer with futari desu, sannin desu, and so on.' },
        { jp: 'こちらへどうぞ', romaji: 'kochira e douzo', en: 'This way, please', note: 'Kochira is the polite “here”; follow the gesture.' },
        { jp: 'お決まりですか', romaji: 'o-kimari desu ka', en: 'Are you ready to order?', note: 'Answer with hai, or with mou chotto matte kudasai for more time.' },
        { jp: 'かしこまりました', romaji: 'kashikomarimashita', en: 'Certainly', note: 'Your order has been understood — a very polite “got it”.' },
        { jp: '少々お待ちください', romaji: 'shoushou omachi kudasai', en: 'Please wait a moment', note: 'The formal version of chotto matte kudasai, said to customers.' },
        { jp: 'お待たせしました', romaji: 'omatase shimashita', en: 'Sorry to keep you waiting', note: 'Said as the food, the change, or the answer finally arrives.' },
        { jp: '温めますか', romaji: 'atatamemasu ka', en: 'Shall I heat it up?', note: 'The convenience-store question. Answer hai, onegai shimasu or daijoubu desu.' },
        { jp: '袋はご利用ですか', romaji: 'fukuro wa go-riyou desu ka', en: 'Do you need a bag?', note: 'Answer onegai shimasu to take one, or daijoubu desu to decline.' },
        { jp: 'お箸はおつけしますか', romaji: 'o-hashi wa otsuke shimasu ka', en: 'Would you like chopsticks?', note: 'Also asked about spoons, forks and wet wipes.' },
        { jp: 'ポイントカードはお持ちですか', romaji: 'pointo kaado wa o-mochi desu ka', en: 'Do you have a point card?', note: 'You almost certainly do not — nai desu or daijoubu desu ends it.' },
        { jp: '店内でお召し上がりですか', romaji: 'tennai de o-meshiagari desu ka', en: 'Are you eating in?', note: 'Meshiagaru is the honorific “to eat”. Answer mochikaeri de for takeaway.' },
        { jp: '一括でよろしいですか', romaji: 'ikkatsu de yoroshii desu ka', en: 'Single payment, all right?', note: 'The card machine question. Hai is the answer you want.' },
        { jp: 'こちらにサインをお願いします', romaji: 'kochira ni sain o onegai shimasu', en: 'Please sign here', note: 'Sain means a signature, not a sign — a classic false friend.' },
        { jp: '三千二百円になります', romaji: 'sanzen nihyaku en ni narimasu', en: 'That comes to ¥3,200', note: 'Ni narimasu is a soft retail “it becomes”; the amount is also on the display.' },
      ],
    },
    {
      id: 'directions',
      title: 'Asking the Way',
      icon: '🗺️',
      blurb: 'Find out where you are, where it is, and whether you can walk it.',
      words: [
        { jp: '駅はどこですか', romaji: 'eki wa doko desu ka', en: 'Where is the station?', note: 'The pattern that carries the whole scenario: [place] wa doko desu ka.' },
        { jp: 'ここはどこですか', romaji: 'koko wa doko desu ka', en: 'Where am I?', note: 'Literally “where is here?” — show a map and this is all you need.' },
        { jp: '〜へ行きたいです', romaji: '… e ikitai desu', en: 'I want to go to …', note: 'The -tai form says what you want to do; e marks the direction.' },
        { jp: '〜へどうやって行きますか', romaji: '… e dou yatte ikimasu ka', en: 'How do I get to …?', note: 'Dou yatte is “by what means”; expect an answer involving a train line.' },
        { jp: '歩いて行けますか', romaji: 'aruite ikemasu ka', en: 'Can I walk there?', note: 'Aruite ikimasu is “go on foot”; ikemasu is its potential form.' },
        { jp: '近いですか', romaji: 'chikai desu ka', en: 'Is it near?', note: 'A yes-or-no question you can ask about anything on a map.' },
        { jp: '遠いですか', romaji: 'tooi desu ka', en: 'Is it far?', note: 'Note the long vowel: tooi (far) against toi, which is nothing at all.' },
        { jp: 'どのくらいかかりますか', romaji: 'dono kurai kakarimasu ka', en: 'How long does it take?', note: 'Kakarimasu covers both time taken and money cost.' },
        { jp: 'まっすぐですか', romaji: 'massugu desu ka', en: 'Is it straight ahead?', note: 'Massugu is “straight”; a nod plus a pointed hand usually confirms it.' },
        { jp: 'この道でいいですか', romaji: 'kono michi de ii desu ka', en: 'Is this the right road?', note: 'De ii desu ka asks whether something will do — endlessly useful.' },
        { jp: '道に迷いました', romaji: 'michi ni mayoimashita', en: 'I’m lost', note: 'Past tense in Japanese: you have already become lost.' },
        { jp: '地図を書いてください', romaji: 'chizu o kaite kudasai', en: 'Please draw me a map', note: 'Kaku covers both writing and drawing.' },
        { jp: '出口はどこですか', romaji: 'deguchi wa doko desu ka', en: 'Where is the exit?', note: 'De-guchi (exit) and iri-guchi (entrance) share the -guchi ending.' },
        { jp: 'コンビニは近くにありますか', romaji: 'konbini wa chikaku ni arimasu ka', en: 'Is there a convenience store nearby?', note: 'Chikaku ni means “in the vicinity”; the answer is almost always yes.' },
      ],
    },
    {
      id: 'trains-and-taxis',
      title: 'Trains & Taxis',
      icon: '🚆',
      blurb: 'Buy the ticket, find the platform, check the train, and direct the driver.',
      words: [
        { jp: '切符はどこで買えますか', romaji: 'kippu wa doko de kaemasu ka', en: 'Where can I buy a ticket?', note: 'De marks where an action happens; kaemasu is the potential of kau (to buy).' },
        { jp: '東京駅までいくらですか', romaji: 'Tokyo-eki made ikura desu ka', en: 'How much is it to Tokyo Station?', note: 'Made means “as far as”; the -eki suffix makes any name a station.' },
        { jp: '何番線ですか', romaji: 'nanbansen desu ka', en: 'Which platform?', note: 'Bansen counts platform tracks; the answer will be a number plus -bansen.' },
        { jp: 'この電車は渋谷に行きますか', romaji: 'kono densha wa Shibuya ni ikimasu ka', en: 'Does this train go to Shibuya?', note: 'Ask on the platform, not on the train — locals answer readily.' },
        { jp: '乗り換えは必要ですか', romaji: 'norikae wa hitsuyou desu ka', en: 'Do I need to change trains?', note: 'Norikae is a transfer; hitsuyou means necessary.' },
        { jp: '次は何時ですか', romaji: 'tsugi wa nanji desu ka', en: 'What time is the next one?', note: 'Tsugi (next) works for trains, buses and your turn in a queue.' },
        { jp: '終電は何時ですか', romaji: 'shuuden wa nanji desu ka', en: 'What time is the last train?', note: 'Ask early in the evening — the last train is often before midnight.' },
        { jp: 'この席は空いていますか', romaji: 'kono seki wa aite imasu ka', en: 'Is this seat free?', note: 'Aite imasu describes the state of being empty or vacant.' },
        { jp: 'ここまでお願いします', romaji: 'koko made onegai shimasu', en: 'To here, please', note: 'Say it to a taxi driver while showing the address or a map pin.' },
        { jp: '〜までお願いします', romaji: '… made onegai shimasu', en: 'To …, please', note: 'Put the destination before made; hotel names work well.' },
        { jp: '急いでいます', romaji: 'isoide imasu', en: 'I’m in a hurry', note: 'The -te imasu form describes an ongoing state.' },
        { jp: 'ここで止めてください', romaji: 'koko de tomete kudasai', en: 'Please stop here', note: 'De marks where the stopping happens. Taxi doors are opened by the driver.' },
        { jp: 'ここでいいです', romaji: 'koko de ii desu', en: 'Here is fine', note: 'A softer alternative that stops the taxi without an instruction.' },
      ],
    },
    {
      id: 'hotel',
      title: 'At the Hotel',
      icon: '🛏️',
      blurb: 'Check in, ask about the room, and report what isn’t working.',
      words: [
        { jp: 'チェックインお願いします', romaji: 'chekku-in onegai shimasu', en: 'I’d like to check in', note: 'Borrowed nouns plus onegai shimasu cover most front-desk business.' },
        { jp: '予約しています', romaji: 'yoyaku shite imasu', en: 'I have a reservation', note: 'Literally “I have reserved” — the -te imasu form of a completed action that still holds.' },
        { jp: '〜という名前です', romaji: '… to iu namae desu', en: 'The name is …', note: 'To iu introduces a name or title: “a name called …”' },
        { jp: '二泊です', romaji: 'nihaku desu', en: 'Two nights', note: '-haku counts nights of a stay; three nights is sanpaku, with the p sound.' },
        { jp: '禁煙の部屋をお願いします', romaji: 'kin’en no heya o onegai shimasu', en: 'A non-smoking room, please', note: 'Kin’en means smoking prohibited; note the break between n and e.' },
        { jp: '静かな部屋はありますか', romaji: 'shizuka na heya wa arimasu ka', en: 'Do you have a quiet room?', note: 'Shizuka is a na-adjective, so it needs na before the noun.' },
        { jp: '朝食は何時からですか', romaji: 'choushoku wa nanji kara desu ka', en: 'What time is breakfast?', note: 'Kara means “from”, so this asks when breakfast starts.' },
        { jp: 'チェックアウトは何時までですか', romaji: 'chekku-auto wa nanji made desu ka', en: 'When is check-out?', note: 'Made means “until” — the deadline rather than the start.' },
        { jp: '荷物を預かってもらえますか', romaji: 'nimotsu o azukatte moraemasu ka', en: 'Could you hold my luggage?', note: 'Most hotels will keep bags before check-in and after check-out.' },
        { jp: 'Wi-Fiのパスワードは何ですか', romaji: 'waifai no pasuwaado wa nan desu ka', en: 'What’s the Wi-Fi password?', note: 'No links the two nouns: the password of the Wi-Fi.' },
        { jp: '部屋を変えてもらえますか', romaji: 'heya o kaete moraemasu ka', en: 'Could I change rooms?', note: 'Kaete is the te-form of kaeru (to change something).' },
        { jp: 'エアコンが壊れています', romaji: 'eakon ga kowarete imasu', en: 'The air conditioning is broken', note: 'Kowarete imasu is a resulting state: it broke, and it is still broken.' },
        { jp: 'お湯が出ません', romaji: 'oyu ga demasen', en: 'There’s no hot water', note: 'Oyu is hot water specifically; demasen means it does not come out.' },
        { jp: '部屋が寒いです', romaji: 'heya ga samui desu', en: 'The room is cold', note: 'Samui is for air temperature; tsumetai is for things you touch.' },
        { jp: '部屋が暑いです', romaji: 'heya ga atsui desu', en: 'The room is hot', note: 'The opposite complaint, and the more common one in summer.' },
        { jp: 'タオルをもう一枚ください', romaji: 'taoru o mou ichimai kudasai', en: 'One more towel, please', note: '-mai counts flat things: towels, tickets, sheets of paper.' },
        { jp: '隣がうるさいです', romaji: 'tonari ga urusai desu', en: 'The room next door is noisy', note: 'Tonari means the one immediately next to you.' },
        { jp: '鍵をなくしました', romaji: 'kagi o nakushimashita', en: 'I lost my key', note: 'Nakushimashita is the polite past of nakusu, to lose something.' },
      ],
    },
    {
      id: 'emergencies',
      title: 'Trouble & Lost Things',
      icon: '🚨',
      blurb: 'Short, loud, unambiguous — the phrases you hope not to need.',
      words: [
        { jp: '助けて', romaji: 'tasukete', en: 'Help!', note: 'The bare te-form is a shout, not a request. Politeness stops mattering here.' },
        { jp: '危ないです', romaji: 'abunai desu', en: 'It’s dangerous / watch out', note: 'Also shouted as just abunai! to warn someone.' },
        { jp: '警察を呼んでください', romaji: 'keisatsu o yonde kudasai', en: 'Please call the police', note: 'Yonde is the te-form of yobu, to call or summon. Police: 110.' },
        { jp: '救急車を呼んでください', romaji: 'kyuukyuusha o yonde kudasai', en: 'Please call an ambulance', note: 'Same pattern, different noun. Fire and ambulance: 119.' },
        { jp: '交番はどこですか', romaji: 'kouban wa doko desu ka', en: 'Where is the police box?', note: 'A kouban is a small neighbourhood police post, and the first stop for lost property.' },
        { jp: '財布をなくしました', romaji: 'saifu o nakushimashita', en: 'I lost my wallet', note: 'Lost property is genuinely likely to be handed in — always ask.' },
        { jp: 'パスポートをなくしました', romaji: 'pasupooto o nakushimashita', en: 'I lost my passport', note: 'Report it at a kouban, then contact your embassy.' },
        { jp: '電車に忘れました', romaji: 'densha ni wasuremashita', en: 'I left it on the train', note: 'Wasureru is to leave something behind; ni marks where it stayed.' },
        { jp: '盗まれました', romaji: 'nusumaremashita', en: 'It was stolen', note: 'A passive past form — the thief is left unsaid, as usual in Japanese.' },
        { jp: '大使館に電話したいです', romaji: 'taishikan ni denwa shitai desu', en: 'I want to call my embassy', note: 'Denwa suru is “to phone”; ni marks who you are calling.' },
      ],
    },
    {
      id: 'feeling-unwell',
      title: 'Feeling Unwell',
      icon: '🩺',
      blurb: 'Name the part that hurts and ask for the help you need.',
      words: [
        { jp: '具合が悪いです', romaji: 'guai ga warui desu', en: 'I feel unwell', note: 'Guai is your condition; this is the general “I’m not well”.' },
        { jp: '痛いです', romaji: 'itai desu', en: 'It hurts', note: 'Point as you say it and no more grammar is required.' },
        { jp: '頭が痛いです', romaji: 'atama ga itai desu', en: 'I have a headache', note: 'The part that hurts takes ga: literally “the head is painful”.' },
        { jp: 'お腹が痛いです', romaji: 'onaka ga itai desu', en: 'I have a stomach ache', note: 'Same pattern; swap in nodo (throat), ha (tooth) or ashi (leg).' },
        { jp: '熱があります', romaji: 'netsu ga arimasu', en: 'I have a fever', note: 'Arimasu for something you have; the fever is marked by ga.' },
        { jp: '昨日から痛いです', romaji: 'kinou kara itai desu', en: 'It has hurt since yesterday', note: 'Kara again means “from”, this time on the timeline.' },
        { jp: 'アレルギーがあります', romaji: 'arerugii ga arimasu', en: 'I have an allergy', note: 'Add the trigger with no: hachi no arerugii ga arimasu, “I’m allergic to bees.”' },
        { jp: '薬をください', romaji: 'kusuri o kudasai', en: 'Medicine, please', note: 'Pharmacy staff will ask what for, so pointing at the symptom helps.' },
        { jp: '薬局はどこですか', romaji: 'yakkyoku wa doko desu ka', en: 'Where is a pharmacy?', note: 'A drugstore (doraggu sutoa) also sells basic medicine.' },
        { jp: '病院へ行きたいです', romaji: 'byouin e ikitai desu', en: 'I want to go to a hospital', note: 'In Japan a byouin covers everything from a clinic to a large hospital.' },
        { jp: '医者を呼んでください', romaji: 'isha o yonde kudasai', en: 'Please call a doctor', note: 'The same yonde kudasai pattern as the police and the ambulance.' },
      ],
    },
    {
      id: 'times-and-hours',
      title: 'Times & Opening Hours',
      icon: '🕐',
      blurb: 'When it starts, when it closes, and how long it will take.',
      words: [
        { jp: '何時ですか', romaji: 'nanji desu ka', en: 'What time is it?', note: 'Nanji is literally “what hour”.' },
        { jp: '何時からですか', romaji: 'nanji kara desu ka', en: 'From what time does it open?', note: 'Kara (from) makes this the opening-time question.' },
        { jp: '何時までですか', romaji: 'nanji made desu ka', en: 'Until what time is it open?', note: 'Made (until) turns the same question into closing time.' },
        { jp: '何時に出ますか', romaji: 'nanji ni demasu ka', en: 'What time does it leave?', note: 'Clock times take ni. Demasu covers trains, buses and tours departing.' },
        { jp: '何分かかりますか', romaji: 'nanpun kakarimasu ka', en: 'How many minutes does it take?', note: 'Nanpun, with the p sound, is the counter question for minutes.' },
        { jp: '開いていますか', romaji: 'aite imasu ka', en: 'Are you open?', note: 'The -te imasu state again: is it in an open condition?' },
        { jp: '休みはいつですか', romaji: 'yasumi wa itsu desu ka', en: 'When are you closed?', note: 'Yasumi is a rest day; many small restaurants close one fixed weekday.' },
        { jp: '今日は何日ですか', romaji: 'kyou wa nannichi desu ka', en: 'What’s today’s date?', note: 'Nannichi asks the day of the month; the answers are famously irregular.' },
        { jp: '何曜日ですか', romaji: 'nan’youbi desu ka', en: 'What day of the week is it?', note: 'Each day ends in -youbi: getsuyoubi, kayoubi, and so on.' },
        { jp: '三時にお願いします', romaji: 'sanji ni onegai shimasu', en: 'At three o’clock, please', note: 'Book a table or a taxi by putting the time before ni onegai shimasu.' },
        { jp: '後で来ます', romaji: 'ato de kimasu', en: 'I’ll come back later', note: 'Ato de means “afterwards”; the present tense carries the future.' },
      ],
    },
    {
      id: 'trip-talk',
      title: 'Talking About Your Trip',
      icon: '✈️',
      blurb: 'Past and future in the two tenses Japanese actually has.',
      words: [
        { jp: '京都へ行きました', romaji: 'Kyoto e ikimashita', en: 'I went to Kyoto', note: '-mashita is the polite past; e marks the direction travelled.' },
        { jp: '三日前に来ました', romaji: 'mikka mae ni kimashita', en: 'I arrived three days ago', note: 'Mae means “before”; mikka mae is “three days before now”.' },
        { jp: '一週間います', romaji: 'isshuukan imasu', en: 'I’m staying a week', note: 'Imasu is the verb of being somewhere, so it doubles as “stay”.' },
        { jp: '明日大阪へ行きます', romaji: 'ashita Osaka e ikimasu', en: 'Tomorrow I’m going to Osaka', note: 'There is no future tense: -masu covers now and later alike.' },
        { jp: '来週帰ります', romaji: 'raishuu kaerimasu', en: 'I’m going home next week', note: 'Kaeru is specifically to return to where you belong.' },
        { jp: '楽しかったです', romaji: 'tanoshikatta desu', en: 'It was fun', note: 'An i-adjective in the past: tanoshii becomes tanoshikatta, then desu for politeness.' },
        { jp: '富士山を見ました', romaji: 'Fujisan o mimashita', en: 'I saw Mt Fuji', note: 'The thing seen takes o; the mountain is Fujisan, never Fuji-yama.' },
        { jp: '温泉に入りました', romaji: 'onsen ni hairimashita', en: 'I went in a hot spring', note: 'Hairu takes ni for the place you end up inside.' },
        { jp: '写真を撮りました', romaji: 'shashin o torimashita', en: 'I took photos', note: 'Shashin o toru is the fixed pairing for taking a photo.' },
        { jp: '日本が好きです', romaji: 'nihon ga suki desu', en: 'I like Japan', note: 'Suki is an adjective, not a verb, so the thing you like takes ga.' },
        { jp: '日本語を勉強しています', romaji: 'nihongo o benkyou shite imasu', en: 'I’m studying Japanese', note: 'The -te imasu form of an action in progress — over weeks as well as right now.' },
      ],
    },
    {
      id: 'how-and-where',
      title: 'Saying How & Where',
      icon: '🧭',
      blurb: 'With whom, by what means, without what — and where the thing actually is.',
      words: [
        { jp: '友達と行きます', romaji: 'tomodachi to ikimasu', en: 'I’ll go with a friend', note: 'To marks the person you do something with.' },
        { jp: '友達と一緒に食べます', romaji: 'tomodachi to issho ni tabemasu', en: 'I’ll eat together with a friend', note: 'Issho ni adds “together”, making the togetherness explicit.' },
        { jp: '一人で来ました', romaji: 'hitori de kimashita', en: 'I came alone', note: 'Hitori de is “by oneself” — de marks the manner, not a companion.' },
        { jp: '電車で行きます', romaji: 'densha de ikimasu', en: 'I’ll go by train', note: 'De marks the means of transport; aruite (on foot) is the exception.' },
        { jp: 'カードで払います', romaji: 'kaado de haraimasu', en: 'I’ll pay by card', note: 'The same de: the tool or method used.' },
        { jp: '箸で食べます', romaji: 'hashi de tabemasu', en: 'I eat with chopsticks', note: 'Instruments take de, never to — to would mean you eat alongside the chopsticks.' },
        { jp: '砂糖なしでお願いします', romaji: 'satou nashi de onegai shimasu', en: 'Without sugar, please', note: 'Nashi means “without”; de sets it as the terms of the request.' },
        { jp: '氷なしでお願いします', romaji: 'koori nashi de onegai shimasu', en: 'No ice, please', note: 'The same pattern, and the most useful version of it in summer.' },
        { jp: '予約なしで入れますか', romaji: 'yoyaku nashi de hairemasu ka', en: 'Can we come in without a reservation?', note: 'Hairemasu is the potential of hairu, to enter.' },
        { jp: '椅子の下に鞄があります', romaji: 'isu no shita ni kaban ga arimasu', en: 'There’s a bag under the chair', note: 'Position words are nouns: “the chair’s underneath”, then ni for location.' },
        { jp: '駅の前で待ちます', romaji: 'eki no mae de machimasu', en: 'I’ll wait in front of the station', note: 'De, not ni, because waiting is an action happening there.' },
        { jp: '銀行の隣です', romaji: 'ginkou no tonari desu', en: 'It’s next to the bank', note: 'A complete answer to a doko question — no verb needed beyond desu.' },
        { jp: 'ホテルの近くにあります', romaji: 'hoteru no chikaku ni arimasu', en: 'It’s near the hotel', note: 'Chikaku (nearby) behaves like any other position noun.' },
      ],
    },
    {
      id: 'joining-ideas',
      title: 'Joining Ideas',
      icon: '🔗',
      blurb: 'And, or, but, because, if — enough to make two thoughts into one sentence.',
      words: [
        { jp: 'コーヒーとお茶をください', romaji: 'koohii to ocha o kudasai', en: 'Coffee and tea, please', note: 'To joins nouns into a complete list — both of them, nothing else.' },
        { jp: '京都と大阪へ行きます', romaji: 'Kyoto to Osaka e ikimasu', en: 'I’m going to Kyoto and Osaka', note: 'To never joins two sentences; only nouns.' },
        { jp: 'コーヒーかお茶をください', romaji: 'koohii ka ocha o kudasai', en: 'Coffee or tea, please', note: 'The same ka that marks questions also means “or” between nouns.' },
        { jp: '電車かバスで行きます', romaji: 'densha ka basu de ikimasu', en: 'I’ll go by train or bus', note: 'The de attaches once, after the whole choice.' },
        { jp: '朝ご飯を食べます。それから、出かけます', romaji: 'asagohan o tabemasu. Sorekara, dekakemasu', en: 'I eat breakfast. Then I go out.', note: 'Sorekara puts events in sequence at the start of the second sentence.' },
        { jp: '行きたいです。でも、時間がありません', romaji: 'ikitai desu. Demo, jikan ga arimasen', en: 'I want to go, but I don’t have time', note: 'Demo starts the second sentence; it never sits in the middle like English “but”.' },
        { jp: 'おいしいです。でも、高いです', romaji: 'oishii desu. Demo, takai desu', en: 'It’s delicious, but expensive', note: 'Two short sentences are more natural here than one long one.' },
        { jp: '雨ですから、行きません', romaji: 'ame desu kara, ikimasen', en: 'Because it’s raining, I won’t go', note: 'Kara follows the reason, so the cause comes first — the reverse of English order.' },
        { jp: 'わかりませんから、英語でお願いします', romaji: 'wakarimasen kara, eigo de onegai shimasu', en: 'Because I don’t understand, English please', note: 'A polite, effective way to switch a conversation into English.' },
        { jp: '時間があったら、行きます', romaji: 'jikan ga attara, ikimasu', en: 'If I have time, I’ll go', note: '-tara makes a condition; it attaches to the plain past form.' },
        { jp: 'わからなかったら、聞いてください', romaji: 'wakaranakattara, kiite kudasai', en: 'If you don’t understand, please ask', note: 'The negative condition: wakaranakatta plus -ra.' },
        { jp: 'だめだったら、別のホテルを探します', romaji: 'dame dattara, betsu no hoteru o sagashimasu', en: 'If it’s no good, I’ll look for another hotel', note: 'Desu becomes datta in the past, so its condition form is dattara.' },
      ],
    },
    {
      id: 'goodbye',
      title: 'Goodbye',
      icon: '🌙',
      blurb: 'Choose a light everyday parting instead of reaching automatically for sayounara.',
      words: [
        { jp: 'さようなら', romaji: 'sayounara', en: 'Goodbye / farewell', note: 'Heavier than everyday English “goodbye”; it can suggest a long separation.' },
        { jp: 'またね', romaji: 'mata ne', en: 'See you', note: 'A light, casual goodbye for friends and people you expect to meet again.' },
        { jp: '失礼します', romaji: 'shitsurei shimasu', en: 'Excuse me, I’m leaving', note: 'A polite exit from an office, shop, lesson, or formal interaction.' },
        { jp: 'ありがとうございました', romaji: 'arigatou gozaimashita', en: 'Thank you very much', note: 'The past polite form thanks someone for a completed service; ideal as you leave a shop.' },
        { jp: 'お会いできてよかったです', romaji: 'o-ai dekite yokatta desu', en: 'It was nice meeting you', note: 'Natural and warm when parting, though less automatic than the English phrase. At the start of a first meeting, use hajimemashite instead.' },
        { jp: 'また会いましょう', romaji: 'mata aimashou', en: 'Let’s meet again', note: 'A friendly, slightly warmer parting when you genuinely hope to see someone again.' },
        { jp: '気をつけて', romaji: 'ki o tsukete', en: 'Take care', note: 'Literally “be careful”; say it to someone who is heading off or travelling.' },
      ],
    },
  ],
}
