const puzzles = {
  id: 'sentence-builder',
  title: 'Sentence Builder',
  tags: ['question', 'timing', 'reasons'],
  intro:
    'Start with the Foundation sentences, then tackle longer, multi-clause Advanced challenges. Particles are separate tiles, so every wa, ga, o, ni, and de has to land in the right place.',
  puzzles: [
    {
      id: 'morning-coffee',
      difficulty: 'Foundation',
      tags: ['timing'],
      title: 'Morning coffee',
      icon: '☕',
      prompt: 'I drink coffee every morning.',
      pieces: [
        { id: 'watashi', jp: 'わたし', romaji: 'watashi', en: 'I / me' },
        { id: 'wa', jp: 'は', romaji: 'wa', en: 'topic marker' },
        { id: 'maiasa', jp: 'まいあさ', romaji: 'maiasa', en: 'every morning' },
        { id: 'koohii', jp: 'コーヒー', romaji: 'koohii', en: 'coffee' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'nomimasu', jp: 'のみます', romaji: 'nomimasu', en: 'drink' },
      ],
      scrambled: ['koohii', 'nomimasu', 'wa', 'maiasa', 'o', 'watashi'],
      answer: ['watashi', 'wa', 'maiasa', 'koohii', 'o', 'nomimasu'],
      alsoAcceptable: [
        {
          answer: ['maiasa', 'watashi', 'wa', 'koohii', 'o', 'nomimasu'],
          explanation:
            'The time phrase may naturally lead the sentence, but the preferred answer first establishes watashi as the topic and then adds the time context.',
        },
      ],
      pattern: 'Topic + time + object + verb',
      explanation:
        'Wa comes immediately after watashi to mark “I” as the topic. Maiasa needs no particle. O follows koohii to mark coffee as the direct object, and nomimasu, the action, comes last.',
    },
    {
      id: 'station',
      difficulty: 'Foundation',
      tags: ['question'],
      title: 'Find the station',
      icon: '🚉',
      prompt: 'Where is the train station?',
      pieces: [
        { id: 'eki', jp: 'えき', romaji: 'eki', en: 'station' },
        { id: 'wa', jp: 'は', romaji: 'wa', en: 'topic marker' },
        { id: 'doko', jp: 'どこ', romaji: 'doko', en: 'where' },
        { id: 'desu', jp: 'です', romaji: 'desu', en: 'is / polite copula' },
        { id: 'ka', jp: 'か', romaji: 'ka', en: 'question marker' },
      ],
      scrambled: ['ka', 'eki', 'desu', 'wa', 'doko'],
      answer: ['eki', 'wa', 'doko', 'desu', 'ka'],
      pattern: 'Topic + question word + desu + ka',
      explanation:
        'Wa follows eki and introduces the station as the topic. Doko occupies the place where the missing answer would go. Desu links the topic to that answer politely, and the final ka turns the whole sentence into a question.',
    },
    {
      id: 'ramen',
      difficulty: 'Foundation',
      tags: [],
      title: 'Ramen stop',
      icon: '🍜',
      prompt: 'I will eat ramen at the restaurant.',
      pieces: [
        { id: 'resutoran', jp: 'レストラン', romaji: 'resutoran', en: 'restaurant' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'at / place-of-action marker' },
        { id: 'raamen', jp: 'ラーメン', romaji: 'raamen', en: 'ramen' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'tabemasu', jp: 'たべます', romaji: 'tabemasu', en: 'eat / will eat' },
      ],
      scrambled: ['tabemasu', 'o', 'resutoran', 'raamen', 'de'],
      answer: ['resutoran', 'de', 'raamen', 'o', 'tabemasu'],
      alsoAcceptable: [
        {
          answer: ['raamen', 'o', 'resutoran', 'de', 'tabemasu'],
          explanation:
            'The particles keep both roles clear, so the food can come first. It foregrounds ramen, while the preferred answer uses the place as neutral opening context.',
        },
      ],
      pattern: 'Place + de + object + o + verb',
      explanation:
        'De follows resutoran and marks it as the place where eating happens. O follows raamen and marks ramen as what is eaten. Tabemasu comes last; this polite non-past form can mean either “eat” or “will eat,” with context supplying the future meaning here.',
    },
    {
      id: 'kyoto',
      difficulty: 'Foundation',
      tags: ['timing'],
      title: 'Kyoto tomorrow',
      icon: '🚄',
      prompt: 'Tomorrow I will go to Kyoto by train.',
      pieces: [
        { id: 'ashita', jp: 'あした', romaji: 'ashita', en: 'tomorrow' },
        { id: 'densha', jp: 'でんしゃ', romaji: 'densha', en: 'train' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'by / means marker' },
        { id: 'kyouto', jp: 'きょうと', romaji: 'Kyouto', en: 'Kyoto' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'to / destination marker' },
        { id: 'ikimasu', jp: 'いきます', romaji: 'ikimasu', en: 'go / will go' },
      ],
      scrambled: ['ni', 'ikimasu', 'densha', 'ashita', 'kyouto', 'de'],
      answer: ['ashita', 'densha', 'de', 'kyouto', 'ni', 'ikimasu'],
      alsoAcceptable: [
        {
          answer: ['ashita', 'kyouto', 'ni', 'densha', 'de', 'ikimasu'],
          explanation:
            'The destination and means phrases can trade places because their particles preserve their roles. The preferred answer gives the travel method before the destination as a neutral progression.',
        },
      ],
      pattern: 'Time + means/de + destination/ni + movement verb',
      explanation:
        'Ashita sets the time without a particle. De must follow densha to mark the means of travel, while ni must follow Kyouto to mark the destination. Ikimasu finishes the thought.',
    },
    {
      id: 'tickets',
      difficulty: 'Foundation',
      tags: [],
      title: 'Two tickets',
      icon: '🎫',
      prompt: 'Please give me two tickets.',
      pieces: [
        { id: 'kippu', jp: 'きっぷ', romaji: 'kippu', en: 'ticket' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'nimai', jp: 'にまい', romaji: 'nimai', en: 'two flat items' },
        { id: 'kudasai', jp: 'ください', romaji: 'kudasai', en: 'please give me' },
      ],
      scrambled: ['kudasai', 'o', 'nimai', 'kippu'],
      answer: ['kippu', 'o', 'nimai', 'kudasai'],
      alsoAcceptable: [
        {
          answer: ['kippu', 'nimai', 'o', 'kudasai'],
          explanation:
            'This treats “two tickets” as one noun phrase before o. It is grammatical, but the preferred answer uses the more common floating-counter pattern.',
        },
      ],
      pattern: 'Object + o + quantity/counter + kudasai',
      explanation:
        'O follows kippu and marks tickets as the thing requested. Nimai means “two” using mai, the counter for flat objects such as tickets, and normally follows the counted item. Kudasai comes last to make the polite request “please give me …”.',
    },
    {
      id: 'did-not-understand',
      difficulty: 'Foundation',
      tags: [],
      title: 'Lost in translation',
      icon: '💬',
      prompt: 'I did not understand Japanese.',
      pieces: [
        { id: 'nihongo', jp: 'にほんご', romaji: 'nihongo', en: 'Japanese language' },
        { id: 'ga', jp: 'が', romaji: 'ga', en: 'subject / focus marker' },
        { id: 'wakarimasen', jp: 'わかりません', romaji: 'wakarimasen', en: 'do not understand' },
        { id: 'deshita', jp: 'でした', romaji: 'deshita', en: 'past polite ending' },
      ],
      scrambled: ['deshita', 'ga', 'wakarimasen', 'nihongo'],
      answer: ['nihongo', 'ga', 'wakarimasen', 'deshita'],
      pattern: 'Thing understood + ga + negative verb + past ending',
      explanation:
        'With wakaru, Japanese marks the thing understood with ga, not o, so ga must follow nihongo. Wakarimasen gives the polite negative, “do not understand,” and deshita makes it past: “did not understand.” The speaker is clear from context and can be omitted.',
    },
    {
      id: 'photo',
      difficulty: 'Foundation',
      tags: ['question'],
      title: 'A photo here',
      icon: '📷',
      prompt: 'May I take a picture here?',
      pieces: [
        { id: 'koko', jp: 'ここ', romaji: 'koko', en: 'here' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'place-of-action marker' },
        { id: 'shashin', jp: 'しゃしん', romaji: 'shashin', en: 'picture / photograph' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'totte', jp: 'とって', romaji: 'totte', en: 'take (te-form)' },
        { id: 'mo', jp: 'も', romaji: 'mo', en: 'even if / also' },
        { id: 'ii', jp: 'いい', romaji: 'ii', en: 'good / okay' },
        { id: 'desu', jp: 'です', romaji: 'desu', en: 'is / polite copula' },
        { id: 'ka', jp: 'か', romaji: 'ka', en: 'question marker' },
      ],
      scrambled: ['ka', 'shashin', 'mo', 'koko', 'ii', 'o', 'desu', 'de', 'totte'],
      answer: ['koko', 'de', 'shashin', 'o', 'totte', 'mo', 'ii', 'desu', 'ka'],
      alsoAcceptable: [
        {
          answer: ['shashin', 'o', 'koko', 'de', 'totte', 'mo', 'ii', 'desu', 'ka'],
          explanation:
            'The particles still identify the object and location when these phrases swap. This order emphasizes the photo, while the preferred answer sets the location first.',
        },
      ],
      pattern: 'Place/de + object/o + te-form + mo ii desu ka',
      explanation:
        'De follows koko to mark where the action happens, and o follows shashin to mark what is taken. Totte is the te-form of toru. The sequence mo ii desu ka literally asks “is it okay even if …?” Together, te-form + mo ii desu ka is the standard way to ask permission.',
    },
    {
      id: 'hotel',
      difficulty: 'Foundation',
      tags: [],
      title: 'Hotel location',
      icon: '🏨',
      prompt: 'The hotel is near the station.',
      pieces: [
        { id: 'hoteru', jp: 'ホテル', romaji: 'hoteru', en: 'hotel' },
        { id: 'wa', jp: 'は', romaji: 'wa', en: 'topic marker' },
        { id: 'eki', jp: 'えき', romaji: 'eki', en: 'station' },
        { id: 'no', jp: 'の', romaji: 'no', en: 'of / linking particle' },
        { id: 'chikaku', jp: 'ちかく', romaji: 'chikaku', en: 'nearby / vicinity' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'location marker' },
        { id: 'arimasu', jp: 'あります', romaji: 'arimasu', en: 'exists / is (inanimate)' },
      ],
      scrambled: ['ni', 'arimasu', 'no', 'hoteru', 'chikaku', 'wa', 'eki'],
      answer: ['hoteru', 'wa', 'eki', 'no', 'chikaku', 'ni', 'arimasu'],
      alsoAcceptable: [
        {
          answer: ['eki', 'no', 'chikaku', 'ni', 'hoteru', 'wa', 'arimasu'],
          explanation:
            'Putting the location first is grammatical, but wa then gives the hotel a contrastive nuance. The preferred answer is the neutral topic-first version.',
        },
      ],
      pattern: 'Topic/wa + reference/no + location/ni + arimasu',
      explanation:
        'Wa follows hoteru to mark the hotel as the topic. No links eki to chikaku, forming “the station’s vicinity,” and ni marks that vicinity as the hotel’s location. Arimasu is used for the existence or location of an inanimate thing; a person or animal would use imasu.',
    },
    {
      id: 'rainy-taxi',
      difficulty: 'Foundation',
      tags: ['reasons'],
      title: 'Rainy taxi',
      icon: '☔',
      prompt: 'Because it is raining, I will go by taxi.',
      pieces: [
        { id: 'ame', jp: 'あめ', romaji: 'ame', en: 'rain' },
        { id: 'ga', jp: 'が', romaji: 'ga', en: 'subject marker' },
        { id: 'futte', jp: 'ふって', romaji: 'futte', en: 'falling (te-form)' },
        { id: 'imasu', jp: 'います', romaji: 'imasu', en: 'is happening / ongoing' },
        { id: 'kara', jp: 'から', romaji: 'kara', en: 'because' },
        { id: 'takushii', jp: 'タクシー', romaji: 'takushii', en: 'taxi' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'by / means marker' },
        { id: 'ikimasu', jp: 'いきます', romaji: 'ikimasu', en: 'go / will go' },
      ],
      scrambled: ['takushii', 'kara', 'ga', 'ikimasu', 'futte', 'de', 'ame', 'imasu'],
      answer: ['ame', 'ga', 'futte', 'imasu', 'kara', 'takushii', 'de', 'ikimasu'],
      pattern: 'Reason + kara + means/de + action',
      explanation:
        'Ga follows ame because rain is the subject of futte imasu, “is falling.” Kara comes after that complete reason and means “because.” In the result, de follows takushii to mark the means of travel, and ikimasu supplies the final action.',
    },
    {
      id: 'souvenir',
      difficulty: 'Foundation',
      tags: [],
      title: 'Family souvenir',
      icon: '🎁',
      prompt: 'I want to buy a small souvenir for my family.',
      pieces: [
        { id: 'kazoku', jp: 'かぞく', romaji: 'kazoku', en: 'family' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'for / recipient marker' },
        { id: 'chiisai', jp: 'ちいさい', romaji: 'chiisai', en: 'small' },
        { id: 'omiyage', jp: 'おみやげ', romaji: 'omiyage', en: 'souvenir' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'kaitai', jp: 'かいたい', romaji: 'kaitai', en: 'want to buy' },
        { id: 'desu', jp: 'です', romaji: 'desu', en: 'polite ending' },
      ],
      scrambled: ['desu', 'omiyage', 'ni', 'kaitai', 'kazoku', 'o', 'chiisai'],
      answer: ['kazoku', 'ni', 'chiisai', 'omiyage', 'o', 'kaitai', 'desu'],
      alsoAcceptable: [
        {
          answer: ['chiisai', 'omiyage', 'o', 'kazoku', 'ni', 'kaitai', 'desu'],
          explanation:
            'The particles preserve the object and recipient roles when those phrases swap. This foregrounds the souvenir, while the preferred answer introduces its recipient first.',
        },
      ],
      pattern: 'Recipient/ni + adjective + object/o + desire + desu',
      explanation:
        'Ni follows kazoku to mark the family as the intended recipient. The i-adjective chiisai goes directly before omiyage, the noun it describes, and o follows that noun to mark it as the object. Kaitai means “want to buy,” and desu makes the statement polite.',
    },
    {
      id: 'time-if',
      difficulty: 'Advanced',
      tags: ['timing', 'reasons'],
      title: 'If there is time',
      icon: '🕰️',
      prompt: 'If I have time tomorrow, I will go to the museum.',
      pieces: [
        { id: 'ashita', jp: 'あした', romaji: 'ashita', en: 'tomorrow' },
        { id: 'jikan', jp: 'じかん', romaji: 'jikan', en: 'time' },
        { id: 'ga', jp: 'が', romaji: 'ga', en: 'subject marker' },
        { id: 'attara', jp: 'あったら', romaji: 'attara', en: 'if there is / if I have' },
        { id: 'hakubutsukan', jp: 'はくぶつかん', romaji: 'hakubutsukan', en: 'museum' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'to / destination marker' },
        { id: 'ikimasu', jp: 'いきます', romaji: 'ikimasu', en: 'will go' },
      ],
      scrambled: ['ni', 'jikan', 'ikimasu', 'ashita', 'attara', 'hakubutsukan', 'ga'],
      answer: ['ashita', 'jikan', 'ga', 'attara', 'hakubutsukan', 'ni', 'ikimasu'],
      alsoAcceptable: [
        {
          answer: ['jikan', 'ga', 'attara', 'ashita', 'hakubutsukan', 'ni', 'ikimasu'],
          explanation:
            'This is valid when tomorrow is understood as part of the result. The preferred answer places ashita first so it clearly frames the whole condition-and-result sentence.',
        },
      ],
      pattern: 'Time + condition/-tara + destination/ni + result',
      explanation:
        'Ashita sets the time for the whole sentence. Ga marks jikan as what exists, and attara turns arimasu into the condition “if there is time.” The result follows without a separate word for “then”: hakubutsukan takes ni as the destination, and ikimasu stays last.',
    },
    {
      id: 'slowly-again',
      difficulty: 'Advanced',
      tags: ['reasons'],
      title: 'One more time',
      icon: '🔁',
      prompt: 'If I do not understand, please speak slowly one more time.',
      pieces: [
        { id: 'wakaranakattara', jp: 'わからなかったら', romaji: 'wakaranakattara', en: 'if I do not understand' },
        { id: 'mou', jp: 'もう', romaji: 'mou', en: 'one more / again' },
        { id: 'ichido', jp: 'いちど', romaji: 'ichido', en: 'time / once' },
        { id: 'yukkuri', jp: 'ゆっくり', romaji: 'yukkuri', en: 'slowly' },
        { id: 'hanashite', jp: 'はなして', romaji: 'hanashite', en: 'speak (te-form)' },
        { id: 'kudasai', jp: 'ください', romaji: 'kudasai', en: 'please' },
      ],
      scrambled: ['ichido', 'kudasai', 'wakaranakattara', 'hanashite', 'mou', 'yukkuri'],
      answer: ['wakaranakattara', 'mou', 'ichido', 'yukkuri', 'hanashite', 'kudasai'],
      alsoAcceptable: [
        {
          answer: ['wakaranakattara', 'yukkuri', 'mou', 'ichido', 'hanashite', 'kudasai'],
          explanation:
            'The manner phrase and “one more time” can trade places. This is natural, but the preferred answer keeps the fixed phrase mou ichido together before adding how to speak.',
        },
      ],
      pattern: 'Condition/-tara + frequency + manner + te-form + kudasai',
      explanation:
        'Wakaranakattara is the complete “if I do not understand” condition. Mou ichido forms the fixed phrase “one more time,” while yukkuri describes how to speak. Hanashite is the te-form of hanasu, and kudasai turns it into a polite request.',
    },
    {
      id: 'english-please',
      difficulty: 'Advanced',
      tags: ['reasons'],
      title: 'Switch languages',
      icon: '🗣️',
      prompt: 'Because I do not understand Japanese, English please.',
      pieces: [
        { id: 'nihongo', jp: 'にほんご', romaji: 'nihongo', en: 'Japanese language' },
        { id: 'ga', jp: 'が', romaji: 'ga', en: 'subject / focus marker' },
        { id: 'wakarimasen', jp: 'わかりません', romaji: 'wakarimasen', en: 'do not understand' },
        { id: 'kara', jp: 'から', romaji: 'kara', en: 'because' },
        { id: 'eigo', jp: 'えいご', romaji: 'eigo', en: 'English language' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'in / by means of' },
        { id: 'onegai', jp: 'おねがい', romaji: 'onegai', en: 'request / favour' },
        { id: 'shimasu', jp: 'します', romaji: 'shimasu', en: 'do (polite)' },
      ],
      scrambled: ['de', 'kara', 'shimasu', 'nihongo', 'eigo', 'wakarimasen', 'onegai', 'ga'],
      answer: ['nihongo', 'ga', 'wakarimasen', 'kara', 'eigo', 'de', 'onegai', 'shimasu'],
      pattern: 'Reason + kara + language/de + onegai shimasu',
      explanation:
        'Ga marks nihongo as the thing not understood. Kara follows the complete reason, nihongo ga wakarimasen. In the request, de follows eigo to mean “in English,” and onegai shimasu closes the sentence politely.',
    },
    {
      id: 'complex-directions',
      difficulty: 'Advanced',
      tags: [],
      title: 'Two-step directions',
      icon: '🧭',
      prompt: 'Go straight, then turn right at the next corner.',
      pieces: [
        { id: 'massugu', jp: 'まっすぐ', romaji: 'massugu', en: 'straight ahead' },
        { id: 'itte', jp: 'いって', romaji: 'itte', en: 'go (te-form)' },
        { id: 'tsugi', jp: 'つぎ', romaji: 'tsugi', en: 'next' },
        { id: 'no', jp: 'の', romaji: 'no', en: 'linking particle' },
        { id: 'kado', jp: 'かど', romaji: 'kado', en: 'corner' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'route / direct-object marker' },
        { id: 'migi', jp: 'みぎ', romaji: 'migi', en: 'right' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'toward / into' },
        { id: 'magatte', jp: 'まがって', romaji: 'magatte', en: 'turn (te-form)' },
        { id: 'kudasai', jp: 'ください', romaji: 'kudasai', en: 'please' },
      ],
      scrambled: ['ni', 'no', 'kudasai', 'massugu', 'kado', 'magatte', 'o', 'tsugi', 'itte', 'migi'],
      answer: ['massugu', 'itte', 'tsugi', 'no', 'kado', 'o', 'migi', 'ni', 'magatte', 'kudasai'],
      pattern: 'Action in te-form + route/o + direction/ni + request',
      explanation:
        'Massugu modifies itte, whose te-form links the first action to the next. No joins tsugi to kado as “the next corner,” and o marks the corner as the point along the route. Migi ni gives the direction of the turn. Only the final action takes kudasai, so one polite ending covers both instructions.',
    },
    {
      id: 'travel-together',
      difficulty: 'Advanced',
      tags: ['timing'],
      title: 'Travelling together',
      icon: '🚆',
      prompt: 'Tomorrow I will go to Kyoto by train with a friend.',
      pieces: [
        { id: 'ashita', jp: 'あした', romaji: 'ashita', en: 'tomorrow' },
        { id: 'tomodachi', jp: 'ともだち', romaji: 'tomodachi', en: 'friend' },
        { id: 'to', jp: 'と', romaji: 'to', en: 'with / companion marker' },
        { id: 'issho', jp: 'いっしょ', romaji: 'issho', en: 'together' },
        { id: 'ni-together', jp: 'に', romaji: 'ni', en: 'adverb-forming particle' },
        { id: 'densha', jp: 'でんしゃ', romaji: 'densha', en: 'train' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'by / means marker' },
        { id: 'kyouto', jp: 'きょうと', romaji: 'Kyouto', en: 'Kyoto' },
        { id: 'e', jp: 'へ', romaji: 'e', en: 'toward / destination marker' },
        { id: 'ikimasu', jp: 'いきます', romaji: 'ikimasu', en: 'will go' },
      ],
      scrambled: ['de', 'e', 'tomodachi', 'ashita', 'ikimasu', 'ni-together', 'kyouto', 'to', 'densha', 'issho'],
      answer: ['ashita', 'tomodachi', 'to', 'issho', 'ni-together', 'densha', 'de', 'kyouto', 'e', 'ikimasu'],
      alsoAcceptable: [
        {
          answer: ['ashita', 'tomodachi', 'to', 'issho', 'ni-together', 'kyouto', 'e', 'densha', 'de', 'ikimasu'],
          explanation:
            'The destination can precede the means because e and de keep their roles clear. The preferred answer presents companion, means, then destination in a smoother neutral sequence.',
        },
        {
          answer: ['ashita', 'densha', 'de', 'tomodachi', 'to', 'issho', 'ni-together', 'kyouto', 'e', 'ikimasu'],
          explanation:
            'The train phrase can come before the companion phrase without changing the roles. It foregrounds the travel method, while the preferred answer keeps the companion closer to the opening context.',
        },
      ],
      pattern: 'Time + companion/to issho ni + means/de + destination/e + verb',
      explanation:
        'To marks tomodachi as the companion and issho ni completes “together.” De marks densha as the means of travel, while e marks Kyouto as the destination. Each particle must stay beside its phrase, and ikimasu remains last.',
    },
    {
      id: 'between-buildings',
      difficulty: 'Advanced',
      tags: [],
      title: 'Between two buildings',
      icon: '🏙️',
      prompt: 'There is a convenience store between the bank and the hotel.',
      pieces: [
        { id: 'ginkou', jp: 'ぎんこう', romaji: 'ginkou', en: 'bank' },
        { id: 'to', jp: 'と', romaji: 'to', en: 'and' },
        { id: 'hoteru', jp: 'ホテル', romaji: 'hoteru', en: 'hotel' },
        { id: 'no', jp: 'の', romaji: 'no', en: 'linking particle' },
        { id: 'aida', jp: 'あいだ', romaji: 'aida', en: 'between / interval' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'location marker' },
        { id: 'konbini', jp: 'コンビニ', romaji: 'konbini', en: 'convenience store' },
        { id: 'ga', jp: 'が', romaji: 'ga', en: 'subject marker' },
        { id: 'arimasu', jp: 'あります', romaji: 'arimasu', en: 'exists / there is' },
      ],
      scrambled: ['arimasu', 'no', 'ginkou', 'ga', 'aida', 'hoteru', 'ni', 'to', 'konbini'],
      answer: ['ginkou', 'to', 'hoteru', 'no', 'aida', 'ni', 'konbini', 'ga', 'arimasu'],
      alsoAcceptable: [
        {
          answer: ['hoteru', 'to', 'ginkou', 'no', 'aida', 'ni', 'konbini', 'ga', 'arimasu'],
          explanation:
            'The two endpoints of “between” can trade places without changing the location. The preferred answer follows the bank-then-hotel order used in the English prompt.',
        },
      ],
      pattern: 'A to B no aida ni + thing/ga + arimasu',
      explanation:
        'To joins the two reference points, ginkou and hoteru. No connects that pair to aida, creating “the space between the bank and the hotel,” and ni marks it as the location. Ga marks konbini as the thing that exists, and arimasu is used because it is inanimate.',
    },
    {
      id: 'checkout-luggage',
      difficulty: 'Advanced',
      tags: ['question', 'timing'],
      title: 'After check-out',
      icon: '🧳',
      prompt: 'Could you hold my luggage after check-out?',
      pieces: [
        { id: 'chekkuauto', jp: 'チェックアウト', romaji: 'chekkuauto', en: 'check-out' },
        { id: 'no', jp: 'の', romaji: 'no', en: 'linking particle' },
        { id: 'ato', jp: 'あと', romaji: 'ato', en: 'after' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'at / in the period after' },
        { id: 'nimotsu', jp: 'にもつ', romaji: 'nimotsu', en: 'luggage' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'azukatte', jp: 'あずかって', romaji: 'azukatte', en: 'hold / look after (te-form)' },
        { id: 'moraemasu', jp: 'もらえます', romaji: 'moraemasu', en: 'can I receive the favour' },
        { id: 'ka', jp: 'か', romaji: 'ka', en: 'question marker' },
      ],
      scrambled: ['moraemasu', 'nimotsu', 'de', 'ka', 'ato', 'azukatte', 'no', 'o', 'chekkuauto'],
      answer: ['chekkuauto', 'no', 'ato', 'de', 'nimotsu', 'o', 'azukatte', 'moraemasu', 'ka'],
      alsoAcceptable: [
        {
          answer: ['nimotsu', 'o', 'chekkuauto', 'no', 'ato', 'de', 'azukatte', 'moraemasu', 'ka'],
          explanation:
            'The object can come before the time phrase because o preserves its role. This foregrounds the luggage, while the preferred answer opens with the time-setting phrase.',
        },
      ],
      pattern: 'Event/no ato de + object/o + te-form + moraemasu ka',
      explanation:
        'No links chekkuauto to ato, and de completes the time expression “after check-out.” O marks nimotsu as what the hotel will hold. The te-form azukatte connects to moraemasu ka, literally asking whether you can receive that favour; this is softer than a direct te-form + kudasai request.',
    },
    {
      id: 'bullet-train-tickets',
      difficulty: 'Advanced',
      tags: ['timing'],
      title: 'Timed ticket request',
      icon: '🎟️',
      prompt: 'Two tickets for tomorrow’s 3 p.m. bullet train, please.',
      pieces: [
        { id: 'ashita', jp: 'あした', romaji: 'ashita', en: 'tomorrow' },
        { id: 'gogo', jp: 'ごご', romaji: 'gogo', en: 'p.m. / afternoon' },
        { id: 'sanji', jp: 'さんじ', romaji: 'sanji', en: 'three o’clock' },
        { id: 'no-time', jp: 'の', romaji: 'no', en: 'linking particle' },
        { id: 'shinkansen', jp: 'しんかんせん', romaji: 'shinkansen', en: 'bullet train' },
        { id: 'no-train', jp: 'の', romaji: 'no', en: 'linking particle' },
        { id: 'kippu', jp: 'きっぷ', romaji: 'kippu', en: 'ticket' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'nimai', jp: 'にまい', romaji: 'nimai', en: 'two flat items' },
        { id: 'kudasai', jp: 'ください', romaji: 'kudasai', en: 'please give me' },
      ],
      scrambled: ['no-train', 'nimai', 'gogo', 'kippu', 'ashita', 'kudasai', 'shinkansen', 'o', 'no-time', 'sanji'],
      answer: ['ashita', 'gogo', 'sanji', 'no-time', 'shinkansen', 'no-train', 'kippu', 'o', 'nimai', 'kudasai'],
      pattern: 'Date + time/no + train/no + item/o + counter + kudasai',
      explanation:
        'Ashita and gogo sanji combine as “tomorrow at 3 p.m.” The first no attaches that time to shinkansen, and the second attaches the train to kippu, building one long noun phrase from left to right. O marks the tickets as requested, nimai counts two flat items, and kudasai comes last.',
    },
    {
      id: 'broken-air-conditioner',
      difficulty: 'Advanced',
      tags: ['question', 'reasons'],
      title: 'Room problem',
      icon: '🛎️',
      prompt: 'Because the air conditioner is broken, could you change my room?',
      pieces: [
        { id: 'eakon', jp: 'エアコン', romaji: 'eakon', en: 'air conditioner' },
        { id: 'ga', jp: 'が', romaji: 'ga', en: 'subject marker' },
        { id: 'kowarete', jp: 'こわれて', romaji: 'kowarete', en: 'broken (te-form)' },
        { id: 'imasu', jp: 'います', romaji: 'imasu', en: 'is in that state' },
        { id: 'node', jp: 'ので', romaji: 'node', en: 'because / since' },
        { id: 'heya', jp: 'へや', romaji: 'heya', en: 'room' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'kaete', jp: 'かえて', romaji: 'kaete', en: 'change (te-form)' },
        { id: 'moraemasu', jp: 'もらえます', romaji: 'moraemasu', en: 'can I receive the favour' },
        { id: 'ka', jp: 'か', romaji: 'ka', en: 'question marker' },
      ],
      scrambled: ['heya', 'node', 'moraemasu', 'ga', 'kaete', 'imasu', 'ka', 'eakon', 'o', 'kowarete'],
      answer: ['eakon', 'ga', 'kowarete', 'imasu', 'node', 'heya', 'o', 'kaete', 'moraemasu', 'ka'],
      pattern: 'State/reason + node + object/o + te-form + moraemasu ka',
      explanation:
        'Ga marks eakon as the thing in the broken state, expressed by kowarete imasu. Node follows that full clause and gives a softer “because” than kara. In the request, o marks heya as what should be changed, and kaete moraemasu ka politely asks the listener to do that favour.',
    },
    {
      id: 'rain-plan',
      difficulty: 'Advanced',
      tags: ['timing', 'reasons'],
      title: 'A rainy alternative',
      icon: '🌧️',
      prompt: 'If it rains tomorrow, I will not go to the park; I will go to the museum.',
      pieces: [
        { id: 'ashita', jp: 'あした', romaji: 'ashita', en: 'tomorrow' },
        { id: 'ame', jp: 'あめ', romaji: 'ame', en: 'rain' },
        { id: 'dattara', jp: 'だったら', romaji: 'dattara', en: 'if it is / if it rains' },
        { id: 'kouen', jp: 'こうえん', romaji: 'kouen', en: 'park' },
        { id: 'ni-park', jp: 'に', romaji: 'ni', en: 'to / destination marker' },
        { id: 'ikimasen', jp: 'いきません', romaji: 'ikimasen', en: 'will not go' },
        { id: 'hakubutsukan', jp: 'はくぶつかん', romaji: 'hakubutsukan', en: 'museum' },
        { id: 'ni-museum', jp: 'に', romaji: 'ni', en: 'to / destination marker' },
        { id: 'ikimasu', jp: 'いきます', romaji: 'ikimasu', en: 'will go' },
      ],
      scrambled: ['ni-museum', 'ame', 'ikimasen', 'ashita', 'hakubutsukan', 'dattara', 'ikimasu', 'kouen', 'ni-park'],
      answer: ['ashita', 'ame', 'dattara', 'kouen', 'ni-park', 'ikimasen', 'hakubutsukan', 'ni-museum', 'ikimasu'],
      pattern: 'Condition/-tara + negative result + alternative result',
      explanation:
        'Ashita sets the context and ame dattara means “if it rains” or literally “if it is rain.” Each destination keeps its own ni: kouen ni belongs with the negative ikimasen, while hakubutsukan ni belongs with the final ikimasu. Japanese can state the alternative as a second result without inserting a separate word for “instead.”',
    },
    {
      id: 'breakfast-at-seven',
      difficulty: 'Foundation',
      tags: ['timing'],
      title: 'Breakfast at seven',
      icon: '🍳',
      prompt: 'Every day I eat breakfast at seven.',
      pieces: [
        { id: 'mainichi', jp: '毎日', romaji: 'mainichi', en: 'every day' },
        { id: 'shichiji', jp: '七時', romaji: 'shichiji', en: 'seven o’clock' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'at / time marker' },
        { id: 'asagohan', jp: '朝ご飯', romaji: 'asagohan', en: 'breakfast' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'tabemasu', jp: '食べます', romaji: 'tabemasu', en: 'eat' },
      ],
      scrambled: ['asagohan', 'ni', 'mainichi', 'tabemasu', 'shichiji', 'o'],
      answer: ['mainichi', 'shichiji', 'ni', 'asagohan', 'o', 'tabemasu'],
      alsoAcceptable: [
        {
          answer: ['mainichi', 'asagohan', 'o', 'shichiji', 'ni', 'tabemasu'],
          explanation:
            'The object can come before the clock time because o and ni keep the roles clear. The preferred answer uses the more neutral progression from broad frequency to specific time, then object.',
        },
      ],
      pattern: 'Frequency + clock time/ni + object/o + verb',
      explanation:
        'Mainichi sets the frequency and needs no particle. A specific clock time takes ni, so it follows shichiji. O marks asagohan as the object, and the verb tabemasu comes last.',
    },
    {
      id: 'late-yesterday',
      difficulty: 'Foundation',
      tags: ['question', 'timing', 'reasons'],
      title: 'Late yesterday',
      icon: '⏰',
      prompt: 'Why were you late yesterday?',
      pieces: [
        { id: 'kinou', jp: '昨日', romaji: 'kinou', en: 'yesterday' },
        { id: 'wa', jp: 'は', romaji: 'wa', en: 'topic marker' },
        { id: 'naze', jp: 'なぜ', romaji: 'naze', en: 'why' },
        { id: 'okuremashita', jp: '遅れました', romaji: 'okuremashita', en: 'was late' },
        { id: 'ka', jp: 'か', romaji: 'ka', en: 'question marker' },
      ],
      scrambled: ['ka', 'wa', 'okuremashita', 'kinou', 'naze'],
      answer: ['kinou', 'wa', 'naze', 'okuremashita', 'ka'],
      alsoAcceptable: [
        {
          answer: ['naze', 'kinou', 'wa', 'okuremashita', 'ka'],
          explanation:
            'Starting with naze is grammatical when “why” is strongly foregrounded. The preferred answer first establishes yesterday as the topic, which is the more neutral information order.',
        },
      ],
      pattern: 'Time/wa + reason question word + past verb + ka',
      explanation:
        'Kinou wa establishes yesterday as the topic. Naze asks for the reason, okuremashita is the polite past form of “be late,” and the final ka marks the question. “You” is omitted because it is understood from context.',
    },
    {
      id: 'bento-before-boarding',
      difficulty: 'Foundation',
      tags: ['timing'],
      title: 'Bento before boarding',
      icon: '🍱',
      prompt: 'I will buy a bento before boarding the train.',
      pieces: [
        { id: 'densha', jp: '電車', romaji: 'densha', en: 'train' },
        { id: 'ni-train', jp: 'に', romaji: 'ni', en: 'target marker' },
        { id: 'noru', jp: '乗る', romaji: 'noru', en: 'board / ride (plain form)' },
        { id: 'mae', jp: '前', romaji: 'mae', en: 'before' },
        { id: 'ni-time', jp: 'に', romaji: 'ni', en: 'time marker' },
        { id: 'obentou', jp: 'お弁当', romaji: 'obentou', en: 'boxed lunch / bento' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'kaimasu', jp: '買います', romaji: 'kaimasu', en: 'will buy' },
      ],
      scrambled: ['mae', 'o', 'noru', 'ni-time', 'densha', 'kaimasu', 'obentou', 'ni-train'],
      answer: ['densha', 'ni-train', 'noru', 'mae', 'ni-time', 'obentou', 'o', 'kaimasu'],
      alsoAcceptable: [
        {
          answer: ['obentou', 'o', 'densha', 'ni-train', 'noru', 'mae', 'ni-time', 'kaimasu'],
          explanation:
            'The object can lead because o still identifies what will be bought. This foregrounds the bento, while the preferred answer uses the before-boarding clause as opening time context.',
        },
      ],
      pattern: 'Plain verb + mae ni + object/o + main verb',
      explanation:
        'Ni marks densha as the target of noru, “to board.” A verb before mae uses its plain non-past form, so noru mae ni means “before boarding.” O marks the bento as the object of kaimasu.',
    },
    {
      id: 'hotel-rain-plan',
      difficulty: 'Foundation',
      tags: ['reasons'],
      title: 'Rain plan',
      icon: '🌦️',
      prompt: 'If it rains, I will rest at the hotel.',
      pieces: [
        { id: 'ame', jp: '雨', romaji: 'ame', en: 'rain' },
        { id: 'ga', jp: 'が', romaji: 'ga', en: 'subject marker' },
        { id: 'futtara', jp: '降ったら', romaji: 'futtara', en: 'if it rains' },
        { id: 'hoteru', jp: 'ホテル', romaji: 'hoteru', en: 'hotel' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'place-of-action marker' },
        { id: 'yasumimasu', jp: '休みます', romaji: 'yasumimasu', en: 'will rest' },
      ],
      scrambled: ['hoteru', 'futtara', 'de', 'ame', 'yasumimasu', 'ga'],
      answer: ['ame', 'ga', 'futtara', 'hoteru', 'de', 'yasumimasu'],
      pattern: 'Subject/ga + conditional/-tara + place/de + result',
      explanation:
        'Ga marks rain as the subject. Futtara is the conditional form of furu, creating “if it rains.” In the result clause, de marks the hotel as where the resting happens, and yasumimasu comes last.',
    },
    {
      id: 'sick-day',
      difficulty: 'Foundation',
      tags: ['timing', 'reasons'],
      title: 'Sick day',
      icon: '🤒',
      prompt: 'Because I was sick, I did not go to work yesterday.',
      pieces: [
        { id: 'byouki', jp: '病気', romaji: 'byouki', en: 'illness / sick' },
        { id: 'deshita-sick', jp: 'でした', romaji: 'deshita', en: 'was (polite past)' },
        { id: 'kara', jp: 'から', romaji: 'kara', en: 'because' },
        { id: 'kinou', jp: '昨日', romaji: 'kinou', en: 'yesterday' },
        { id: 'wa', jp: 'は', romaji: 'wa', en: 'topic marker' },
        { id: 'shigoto', jp: '仕事', romaji: 'shigoto', en: 'work' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'to / destination marker' },
        { id: 'ikimasen', jp: '行きません', romaji: 'ikimasen', en: 'do not go' },
        { id: 'deshita-go', jp: 'でした', romaji: 'deshita', en: 'past polite ending' },
      ],
      scrambled: ['ni', 'deshita-go', 'kinou', 'byouki', 'shigoto', 'kara', 'wa', 'ikimasen', 'deshita-sick'],
      answer: ['byouki', 'deshita-sick', 'kara', 'kinou', 'wa', 'shigoto', 'ni', 'ikimasen', 'deshita-go'],
      alsoAcceptable: [
        {
          answer: ['kinou', 'wa', 'byouki', 'deshita-sick', 'kara', 'shigoto', 'ni', 'ikimasen', 'deshita-go'],
          explanation:
            'Yesterday can be established before the reason clause. This is valid, but the preferred answer keeps the complete reason first and then states its result in a clearer cause-to-effect order.',
        },
      ],
      pattern: 'Past reason + kara + time/wa + destination/ni + negative past verb',
      explanation:
        'Byouki deshita means “was sick,” and kara turns it into the reason. Kinou wa sets yesterday as the time frame. Ni marks work as the destination, while ikimasen deshita means “did not go.”',
    },
    {
      id: 'opening-time',
      difficulty: 'Foundation',
      tags: ['question', 'timing'],
      title: 'Opening time',
      icon: '🕘',
      prompt: 'What time does the shop open?',
      pieces: [
        { id: 'mise', jp: '店', romaji: 'mise', en: 'shop' },
        { id: 'wa', jp: 'は', romaji: 'wa', en: 'topic marker' },
        { id: 'nanji', jp: '何時', romaji: 'nanji', en: 'what time' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'at / time marker' },
        { id: 'akimasu', jp: '開きます', romaji: 'akimasu', en: 'opens' },
        { id: 'ka', jp: 'か', romaji: 'ka', en: 'question marker' },
      ],
      scrambled: ['ni', 'ka', 'mise', 'akimasu', 'wa', 'nanji'],
      answer: ['mise', 'wa', 'nanji', 'ni', 'akimasu', 'ka'],
      alsoAcceptable: [
        {
          answer: ['nanji', 'ni', 'mise', 'wa', 'akimasu', 'ka'],
          explanation:
            'The time question can lead when it is strongly foregrounded. The preferred answer first identifies the shop as the topic, which is the neutral question pattern.',
        },
      ],
      pattern: 'Topic/wa + time question/ni + verb + ka',
      explanation:
        'Wa marks the shop as the topic. Nanji asks “what time” and takes ni, just as a stated clock time would. Akimasu means “opens,” and the final ka makes it a polite question.',
    },
    {
      id: 'missed-train',
      difficulty: 'Foundation',
      tags: ['reasons'],
      title: 'Missed train',
      icon: '🚫',
      prompt: 'Because I missed the train, I was late.',
      pieces: [
        { id: 'densha', jp: '電車', romaji: 'densha', en: 'train' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'target marker' },
        { id: 'noriokureta', jp: '乗り遅れた', romaji: 'noriokureta', en: 'missed / failed to board' },
        { id: 'node', jp: 'ので', romaji: 'node', en: 'because / since' },
        { id: 'chikoku', jp: '遅刻', romaji: 'chikoku', en: 'lateness' },
        { id: 'shimashita', jp: 'しました', romaji: 'shimashita', en: 'did (polite past)' },
      ],
      scrambled: ['shimashita', 'node', 'densha', 'chikoku', 'ni', 'noriokureta'],
      answer: ['densha', 'ni', 'noriokureta', 'node', 'chikoku', 'shimashita'],
      pattern: 'Plain past reason + node + polite past result',
      explanation:
        'Ni identifies the train that was missed. The reason before node uses the plain past form noriokureta. Node connects the reason to its result and is somewhat softer than kara. Chikoku shimashita means “was late.”',
    },
    {
      id: 'after-work',
      difficulty: 'Foundation',
      tags: ['timing'],
      title: 'After work',
      icon: '🤝',
      prompt: 'I will meet a friend after work.',
      pieces: [
        { id: 'shigoto', jp: '仕事', romaji: 'shigoto', en: 'work' },
        { id: 'no', jp: 'の', romaji: 'no', en: 'linking particle' },
        { id: 'ato', jp: '後', romaji: 'ato', en: 'after' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'completes the time expression' },
        { id: 'tomodachi', jp: '友達', romaji: 'tomodachi', en: 'friend' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'person met / target marker' },
        { id: 'aimasu', jp: '会います', romaji: 'aimasu', en: 'will meet' },
      ],
      scrambled: ['ato', 'aimasu', 'ni', 'shigoto', 'tomodachi', 'de', 'no'],
      answer: ['shigoto', 'no', 'ato', 'de', 'tomodachi', 'ni', 'aimasu'],
      alsoAcceptable: [
        {
          answer: ['tomodachi', 'ni', 'shigoto', 'no', 'ato', 'de', 'aimasu'],
          explanation:
            'The person being met can lead because ni preserves that role. This foregrounds the friend, while the preferred answer opens with the time phrase as neutral context.',
        },
      ],
      pattern: 'Noun/no ato de + person/ni + au',
      explanation:
        'No connects shigoto and ato, forming “after work”; de completes the expression no ato de. With au, the person being met is marked with ni. The verb aimasu comes last.',
    },
    {
      id: 'good-price',
      difficulty: 'Foundation',
      tags: ['reasons'],
      title: 'A good price',
      icon: '🏷️',
      prompt: 'Because it is cheap, I will buy this souvenir.',
      pieces: [
        { id: 'yasui', jp: '安い', romaji: 'yasui', en: 'cheap' },
        { id: 'kara', jp: 'から', romaji: 'kara', en: 'because' },
        { id: 'kono', jp: 'この', romaji: 'kono', en: 'this (before a noun)' },
        { id: 'omiyage', jp: 'お土産', romaji: 'omiyage', en: 'souvenir' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'kaimasu', jp: '買います', romaji: 'kaimasu', en: 'will buy' },
      ],
      scrambled: ['o', 'omiyage', 'kara', 'kaimasu', 'yasui', 'kono'],
      answer: ['yasui', 'kara', 'kono', 'omiyage', 'o', 'kaimasu'],
      pattern: 'I-adjective + kara + demonstrative noun phrase/o + result',
      explanation:
        'An i-adjective can come directly before kara, so yasui kara means “because it is cheap.” Kono must come directly before its noun. O marks kono omiyage as the object, and kaimasu expresses the resulting decision.',
    },
    {
      id: 'reason-to-study',
      difficulty: 'Foundation',
      tags: ['question', 'reasons'],
      title: 'Reason to study',
      icon: '📚',
      prompt: 'Why are you studying Japanese?',
      pieces: [
        { id: 'naze', jp: 'なぜ', romaji: 'naze', en: 'why' },
        { id: 'nihongo', jp: '日本語', romaji: 'nihongo', en: 'Japanese language' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'benkyou', jp: '勉強', romaji: 'benkyou', en: 'study' },
        { id: 'shite', jp: 'して', romaji: 'shite', en: 'doing (te-form)' },
        { id: 'imasu', jp: 'います', romaji: 'imasu', en: 'ongoing action' },
        { id: 'ka', jp: 'か', romaji: 'ka', en: 'question marker' },
      ],
      scrambled: ['imasu', 'nihongo', 'naze', 'ka', 'benkyou', 'o', 'shite'],
      answer: ['naze', 'nihongo', 'o', 'benkyou', 'shite', 'imasu', 'ka'],
      alsoAcceptable: [
        {
          answer: ['nihongo', 'o', 'naze', 'benkyou', 'shite', 'imasu', 'ka'],
          explanation:
            'The object can lead because o preserves its role. This foregrounds Japanese, while the preferred answer puts the reason question word first for a more neutral request for explanation.',
        },
      ],
      pattern: 'Reason question word + object/o + te imasu + ka',
      explanation:
        'Naze asks for the reason. O marks Japanese as what is being studied. Benkyou shite imasu describes an ongoing activity, and the final ka makes it a polite question. The understood “you” is omitted.',
    },
  ],
}

export default puzzles
