const puzzles = {
  id: 'sentence-builder',
  title: 'Sentence Builder',
  tags: ['question', 'timing', 'reasons'],
  intro:
    'Start with the Foundation sentences, then tackle longer, multi-clause Advanced challenges. Particles are separate tiles, so every wa, ga, o, ni, and de has to land in the right place.',
  puzzles: [
    {
      id: 'morning-coffee',
      difficulty: 'Foundation',
      tags: ['timing'],
      title: 'Morning coffee',
      icon: '☕',
      prompt: 'I drink coffee every morning.',
      pieces: [
        { id: 'watashi', jp: 'わたし', romaji: 'watashi', en: 'I / me' },
        { id: 'wa', jp: 'は', romaji: 'wa', en: 'topic marker' },
        { id: 'maiasa', jp: 'まいあさ', romaji: 'maiasa', en: 'every morning' },
        { id: 'koohii', jp: 'コーヒー', romaji: 'koohii', en: 'coffee' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'nomimasu', jp: 'のみます', romaji: 'nomimasu', en: 'drink' },
      ],
      scrambled: ['koohii', 'nomimasu', 'wa', 'maiasa', 'o', 'watashi'],
      answer: ['watashi', 'wa', 'maiasa', 'koohii', 'o', 'nomimasu'],
      acceptedAnswers: [
        ['watashi', 'wa', 'maiasa', 'koohii', 'o', 'nomimasu'],
        ['maiasa', 'watashi', 'wa', 'koohii', 'o', 'nomimasu'],
      ],
      pattern: 'Topic + time + object + verb',
      explanation:
        'Wa comes immediately after watashi to mark “I” as the topic. Maiasa needs no particle. O follows koohii to mark coffee as the direct object, and nomimasu, the action, comes last. The time phrase may also lead the sentence, so “maiasa watashi wa …” is accepted too.',
    },
    {
      id: 'station',
      difficulty: 'Foundation',
      tags: ['question'],
      title: 'Find the station',
      icon: '🚉',
      prompt: 'Where is the train station?',
      pieces: [
        { id: 'eki', jp: 'えき', romaji: 'eki', en: 'station' },
        { id: 'wa', jp: 'は', romaji: 'wa', en: 'topic marker' },
        { id: 'doko', jp: 'どこ', romaji: 'doko', en: 'where' },
        { id: 'desu', jp: 'です', romaji: 'desu', en: 'is / polite copula' },
        { id: 'ka', jp: 'か', romaji: 'ka', en: 'question marker' },
      ],
      scrambled: ['ka', 'eki', 'desu', 'wa', 'doko'],
      answer: ['eki', 'wa', 'doko', 'desu', 'ka'],
      pattern: 'Topic + question word + desu + ka',
      explanation:
        'Wa follows eki and introduces the station as the topic. Doko occupies the place where the missing answer would go. Desu links the topic to that answer politely, and the final ka turns the whole sentence into a question.',
    },
    {
      id: 'ramen',
      difficulty: 'Foundation',
      tags: [],
      title: 'Ramen stop',
      icon: '🍜',
      prompt: 'I will eat ramen at the restaurant.',
      pieces: [
        { id: 'resutoran', jp: 'レストラン', romaji: 'resutoran', en: 'restaurant' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'at / place-of-action marker' },
        { id: 'raamen', jp: 'ラーメン', romaji: 'raamen', en: 'ramen' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'tabemasu', jp: 'たべます', romaji: 'tabemasu', en: 'eat / will eat' },
      ],
      scrambled: ['tabemasu', 'o', 'resutoran', 'raamen', 'de'],
      answer: ['resutoran', 'de', 'raamen', 'o', 'tabemasu'],
      pattern: 'Place + de + object + o + verb',
      explanation:
        'De follows resutoran and marks it as the place where eating happens. O follows raamen and marks ramen as what is eaten. Tabemasu comes last; this polite non-past form can mean either “eat” or “will eat,” with context supplying the future meaning here.',
    },
    {
      id: 'kyoto',
      difficulty: 'Foundation',
      tags: ['timing'],
      title: 'Kyoto tomorrow',
      icon: '🚄',
      prompt: 'Tomorrow I will go to Kyoto by train.',
      pieces: [
        { id: 'ashita', jp: 'あした', romaji: 'ashita', en: 'tomorrow' },
        { id: 'densha', jp: 'でんしゃ', romaji: 'densha', en: 'train' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'by / means marker' },
        { id: 'kyouto', jp: 'きょうと', romaji: 'Kyouto', en: 'Kyoto' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'to / destination marker' },
        { id: 'ikimasu', jp: 'いきます', romaji: 'ikimasu', en: 'go / will go' },
      ],
      scrambled: ['ni', 'ikimasu', 'densha', 'ashita', 'kyouto', 'de'],
      answer: ['ashita', 'densha', 'de', 'kyouto', 'ni', 'ikimasu'],
      acceptedAnswers: [
        ['ashita', 'densha', 'de', 'kyouto', 'ni', 'ikimasu'],
        ['ashita', 'kyouto', 'ni', 'densha', 'de', 'ikimasu'],
      ],
      pattern: 'Time + means/de + destination/ni + movement verb',
      explanation:
        'Ashita sets the time without a particle. De must follow densha to mark the means of travel, while ni must follow Kyouto to mark the destination. Ikimasu finishes the thought. The train phrase and the Kyoto phrase may trade places, so both natural versions are accepted.',
    },
    {
      id: 'tickets',
      difficulty: 'Foundation',
      tags: [],
      title: 'Two tickets',
      icon: '🎫',
      prompt: 'Please give me two tickets.',
      pieces: [
        { id: 'kippu', jp: 'きっぷ', romaji: 'kippu', en: 'ticket' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'nimai', jp: 'にまい', romaji: 'nimai', en: 'two flat items' },
        { id: 'kudasai', jp: 'ください', romaji: 'kudasai', en: 'please give me' },
      ],
      scrambled: ['kudasai', 'o', 'nimai', 'kippu'],
      answer: ['kippu', 'o', 'nimai', 'kudasai'],
      pattern: 'Object + o + quantity/counter + kudasai',
      explanation:
        'O follows kippu and marks tickets as the thing requested. Nimai means “two” using mai, the counter for flat objects such as tickets, and normally follows the counted item. Kudasai comes last to make the polite request “please give me …”.',
    },
    {
      id: 'did-not-understand',
      difficulty: 'Foundation',
      tags: [],
      title: 'Lost in translation',
      icon: '💬',
      prompt: 'I did not understand Japanese.',
      pieces: [
        { id: 'nihongo', jp: 'にほんご', romaji: 'nihongo', en: 'Japanese language' },
        { id: 'ga', jp: 'が', romaji: 'ga', en: 'subject / focus marker' },
        { id: 'wakarimasen', jp: 'わかりません', romaji: 'wakarimasen', en: 'do not understand' },
        { id: 'deshita', jp: 'でした', romaji: 'deshita', en: 'past polite ending' },
      ],
      scrambled: ['deshita', 'ga', 'wakarimasen', 'nihongo'],
      answer: ['nihongo', 'ga', 'wakarimasen', 'deshita'],
      pattern: 'Thing understood + ga + negative verb + past ending',
      explanation:
        'With wakaru, Japanese marks the thing understood with ga, not o, so ga must follow nihongo. Wakarimasen gives the polite negative, “do not understand,” and deshita makes it past: “did not understand.” The speaker is clear from context and can be omitted.',
    },
    {
      id: 'photo',
      difficulty: 'Foundation',
      tags: ['question'],
      title: 'A photo here',
      icon: '📷',
      prompt: 'May I take a picture here?',
      pieces: [
        { id: 'koko', jp: 'ここ', romaji: 'koko', en: 'here' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'place-of-action marker' },
        { id: 'shashin', jp: 'しゃしん', romaji: 'shashin', en: 'picture / photograph' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'totte', jp: 'とって', romaji: 'totte', en: 'take (te-form)' },
        { id: 'mo', jp: 'も', romaji: 'mo', en: 'even if / also' },
        { id: 'ii', jp: 'いい', romaji: 'ii', en: 'good / okay' },
        { id: 'desu', jp: 'です', romaji: 'desu', en: 'is / polite copula' },
        { id: 'ka', jp: 'か', romaji: 'ka', en: 'question marker' },
      ],
      scrambled: ['ka', 'shashin', 'mo', 'koko', 'ii', 'o', 'desu', 'de', 'totte'],
      answer: ['koko', 'de', 'shashin', 'o', 'totte', 'mo', 'ii', 'desu', 'ka'],
      pattern: 'Place/de + object/o + te-form + mo ii desu ka',
      explanation:
        'De follows koko to mark where the action happens, and o follows shashin to mark what is taken. Totte is the te-form of toru. The sequence mo ii desu ka literally asks “is it okay even if …?” Together, te-form + mo ii desu ka is the standard way to ask permission.',
    },
    {
      id: 'hotel',
      difficulty: 'Foundation',
      tags: [],
      title: 'Hotel location',
      icon: '🏨',
      prompt: 'The hotel is near the station.',
      pieces: [
        { id: 'hoteru', jp: 'ホテル', romaji: 'hoteru', en: 'hotel' },
        { id: 'wa', jp: 'は', romaji: 'wa', en: 'topic marker' },
        { id: 'eki', jp: 'えき', romaji: 'eki', en: 'station' },
        { id: 'no', jp: 'の', romaji: 'no', en: 'of / linking particle' },
        { id: 'chikaku', jp: 'ちかく', romaji: 'chikaku', en: 'nearby / vicinity' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'location marker' },
        { id: 'arimasu', jp: 'あります', romaji: 'arimasu', en: 'exists / is (inanimate)' },
      ],
      scrambled: ['ni', 'arimasu', 'no', 'hoteru', 'chikaku', 'wa', 'eki'],
      answer: ['hoteru', 'wa', 'eki', 'no', 'chikaku', 'ni', 'arimasu'],
      pattern: 'Topic/wa + reference/no + location/ni + arimasu',
      explanation:
        'Wa follows hoteru to mark the hotel as the topic. No links eki to chikaku, forming “the station’s vicinity,” and ni marks that vicinity as the hotel’s location. Arimasu is used for the existence or location of an inanimate thing; a person or animal would use imasu.',
    },
    {
      id: 'rainy-taxi',
      difficulty: 'Foundation',
      tags: ['reasons'],
      title: 'Rainy taxi',
      icon: '☔',
      prompt: 'Because it is raining, I will go by taxi.',
      pieces: [
        { id: 'ame', jp: 'あめ', romaji: 'ame', en: 'rain' },
        { id: 'ga', jp: 'が', romaji: 'ga', en: 'subject marker' },
        { id: 'futte', jp: 'ふって', romaji: 'futte', en: 'falling (te-form)' },
        { id: 'imasu', jp: 'います', romaji: 'imasu', en: 'is happening / ongoing' },
        { id: 'kara', jp: 'から', romaji: 'kara', en: 'because' },
        { id: 'takushii', jp: 'タクシー', romaji: 'takushii', en: 'taxi' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'by / means marker' },
        { id: 'ikimasu', jp: 'いきます', romaji: 'ikimasu', en: 'go / will go' },
      ],
      scrambled: ['takushii', 'kara', 'ga', 'ikimasu', 'futte', 'de', 'ame', 'imasu'],
      answer: ['ame', 'ga', 'futte', 'imasu', 'kara', 'takushii', 'de', 'ikimasu'],
      pattern: 'Reason + kara + means/de + action',
      explanation:
        'Ga follows ame because rain is the subject of futte imasu, “is falling.” Kara comes after that complete reason and means “because.” In the result, de follows takushii to mark the means of travel, and ikimasu supplies the final action.',
    },
    {
      id: 'souvenir',
      difficulty: 'Foundation',
      tags: [],
      title: 'Family souvenir',
      icon: '🎁',
      prompt: 'I want to buy a small souvenir for my family.',
      pieces: [
        { id: 'kazoku', jp: 'かぞく', romaji: 'kazoku', en: 'family' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'for / recipient marker' },
        { id: 'chiisai', jp: 'ちいさい', romaji: 'chiisai', en: 'small' },
        { id: 'omiyage', jp: 'おみやげ', romaji: 'omiyage', en: 'souvenir' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'kaitai', jp: 'かいたい', romaji: 'kaitai', en: 'want to buy' },
        { id: 'desu', jp: 'です', romaji: 'desu', en: 'polite ending' },
      ],
      scrambled: ['desu', 'omiyage', 'ni', 'kaitai', 'kazoku', 'o', 'chiisai'],
      answer: ['kazoku', 'ni', 'chiisai', 'omiyage', 'o', 'kaitai', 'desu'],
      pattern: 'Recipient/ni + adjective + object/o + desire + desu',
      explanation:
        'Ni follows kazoku to mark the family as the intended recipient. The i-adjective chiisai goes directly before omiyage, the noun it describes, and o follows that noun to mark it as the object. Kaitai means “want to buy,” and desu makes the statement polite.',
    },
    {
      id: 'time-if',
      difficulty: 'Advanced',
      tags: ['timing', 'reasons'],
      title: 'If there is time',
      icon: '🕰️',
      prompt: 'If I have time tomorrow, I will go to the museum.',
      pieces: [
        { id: 'ashita', jp: 'あした', romaji: 'ashita', en: 'tomorrow' },
        { id: 'jikan', jp: 'じかん', romaji: 'jikan', en: 'time' },
        { id: 'ga', jp: 'が', romaji: 'ga', en: 'subject marker' },
        { id: 'attara', jp: 'あったら', romaji: 'attara', en: 'if there is / if I have' },
        { id: 'hakubutsukan', jp: 'はくぶつかん', romaji: 'hakubutsukan', en: 'museum' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'to / destination marker' },
        { id: 'ikimasu', jp: 'いきます', romaji: 'ikimasu', en: 'will go' },
      ],
      scrambled: ['ni', 'jikan', 'ikimasu', 'ashita', 'attara', 'hakubutsukan', 'ga'],
      answer: ['ashita', 'jikan', 'ga', 'attara', 'hakubutsukan', 'ni', 'ikimasu'],
      pattern: 'Time + condition/-tara + destination/ni + result',
      explanation:
        'Ashita sets the time for the whole sentence. Ga marks jikan as what exists, and attara turns arimasu into the condition “if there is time.” The result follows without a separate word for “then”: hakubutsukan takes ni as the destination, and ikimasu stays last.',
    },
    {
      id: 'slowly-again',
      difficulty: 'Advanced',
      tags: ['reasons'],
      title: 'One more time',
      icon: '🔁',
      prompt: 'If I do not understand, please speak slowly one more time.',
      pieces: [
        { id: 'wakaranakattara', jp: 'わからなかったら', romaji: 'wakaranakattara', en: 'if I do not understand' },
        { id: 'mou', jp: 'もう', romaji: 'mou', en: 'one more / again' },
        { id: 'ichido', jp: 'いちど', romaji: 'ichido', en: 'time / once' },
        { id: 'yukkuri', jp: 'ゆっくり', romaji: 'yukkuri', en: 'slowly' },
        { id: 'hanashite', jp: 'はなして', romaji: 'hanashite', en: 'speak (te-form)' },
        { id: 'kudasai', jp: 'ください', romaji: 'kudasai', en: 'please' },
      ],
      scrambled: ['ichido', 'kudasai', 'wakaranakattara', 'hanashite', 'mou', 'yukkuri'],
      answer: ['wakaranakattara', 'mou', 'ichido', 'yukkuri', 'hanashite', 'kudasai'],
      acceptedAnswers: [
        ['wakaranakattara', 'mou', 'ichido', 'yukkuri', 'hanashite', 'kudasai'],
        ['wakaranakattara', 'yukkuri', 'mou', 'ichido', 'hanashite', 'kudasai'],
      ],
      pattern: 'Condition/-tara + frequency + manner + te-form + kudasai',
      explanation:
        'Wakaranakattara is the complete “if I do not understand” condition. Mou ichido forms the fixed phrase “one more time,” while yukkuri describes how to speak. Hanashite is the te-form of hanasu, and kudasai turns it into a polite request. The frequency and manner phrases can trade places, so both natural orders are accepted.',
    },
    {
      id: 'english-please',
      difficulty: 'Advanced',
      tags: ['reasons'],
      title: 'Switch languages',
      icon: '🗣️',
      prompt: 'Because I do not understand Japanese, English please.',
      pieces: [
        { id: 'nihongo', jp: 'にほんご', romaji: 'nihongo', en: 'Japanese language' },
        { id: 'ga', jp: 'が', romaji: 'ga', en: 'subject / focus marker' },
        { id: 'wakarimasen', jp: 'わかりません', romaji: 'wakarimasen', en: 'do not understand' },
        { id: 'kara', jp: 'から', romaji: 'kara', en: 'because' },
        { id: 'eigo', jp: 'えいご', romaji: 'eigo', en: 'English language' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'in / by means of' },
        { id: 'onegai', jp: 'おねがい', romaji: 'onegai', en: 'request / favour' },
        { id: 'shimasu', jp: 'します', romaji: 'shimasu', en: 'do (polite)' },
      ],
      scrambled: ['de', 'kara', 'shimasu', 'nihongo', 'eigo', 'wakarimasen', 'onegai', 'ga'],
      answer: ['nihongo', 'ga', 'wakarimasen', 'kara', 'eigo', 'de', 'onegai', 'shimasu'],
      pattern: 'Reason + kara + language/de + onegai shimasu',
      explanation:
        'Ga marks nihongo as the thing not understood. Kara follows the complete reason, nihongo ga wakarimasen. In the request, de follows eigo to mean “in English,” and onegai shimasu closes the sentence politely.',
    },
    {
      id: 'complex-directions',
      difficulty: 'Advanced',
      tags: [],
      title: 'Two-step directions',
      icon: '🧭',
      prompt: 'Go straight, then turn right at the next corner.',
      pieces: [
        { id: 'massugu', jp: 'まっすぐ', romaji: 'massugu', en: 'straight ahead' },
        { id: 'itte', jp: 'いって', romaji: 'itte', en: 'go (te-form)' },
        { id: 'tsugi', jp: 'つぎ', romaji: 'tsugi', en: 'next' },
        { id: 'no', jp: 'の', romaji: 'no', en: 'linking particle' },
        { id: 'kado', jp: 'かど', romaji: 'kado', en: 'corner' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'route / direct-object marker' },
        { id: 'migi', jp: 'みぎ', romaji: 'migi', en: 'right' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'toward / into' },
        { id: 'magatte', jp: 'まがって', romaji: 'magatte', en: 'turn (te-form)' },
        { id: 'kudasai', jp: 'ください', romaji: 'kudasai', en: 'please' },
      ],
      scrambled: ['ni', 'no', 'kudasai', 'massugu', 'kado', 'magatte', 'o', 'tsugi', 'itte', 'migi'],
      answer: ['massugu', 'itte', 'tsugi', 'no', 'kado', 'o', 'migi', 'ni', 'magatte', 'kudasai'],
      pattern: 'Action in te-form + route/o + direction/ni + request',
      explanation:
        'Massugu modifies itte, whose te-form links the first action to the next. No joins tsugi to kado as “the next corner,” and o marks the corner as the point along the route. Migi ni gives the direction of the turn. Only the final action takes kudasai, so one polite ending covers both instructions.',
    },
    {
      id: 'travel-together',
      difficulty: 'Advanced',
      tags: ['timing'],
      title: 'Travelling together',
      icon: '🚆',
      prompt: 'Tomorrow I will go to Kyoto by train with a friend.',
      pieces: [
        { id: 'ashita', jp: 'あした', romaji: 'ashita', en: 'tomorrow' },
        { id: 'tomodachi', jp: 'ともだち', romaji: 'tomodachi', en: 'friend' },
        { id: 'to', jp: 'と', romaji: 'to', en: 'with / companion marker' },
        { id: 'issho', jp: 'いっしょ', romaji: 'issho', en: 'together' },
        { id: 'ni-together', jp: 'に', romaji: 'ni', en: 'adverb-forming particle' },
        { id: 'densha', jp: 'でんしゃ', romaji: 'densha', en: 'train' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'by / means marker' },
        { id: 'kyouto', jp: 'きょうと', romaji: 'Kyouto', en: 'Kyoto' },
        { id: 'e', jp: 'へ', romaji: 'e', en: 'toward / destination marker' },
        { id: 'ikimasu', jp: 'いきます', romaji: 'ikimasu', en: 'will go' },
      ],
      scrambled: ['de', 'e', 'tomodachi', 'ashita', 'ikimasu', 'ni-together', 'kyouto', 'to', 'densha', 'issho'],
      answer: ['ashita', 'tomodachi', 'to', 'issho', 'ni-together', 'densha', 'de', 'kyouto', 'e', 'ikimasu'],
      acceptedAnswers: [
        ['ashita', 'tomodachi', 'to', 'issho', 'ni-together', 'densha', 'de', 'kyouto', 'e', 'ikimasu'],
        ['ashita', 'tomodachi', 'to', 'issho', 'ni-together', 'kyouto', 'e', 'densha', 'de', 'ikimasu'],
        ['ashita', 'densha', 'de', 'tomodachi', 'to', 'issho', 'ni-together', 'kyouto', 'e', 'ikimasu'],
      ],
      pattern: 'Time + companion/to issho ni + means/de + destination/e + verb',
      explanation:
        'To marks tomodachi as the companion and issho ni completes “together.” De marks densha as the means of travel, while e marks Kyouto as the destination. The particles keep those roles clear, so several neutral phrase orders are accepted, but each particle must stay beside its phrase and ikimasu remains last.',
    },
    {
      id: 'between-buildings',
      difficulty: 'Advanced',
      tags: [],
      title: 'Between two buildings',
      icon: '🏙️',
      prompt: 'There is a convenience store between the bank and the hotel.',
      pieces: [
        { id: 'ginkou', jp: 'ぎんこう', romaji: 'ginkou', en: 'bank' },
        { id: 'to', jp: 'と', romaji: 'to', en: 'and' },
        { id: 'hoteru', jp: 'ホテル', romaji: 'hoteru', en: 'hotel' },
        { id: 'no', jp: 'の', romaji: 'no', en: 'linking particle' },
        { id: 'aida', jp: 'あいだ', romaji: 'aida', en: 'between / interval' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'location marker' },
        { id: 'konbini', jp: 'コンビニ', romaji: 'konbini', en: 'convenience store' },
        { id: 'ga', jp: 'が', romaji: 'ga', en: 'subject marker' },
        { id: 'arimasu', jp: 'あります', romaji: 'arimasu', en: 'exists / there is' },
      ],
      scrambled: ['arimasu', 'no', 'ginkou', 'ga', 'aida', 'hoteru', 'ni', 'to', 'konbini'],
      answer: ['ginkou', 'to', 'hoteru', 'no', 'aida', 'ni', 'konbini', 'ga', 'arimasu'],
      pattern: 'A to B no aida ni + thing/ga + arimasu',
      explanation:
        'To joins the two reference points, ginkou and hoteru. No connects that pair to aida, creating “the space between the bank and the hotel,” and ni marks it as the location. Ga marks konbini as the thing that exists, and arimasu is used because it is inanimate.',
    },
    {
      id: 'checkout-luggage',
      difficulty: 'Advanced',
      tags: ['question', 'timing'],
      title: 'After check-out',
      icon: '🧳',
      prompt: 'Could you hold my luggage after check-out?',
      pieces: [
        { id: 'chekkuauto', jp: 'チェックアウト', romaji: 'chekkuauto', en: 'check-out' },
        { id: 'no', jp: 'の', romaji: 'no', en: 'linking particle' },
        { id: 'ato', jp: 'あと', romaji: 'ato', en: 'after' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'at / in the period after' },
        { id: 'nimotsu', jp: 'にもつ', romaji: 'nimotsu', en: 'luggage' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'azukatte', jp: 'あずかって', romaji: 'azukatte', en: 'hold / look after (te-form)' },
        { id: 'moraemasu', jp: 'もらえます', romaji: 'moraemasu', en: 'can I receive the favour' },
        { id: 'ka', jp: 'か', romaji: 'ka', en: 'question marker' },
      ],
      scrambled: ['moraemasu', 'nimotsu', 'de', 'ka', 'ato', 'azukatte', 'no', 'o', 'chekkuauto'],
      answer: ['chekkuauto', 'no', 'ato', 'de', 'nimotsu', 'o', 'azukatte', 'moraemasu', 'ka'],
      pattern: 'Event/no ato de + object/o + te-form + moraemasu ka',
      explanation:
        'No links chekkuauto to ato, and de completes the time expression “after check-out.” O marks nimotsu as what the hotel will hold. The te-form azukatte connects to moraemasu ka, literally asking whether you can receive that favour; this is softer than a direct te-form + kudasai request.',
    },
    {
      id: 'bullet-train-tickets',
      difficulty: 'Advanced',
      tags: ['timing'],
      title: 'Timed ticket request',
      icon: '🎟️',
      prompt: 'Two tickets for tomorrow’s 3 p.m. bullet train, please.',
      pieces: [
        { id: 'ashita', jp: 'あした', romaji: 'ashita', en: 'tomorrow' },
        { id: 'gogo', jp: 'ごご', romaji: 'gogo', en: 'p.m. / afternoon' },
        { id: 'sanji', jp: 'さんじ', romaji: 'sanji', en: 'three o’clock' },
        { id: 'no-time', jp: 'の', romaji: 'no', en: 'linking particle' },
        { id: 'shinkansen', jp: 'しんかんせん', romaji: 'shinkansen', en: 'bullet train' },
        { id: 'no-train', jp: 'の', romaji: 'no', en: 'linking particle' },
        { id: 'kippu', jp: 'きっぷ', romaji: 'kippu', en: 'ticket' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'nimai', jp: 'にまい', romaji: 'nimai', en: 'two flat items' },
        { id: 'kudasai', jp: 'ください', romaji: 'kudasai', en: 'please give me' },
      ],
      scrambled: ['no-train', 'nimai', 'gogo', 'kippu', 'ashita', 'kudasai', 'shinkansen', 'o', 'no-time', 'sanji'],
      answer: ['ashita', 'gogo', 'sanji', 'no-time', 'shinkansen', 'no-train', 'kippu', 'o', 'nimai', 'kudasai'],
      pattern: 'Date + time/no + train/no + item/o + counter + kudasai',
      explanation:
        'Ashita and gogo sanji combine as “tomorrow at 3 p.m.” The first no attaches that time to shinkansen, and the second attaches the train to kippu, building one long noun phrase from left to right. O marks the tickets as requested, nimai counts two flat items, and kudasai comes last.',
    },
    {
      id: 'broken-air-conditioner',
      difficulty: 'Advanced',
      tags: ['question', 'reasons'],
      title: 'Room problem',
      icon: '🛎️',
      prompt: 'Because the air conditioner is broken, could you change my room?',
      pieces: [
        { id: 'eakon', jp: 'エアコン', romaji: 'eakon', en: 'air conditioner' },
        { id: 'ga', jp: 'が', romaji: 'ga', en: 'subject marker' },
        { id: 'kowarete', jp: 'こわれて', romaji: 'kowarete', en: 'broken (te-form)' },
        { id: 'imasu', jp: 'います', romaji: 'imasu', en: 'is in that state' },
        { id: 'node', jp: 'ので', romaji: 'node', en: 'because / since' },
        { id: 'heya', jp: 'へや', romaji: 'heya', en: 'room' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'kaete', jp: 'かえて', romaji: 'kaete', en: 'change (te-form)' },
        { id: 'moraemasu', jp: 'もらえます', romaji: 'moraemasu', en: 'can I receive the favour' },
        { id: 'ka', jp: 'か', romaji: 'ka', en: 'question marker' },
      ],
      scrambled: ['heya', 'node', 'moraemasu', 'ga', 'kaete', 'imasu', 'ka', 'eakon', 'o', 'kowarete'],
      answer: ['eakon', 'ga', 'kowarete', 'imasu', 'node', 'heya', 'o', 'kaete', 'moraemasu', 'ka'],
      pattern: 'State/reason + node + object/o + te-form + moraemasu ka',
      explanation:
        'Ga marks eakon as the thing in the broken state, expressed by kowarete imasu. Node follows that full clause and gives a softer “because” than kara. In the request, o marks heya as what should be changed, and kaete moraemasu ka politely asks the listener to do that favour.',
    },
    {
      id: 'rain-plan',
      difficulty: 'Advanced',
      tags: ['timing', 'reasons'],
      title: 'A rainy alternative',
      icon: '🌧️',
      prompt: 'If it rains tomorrow, I will not go to the park; I will go to the museum.',
      pieces: [
        { id: 'ashita', jp: 'あした', romaji: 'ashita', en: 'tomorrow' },
        { id: 'ame', jp: 'あめ', romaji: 'ame', en: 'rain' },
        { id: 'dattara', jp: 'だったら', romaji: 'dattara', en: 'if it is / if it rains' },
        { id: 'kouen', jp: 'こうえん', romaji: 'kouen', en: 'park' },
        { id: 'ni-park', jp: 'に', romaji: 'ni', en: 'to / destination marker' },
        { id: 'ikimasen', jp: 'いきません', romaji: 'ikimasen', en: 'will not go' },
        { id: 'hakubutsukan', jp: 'はくぶつかん', romaji: 'hakubutsukan', en: 'museum' },
        { id: 'ni-museum', jp: 'に', romaji: 'ni', en: 'to / destination marker' },
        { id: 'ikimasu', jp: 'いきます', romaji: 'ikimasu', en: 'will go' },
      ],
      scrambled: ['ni-museum', 'ame', 'ikimasen', 'ashita', 'hakubutsukan', 'dattara', 'ikimasu', 'kouen', 'ni-park'],
      answer: ['ashita', 'ame', 'dattara', 'kouen', 'ni-park', 'ikimasen', 'hakubutsukan', 'ni-museum', 'ikimasu'],
      pattern: 'Condition/-tara + negative result + alternative result',
      explanation:
        'Ashita sets the context and ame dattara means “if it rains” or literally “if it is rain.” Each destination keeps its own ni: kouen ni belongs with the negative ikimasen, while hakubutsukan ni belongs with the final ikimasu. Japanese can state the alternative as a second result without inserting a separate word for “instead.”',
    },
  ],
}

export default puzzles
