const puzzles = {
  id: 'sentence-builder',
  title: 'Sentence Builder',
  intro:
    'Put the romaji tiles into one natural Japanese order. Particles are separate tiles, so every wa, ga, o, ni, and de has to land in the right place.',
  puzzles: [
    {
      id: 'morning-coffee',
      title: 'Morning coffee',
      icon: '☕',
      prompt: 'I drink coffee every morning.',
      pieces: [
        { id: 'watashi', jp: 'わたし', romaji: 'watashi', en: 'I / me' },
        { id: 'wa', jp: 'は', romaji: 'wa', en: 'topic marker' },
        { id: 'maiasa', jp: 'まいあさ', romaji: 'maiasa', en: 'every morning' },
        { id: 'koohii', jp: 'コーヒー', romaji: 'koohii', en: 'coffee' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'nomimasu', jp: 'のみます', romaji: 'nomimasu', en: 'drink' },
      ],
      scrambled: ['koohii', 'nomimasu', 'wa', 'maiasa', 'o', 'watashi'],
      answer: ['watashi', 'wa', 'maiasa', 'koohii', 'o', 'nomimasu'],
      acceptedAnswers: [
        ['watashi', 'wa', 'maiasa', 'koohii', 'o', 'nomimasu'],
        ['maiasa', 'watashi', 'wa', 'koohii', 'o', 'nomimasu'],
      ],
      pattern: 'Topic + time + object + verb',
      explanation:
        'Wa comes immediately after watashi to mark “I” as the topic. Maiasa needs no particle. O follows koohii to mark coffee as the direct object, and nomimasu, the action, comes last. The time phrase may also lead the sentence, so “maiasa watashi wa …” is accepted too.',
    },
    {
      id: 'station',
      title: 'Find the station',
      icon: '🚉',
      prompt: 'Where is the train station?',
      pieces: [
        { id: 'eki', jp: 'えき', romaji: 'eki', en: 'station' },
        { id: 'wa', jp: 'は', romaji: 'wa', en: 'topic marker' },
        { id: 'doko', jp: 'どこ', romaji: 'doko', en: 'where' },
        { id: 'desu', jp: 'です', romaji: 'desu', en: 'is / polite copula' },
        { id: 'ka', jp: 'か', romaji: 'ka', en: 'question marker' },
      ],
      scrambled: ['ka', 'eki', 'desu', 'wa', 'doko'],
      answer: ['eki', 'wa', 'doko', 'desu', 'ka'],
      pattern: 'Topic + question word + desu + ka',
      explanation:
        'Wa follows eki and introduces the station as the topic. Doko occupies the place where the missing answer would go. Desu links the topic to that answer politely, and the final ka turns the whole sentence into a question.',
    },
    {
      id: 'ramen',
      title: 'Ramen stop',
      icon: '🍜',
      prompt: 'I will eat ramen at the restaurant.',
      pieces: [
        { id: 'resutoran', jp: 'レストラン', romaji: 'resutoran', en: 'restaurant' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'at / place-of-action marker' },
        { id: 'raamen', jp: 'ラーメン', romaji: 'raamen', en: 'ramen' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'tabemasu', jp: 'たべます', romaji: 'tabemasu', en: 'eat / will eat' },
      ],
      scrambled: ['tabemasu', 'o', 'resutoran', 'raamen', 'de'],
      answer: ['resutoran', 'de', 'raamen', 'o', 'tabemasu'],
      pattern: 'Place + de + object + o + verb',
      explanation:
        'De follows resutoran and marks it as the place where eating happens. O follows raamen and marks ramen as what is eaten. Tabemasu comes last; this polite non-past form can mean either “eat” or “will eat,” with context supplying the future meaning here.',
    },
    {
      id: 'kyoto',
      title: 'Kyoto tomorrow',
      icon: '🚄',
      prompt: 'Tomorrow I will go to Kyoto by train.',
      pieces: [
        { id: 'ashita', jp: 'あした', romaji: 'ashita', en: 'tomorrow' },
        { id: 'densha', jp: 'でんしゃ', romaji: 'densha', en: 'train' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'by / means marker' },
        { id: 'kyouto', jp: 'きょうと', romaji: 'Kyouto', en: 'Kyoto' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'to / destination marker' },
        { id: 'ikimasu', jp: 'いきます', romaji: 'ikimasu', en: 'go / will go' },
      ],
      scrambled: ['ni', 'ikimasu', 'densha', 'ashita', 'kyouto', 'de'],
      answer: ['ashita', 'densha', 'de', 'kyouto', 'ni', 'ikimasu'],
      acceptedAnswers: [
        ['ashita', 'densha', 'de', 'kyouto', 'ni', 'ikimasu'],
        ['ashita', 'kyouto', 'ni', 'densha', 'de', 'ikimasu'],
      ],
      pattern: 'Time + means/de + destination/ni + movement verb',
      explanation:
        'Ashita sets the time without a particle. De must follow densha to mark the means of travel, while ni must follow Kyouto to mark the destination. Ikimasu finishes the thought. The train phrase and the Kyoto phrase may trade places, so both natural versions are accepted.',
    },
    {
      id: 'tickets',
      title: 'Two tickets',
      icon: '🎫',
      prompt: 'Please give me two tickets.',
      pieces: [
        { id: 'kippu', jp: 'きっぷ', romaji: 'kippu', en: 'ticket' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'nimai', jp: 'にまい', romaji: 'nimai', en: 'two flat items' },
        { id: 'kudasai', jp: 'ください', romaji: 'kudasai', en: 'please give me' },
      ],
      scrambled: ['kudasai', 'o', 'nimai', 'kippu'],
      answer: ['kippu', 'o', 'nimai', 'kudasai'],
      pattern: 'Object + o + quantity/counter + kudasai',
      explanation:
        'O follows kippu and marks tickets as the thing requested. Nimai means “two” using mai, the counter for flat objects such as tickets, and normally follows the counted item. Kudasai comes last to make the polite request “please give me …”.',
    },
    {
      id: 'did-not-understand',
      title: 'Lost in translation',
      icon: '💬',
      prompt: 'I did not understand Japanese.',
      pieces: [
        { id: 'nihongo', jp: 'にほんご', romaji: 'nihongo', en: 'Japanese language' },
        { id: 'ga', jp: 'が', romaji: 'ga', en: 'subject / focus marker' },
        { id: 'wakarimasen', jp: 'わかりません', romaji: 'wakarimasen', en: 'do not understand' },
        { id: 'deshita', jp: 'でした', romaji: 'deshita', en: 'past polite ending' },
      ],
      scrambled: ['deshita', 'ga', 'wakarimasen', 'nihongo'],
      answer: ['nihongo', 'ga', 'wakarimasen', 'deshita'],
      pattern: 'Thing understood + ga + negative verb + past ending',
      explanation:
        'With wakaru, Japanese marks the thing understood with ga, not o, so ga must follow nihongo. Wakarimasen gives the polite negative, “do not understand,” and deshita makes it past: “did not understand.” The speaker is clear from context and can be omitted.',
    },
    {
      id: 'photo',
      title: 'A photo here',
      icon: '📷',
      prompt: 'May I take a picture here?',
      pieces: [
        { id: 'koko', jp: 'ここ', romaji: 'koko', en: 'here' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'place-of-action marker' },
        { id: 'shashin', jp: 'しゃしん', romaji: 'shashin', en: 'picture / photograph' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'totte', jp: 'とって', romaji: 'totte', en: 'take (te-form)' },
        { id: 'mo', jp: 'も', romaji: 'mo', en: 'even if / also' },
        { id: 'ii', jp: 'いい', romaji: 'ii', en: 'good / okay' },
        { id: 'desu', jp: 'です', romaji: 'desu', en: 'is / polite copula' },
        { id: 'ka', jp: 'か', romaji: 'ka', en: 'question marker' },
      ],
      scrambled: ['ka', 'shashin', 'mo', 'koko', 'ii', 'o', 'desu', 'de', 'totte'],
      answer: ['koko', 'de', 'shashin', 'o', 'totte', 'mo', 'ii', 'desu', 'ka'],
      pattern: 'Place/de + object/o + te-form + mo ii desu ka',
      explanation:
        'De follows koko to mark where the action happens, and o follows shashin to mark what is taken. Totte is the te-form of toru. The sequence mo ii desu ka literally asks “is it okay even if …?” Together, te-form + mo ii desu ka is the standard way to ask permission.',
    },
    {
      id: 'hotel',
      title: 'Hotel location',
      icon: '🏨',
      prompt: 'The hotel is near the station.',
      pieces: [
        { id: 'hoteru', jp: 'ホテル', romaji: 'hoteru', en: 'hotel' },
        { id: 'wa', jp: 'は', romaji: 'wa', en: 'topic marker' },
        { id: 'eki', jp: 'えき', romaji: 'eki', en: 'station' },
        { id: 'no', jp: 'の', romaji: 'no', en: 'of / linking particle' },
        { id: 'chikaku', jp: 'ちかく', romaji: 'chikaku', en: 'nearby / vicinity' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'location marker' },
        { id: 'arimasu', jp: 'あります', romaji: 'arimasu', en: 'exists / is (inanimate)' },
      ],
      scrambled: ['ni', 'arimasu', 'no', 'hoteru', 'chikaku', 'wa', 'eki'],
      answer: ['hoteru', 'wa', 'eki', 'no', 'chikaku', 'ni', 'arimasu'],
      pattern: 'Topic/wa + reference/no + location/ni + arimasu',
      explanation:
        'Wa follows hoteru to mark the hotel as the topic. No links eki to chikaku, forming “the station’s vicinity,” and ni marks that vicinity as the hotel’s location. Arimasu is used for the existence or location of an inanimate thing; a person or animal would use imasu.',
    },
    {
      id: 'rainy-taxi',
      title: 'Rainy taxi',
      icon: '☔',
      prompt: 'Because it is raining, I will go by taxi.',
      pieces: [
        { id: 'ame', jp: 'あめ', romaji: 'ame', en: 'rain' },
        { id: 'ga', jp: 'が', romaji: 'ga', en: 'subject marker' },
        { id: 'futte', jp: 'ふって', romaji: 'futte', en: 'falling (te-form)' },
        { id: 'imasu', jp: 'います', romaji: 'imasu', en: 'is happening / ongoing' },
        { id: 'kara', jp: 'から', romaji: 'kara', en: 'because' },
        { id: 'takushii', jp: 'タクシー', romaji: 'takushii', en: 'taxi' },
        { id: 'de', jp: 'で', romaji: 'de', en: 'by / means marker' },
        { id: 'ikimasu', jp: 'いきます', romaji: 'ikimasu', en: 'go / will go' },
      ],
      scrambled: ['takushii', 'kara', 'ga', 'ikimasu', 'futte', 'de', 'ame', 'imasu'],
      answer: ['ame', 'ga', 'futte', 'imasu', 'kara', 'takushii', 'de', 'ikimasu'],
      pattern: 'Reason + kara + means/de + action',
      explanation:
        'Ga follows ame because rain is the subject of futte imasu, “is falling.” Kara comes after that complete reason and means “because.” In the result, de follows takushii to mark the means of travel, and ikimasu supplies the final action.',
    },
    {
      id: 'souvenir',
      title: 'Family souvenir',
      icon: '🎁',
      prompt: 'I want to buy a small souvenir for my family.',
      pieces: [
        { id: 'kazoku', jp: 'かぞく', romaji: 'kazoku', en: 'family' },
        { id: 'ni', jp: 'に', romaji: 'ni', en: 'for / recipient marker' },
        { id: 'chiisai', jp: 'ちいさい', romaji: 'chiisai', en: 'small' },
        { id: 'omiyage', jp: 'おみやげ', romaji: 'omiyage', en: 'souvenir' },
        { id: 'o', jp: 'を', romaji: 'o', en: 'direct-object marker' },
        { id: 'kaitai', jp: 'かいたい', romaji: 'kaitai', en: 'want to buy' },
        { id: 'desu', jp: 'です', romaji: 'desu', en: 'polite ending' },
      ],
      scrambled: ['desu', 'omiyage', 'ni', 'kaitai', 'kazoku', 'o', 'chiisai'],
      answer: ['kazoku', 'ni', 'chiisai', 'omiyage', 'o', 'kaitai', 'desu'],
      pattern: 'Recipient/ni + adjective + object/o + desire + desu',
      explanation:
        'Ni follows kazoku to mark the family as the intended recipient. The i-adjective chiisai goes directly before omiyage, the noun it describes, and o follows that noun to mark it as the object. Kaitai means “want to buy,” and desu makes the statement polite.',
    },
  ],
}

export default puzzles
