// Short dialogue stories, in two kinds. The first six are everyday interactions
// — asking the way, ordering without meat, a hotel desk, a till, a ticket
// window, a fitting room — and each ends with a `takeaway` naming the one
// pattern that carried it. The rest are built around a turn — a pun, a
// reversal, a literal reading — and each has a `catch` instead. A story needs
// one or the other, never both; without either, no panel is rendered.
//
// Each line is { speaker?, jp, romaji, en, parts }. A line without a speaker is
// narration. `jp` is what speech synthesis reads aloud, so it holds only the
// sentence — the speaker label lives outside it. `catch` explains the turn in
// English and stays hidden until the reader asks for it.
//
// `parts` is the grammar breakdown, shown beside the translation: one entry per
// chunk of the sentence, in order, each `{ jp, romaji, en, role }` where `en` is
// what the chunk means ("—" when it carries no meaning of its own) and `role` is
// the job it does in the sentence. The chunks must concatenate back into `jp`
// exactly, ignoring punctuation — that is what makes the breakdown checkable.
//
// Grammar is kept to what the course teaches: -masu forms, plain particles,
// no keigo beyond the set phrases from Chapter 6.
export default {
  id: "stories",
  title: "Short Stories",
  intro:
    "Thirteen very short pieces, almost all dialogue: six everyday interactions you can expect to have, then seven stories with a sting in the tail. Tap any sentence for its translation and a word-by-word breakdown. Play a line, or let the whole story run.",
  stories: [
    {
      id: "michi",
      title: "Asking the Way",
      jpTitle: "道を聞きます",
      icon: "🗺️",
      blurb: "A traveller five minutes from the station, and a stranger with time.",
      cast: "A traveller · a passer-by",
      lines: [
        {
          jp: "女の人は、地図を見ています。",
          romaji: "Onna no hito wa, chizu o mite imasu.",
          en: "A woman is looking at a map.",
          parts: [
            { jp: "女の人", romaji: "onna no hito", en: "woman", role: "literally \"female person\"" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker: this is who the sentence is about" },
            { jp: "地図", romaji: "chizu", en: "map", role: "the object" },
            { jp: "を", romaji: "o", en: "—", role: "object marker: the thing being looked at" },
            { jp: "見ています", romaji: "mite imasu", en: "is looking at", role: "見る (to look) plus ています, an action in progress" },
          ],
        },
        {
          speaker: "Traveller",
          jp: "すみません、ちょっといいですか。",
          romaji: "Sumimasen, chotto ii desu ka.",
          en: "Excuse me, do you have a moment?",
          parts: [
            { jp: "すみません", romaji: "sumimasen", en: "excuse me", role: "the all-purpose opener for stopping a stranger" },
            { jp: "ちょっと", romaji: "chotto", en: "a little", role: "softens the request to a small favour" },
            { jp: "いい", romaji: "ii", en: "all right", role: "adjective: good, fine" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus the question marker" },
          ],
        },
        {
          speaker: "Passer-by",
          jp: "はい、どうぞ。",
          romaji: "Hai, douzo.",
          en: "Yes, go ahead.",
          parts: [
            { jp: "はい", romaji: "hai", en: "yes", role: "agreement — here, permission to continue" },
            { jp: "どうぞ", romaji: "douzo", en: "go ahead", role: "invites the other person to proceed" },
          ],
        },
        {
          speaker: "Traveller",
          jp: "京都駅へ行きたいです。",
          romaji: "Kyoto-eki e ikitai desu.",
          en: "I want to go to Kyoto Station.",
          parts: [
            { jp: "京都駅", romaji: "Kyoto-eki", en: "Kyoto Station", role: "a place name plus 駅, the station suffix" },
            { jp: "へ", romaji: "e", en: "to", role: "marks the direction travelled; written へ, pronounced e" },
            { jp: "行きたいです", romaji: "ikitai desu", en: "want to go", role: "行く (to go) in the -tai form: what you want to do" },
          ],
        },
        {
          speaker: "Traveller",
          jp: "歩いて行けますか。",
          romaji: "Aruite ikemasu ka.",
          en: "Can I walk there?",
          parts: [
            { jp: "歩いて", romaji: "aruite", en: "on foot", role: "te-form of 歩く (to walk), describing how you go" },
            { jp: "行けます", romaji: "ikemasu", en: "can go", role: "potential form of 行く, polite" },
            { jp: "か", romaji: "ka", en: "—", role: "question marker" },
          ],
        },
        {
          speaker: "Passer-by",
          jp: "はい、近いです。五分ぐらいです。",
          romaji: "Hai, chikai desu. Gofun gurai desu.",
          en: "Yes, it's close. About five minutes.",
          parts: [
            { jp: "はい", romaji: "hai", en: "yes", role: "answers the yes-or-no question" },
            { jp: "近い", romaji: "chikai", en: "near", role: "an i-adjective" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
            { jp: "五分", romaji: "gofun", en: "five minutes", role: "number plus 分, the counter for minutes" },
            { jp: "ぐらい", romaji: "gurai", en: "about", role: "makes the number approximate" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
          ],
        },
        {
          speaker: "Passer-by",
          jp: "この道をまっすぐ行ってください。",
          romaji: "Kono michi o massugu itte kudasai.",
          en: "Go straight along this road.",
          parts: [
            { jp: "この", romaji: "kono", en: "this", role: "points at something near the speaker" },
            { jp: "道", romaji: "michi", en: "road", role: "the noun" },
            { jp: "を", romaji: "o", en: "—", role: "marks the route travelled along, not an object" },
            { jp: "まっすぐ", romaji: "massugu", en: "straight", role: "describes how you go" },
            { jp: "行って", romaji: "itte", en: "go", role: "te-form of 行く — irregular, so worth memorising" },
            { jp: "ください", romaji: "kudasai", en: "please", role: "te-form plus ください: the standard polite request" },
          ],
        },
        {
          speaker: "Passer-by",
          jp: "二つ目の信号を右に曲がってください。",
          romaji: "Futatsume no shingou o migi ni magatte kudasai.",
          en: "Turn right at the second traffic light.",
          parts: [
            { jp: "二つ目", romaji: "futatsume", en: "the second", role: "counter ふたつ plus 目, which makes it an ordinal" },
            { jp: "の", romaji: "no", en: "—", role: "links the two nouns" },
            { jp: "信号", romaji: "shingou", en: "traffic light", role: "the noun" },
            { jp: "を", romaji: "o", en: "—", role: "marks the point you turn at, treated as part of the route" },
            { jp: "右", romaji: "migi", en: "right", role: "the direction" },
            { jp: "に", romaji: "ni", en: "to", role: "marks the direction you end up facing" },
            { jp: "曲がって", romaji: "magatte", en: "turn", role: "te-form of 曲がる (to turn)" },
            { jp: "ください", romaji: "kudasai", en: "please", role: "makes it a polite request" },
          ],
        },
        {
          speaker: "Traveller",
          jp: "二つ目の信号を右ですね。",
          romaji: "Futatsume no shingou o migi desu ne.",
          en: "Right at the second light, yes?",
          parts: [
            { jp: "二つ目", romaji: "futatsume", en: "the second", role: "repeated back to confirm it" },
            { jp: "の", romaji: "no", en: "—", role: "links the two nouns" },
            { jp: "信号", romaji: "shingou", en: "traffic light", role: "the noun" },
            { jp: "を", romaji: "o", en: "—", role: "carried over from the instruction, verb and all left unsaid" },
            { jp: "右", romaji: "migi", en: "right", role: "the word that matters, said back to check it" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
            { jp: "ね", romaji: "ne", en: "isn't it", role: "asks for confirmation of what you just said" },
          ],
        },
        {
          speaker: "Passer-by",
          jp: "はい、そうです。気をつけて。",
          romaji: "Hai, sou desu. Ki o tsukete.",
          en: "Yes, that's right. Take care.",
          parts: [
            { jp: "はい", romaji: "hai", en: "yes", role: "confirms it" },
            { jp: "そう", romaji: "sou", en: "so", role: "that way, like that" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
            { jp: "気", romaji: "ki", en: "attention", role: "the noun in a fixed expression" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "つけて", romaji: "tsukete", en: "attach", role: "te-form of つける; 気をつけて means \"be careful\"" },
          ],
        },
        {
          speaker: "Traveller",
          jp: "ありがとうございます。",
          romaji: "Arigatou gozaimasu.",
          en: "Thank you.",
          parts: [
            { jp: "ありがとうございます", romaji: "arigatou gozaimasu", en: "thank you", role: "the full polite form, right for a stranger who helped" },
          ],
        },
      ],
      takeaway:
        "The traveller produces four sentences, all of them from the phrase deck: sumimasen to open, *… e ikitai desu* for the goal, *aruite ikemasu ka* to check, and then the one move that actually rescues the exchange — repeating the key word back with **ね**. You do not need to catch the whole answer, only *migi*.",
    },
    {
      id: "ramen",
      title: "Vegetarian Ramen",
      jpTitle: "ベジタリアンのラーメン",
      icon: "🍜",
      blurb: "Ordering without meat, and the follow-up question that matters more.",
      cast: "A traveller · a ramen cook",
      lines: [
        {
          jp: "小さなラーメン屋に入りました。",
          romaji: "Chiisana raamen-ya ni hairimashita.",
          en: "He went into a small ramen shop.",
          parts: [
            { jp: "小さな", romaji: "chiisana", en: "small", role: "describes the noun that follows" },
            { jp: "ラーメン屋", romaji: "raamen-ya", en: "ramen shop", role: "屋 turns anything into the shop that sells it" },
            { jp: "に", romaji: "ni", en: "into", role: "marks where you end up" },
            { jp: "入りました", romaji: "hairimashita", en: "entered", role: "入る (to enter), polite past" },
          ],
        },
        {
          speaker: "Cook",
          jp: "いらっしゃいませ。何名様ですか。",
          romaji: "Irasshaimase. Nanmei-sama desu ka.",
          en: "Welcome! How many people?",
          parts: [
            { jp: "いらっしゃいませ", romaji: "irasshaimase", en: "welcome", role: "called out to every customer; no reply needed" },
            { jp: "何名様", romaji: "nanmei-sama", en: "how many people", role: "the honorific version of 何人, used to customers" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus question marker" },
          ],
        },
        {
          speaker: "Traveller",
          jp: "一人です。",
          romaji: "Hitori desu.",
          en: "Just me.",
          parts: [
            { jp: "一人", romaji: "hitori", en: "one person", role: "the counter 人 is irregular here: hitori, futari, sannin" },
            { jp: "です", romaji: "desu", en: "is", role: "a complete answer on its own" },
          ],
        },
        {
          speaker: "Cook",
          jp: "こちらへどうぞ。",
          romaji: "Kochira e douzo.",
          en: "This way, please.",
          parts: [
            { jp: "こちら", romaji: "kochira", en: "this way", role: "the polite form of ここ" },
            { jp: "へ", romaji: "e", en: "to", role: "marks the direction" },
            { jp: "どうぞ", romaji: "douzo", en: "please", role: "invites you to go ahead" },
          ],
        },
        {
          speaker: "Traveller",
          jp: "すみません、私はベジタリアンです。",
          romaji: "Sumimasen, watashi wa bejitarian desu.",
          en: "Excuse me — I'm a vegetarian.",
          parts: [
            { jp: "すみません", romaji: "sumimasen", en: "excuse me", role: "opens the request politely" },
            { jp: "私", romaji: "watashi", en: "I", role: "kept here because the topic is genuinely new" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker: as for me" },
            { jp: "ベジタリアン", romaji: "bejitarian", en: "vegetarian", role: "a borrowed word, so it is written in katakana" },
            { jp: "です", romaji: "desu", en: "am", role: "polite ending" },
          ],
        },
        {
          speaker: "Traveller",
          jp: "肉が入っていないラーメンはありますか。",
          romaji: "Niku ga haitte inai raamen wa arimasu ka.",
          en: "Do you have a ramen with no meat in it?",
          parts: [
            { jp: "肉", romaji: "niku", en: "meat", role: "the noun" },
            { jp: "が", romaji: "ga", en: "—", role: "marks what is (not) contained" },
            { jp: "入っていない", romaji: "haitte inai", en: "is not contained", role: "the plain negative of 入っています, describing the noun that follows" },
            { jp: "ラーメン", romaji: "raamen", en: "ramen", role: "the noun being described" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker" },
            { jp: "あります", romaji: "arimasu", en: "there is", role: "existence of a thing" },
            { jp: "か", romaji: "ka", en: "—", role: "question marker" },
          ],
        },
        {
          speaker: "Cook",
          jp: "野菜ラーメンがあります。でも、出汁は魚です。",
          romaji: "Yasai raamen ga arimasu. Demo, dashi wa sakana desu.",
          en: "There's a vegetable ramen. But the stock is fish.",
          parts: [
            { jp: "野菜ラーメン", romaji: "yasai raamen", en: "vegetable ramen", role: "two nouns stacked, no particle needed" },
            { jp: "が", romaji: "ga", en: "—", role: "marks the thing that exists — new information" },
            { jp: "あります", romaji: "arimasu", en: "there is", role: "existence of a thing" },
            { jp: "でも", romaji: "demo", en: "but", role: "starts the second sentence; it never sits mid-sentence" },
            { jp: "出汁", romaji: "dashi", en: "stock", role: "the broth base in almost everything savoury" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker: as for the stock" },
            { jp: "魚", romaji: "sakana", en: "fish", role: "the answer, and the problem" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
          ],
        },
        {
          speaker: "Traveller",
          jp: "魚も食べません。野菜だけでお願いします。",
          romaji: "Sakana mo tabemasen. Yasai dake de onegai shimasu.",
          en: "I don't eat fish either. Vegetables only, please.",
          parts: [
            { jp: "魚", romaji: "sakana", en: "fish", role: "the noun" },
            { jp: "も", romaji: "mo", en: "also", role: "adds fish to what was already ruled out; it replaces を" },
            { jp: "食べません", romaji: "tabemasen", en: "do not eat", role: "食べる (to eat), polite negative" },
            { jp: "野菜", romaji: "yasai", en: "vegetables", role: "the noun" },
            { jp: "だけ", romaji: "dake", en: "only", role: "restricts it to that and nothing else" },
            { jp: "で", romaji: "de", en: "—", role: "sets the terms the request is made under" },
            { jp: "お願いします", romaji: "onegai shimasu", en: "please", role: "asks for it as a favour" },
          ],
        },
        {
          speaker: "Cook",
          jp: "わかりました。少々お待ちください。",
          romaji: "Wakarimashita. Shoushou omachi kudasai.",
          en: "Understood. One moment, please.",
          parts: [
            { jp: "わかりました", romaji: "wakarimashita", en: "understood", role: "polite past of わかる — Japanese uses the past here, not the present" },
            { jp: "少々", romaji: "shoushou", en: "a little", role: "the formal version of ちょっと" },
            { jp: "お待ちください", romaji: "omachi kudasai", en: "please wait", role: "the polite set phrase staff use to customers" },
          ],
        },
        {
          jp: "しばらくして、ラーメンが来ました。",
          romaji: "Shibaraku shite, raamen ga kimashita.",
          en: "After a while, the ramen arrived.",
          parts: [
            { jp: "しばらく", romaji: "shibaraku", en: "for a while", role: "an unspecified short stretch of time" },
            { jp: "して", romaji: "shite", en: "having passed", role: "te-form of する, joining this to what follows" },
            { jp: "ラーメン", romaji: "raamen", en: "ramen", role: "the noun" },
            { jp: "が", romaji: "ga", en: "—", role: "marks the thing that arrives" },
            { jp: "来ました", romaji: "kimashita", en: "came", role: "来る (to come), polite past" },
          ],
        },
        {
          speaker: "Traveller",
          jp: "いただきます。",
          romaji: "Itadakimasu.",
          en: "Thank you for the food.",
          parts: [
            { jp: "いただきます", romaji: "itadakimasu", en: "I gratefully receive", role: "said before eating, to the food and everyone behind it" },
          ],
        },
        {
          speaker: "Traveller",
          jp: "おいしいです。ごちそうさまでした。",
          romaji: "Oishii desu. Gochisousama deshita.",
          en: "It's delicious. Thank you for the meal.",
          parts: [
            { jp: "おいしい", romaji: "oishii", en: "delicious", role: "an i-adjective" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
            { jp: "ごちそうさまでした", romaji: "gochisousama deshita", en: "thank you for the meal", role: "said after eating, and as you leave" },
          ],
        },
      ],
      takeaway:
        "*Bejitarian desu* is not enough on its own in Japan, and this cook is being helpful by saying so: **dashi wa sakana desu** — the stock is fish. The two sentences that actually settle it are *sakana mo tabemasen* and *yasai dake de onegai shimasu*, where **だけ** (only) does the work.",
    },
    {
      id: "furonto",
      title: "At the Hotel Desk",
      jpTitle: "ホテルのフロント",
      icon: "🛏️",
      blurb: "Checking in and asking the four questions every guest needs answered.",
      cast: "A guest · the front desk",
      lines: [
        {
          speaker: "Guest",
          jp: "チェックインお願いします。",
          romaji: "Chekku-in onegai shimasu.",
          en: "I'd like to check in.",
          parts: [
            { jp: "チェックイン", romaji: "chekku-in", en: "check-in", role: "a borrowed noun, in katakana" },
            { jp: "お願いします", romaji: "onegai shimasu", en: "please", role: "noun plus お願いします handles most front-desk business" },
          ],
        },
        {
          speaker: "Desk",
          jp: "はい、お名前をお願いします。",
          romaji: "Hai, o-namae o onegai shimasu.",
          en: "Certainly — your name, please.",
          parts: [
            { jp: "はい", romaji: "hai", en: "yes", role: "acknowledges the request" },
            { jp: "お名前", romaji: "o-namae", en: "name", role: "the honorific お- because it is your name, not theirs" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "お願いします", romaji: "onegai shimasu", en: "please", role: "asks you for it politely" },
          ],
        },
        {
          speaker: "Guest",
          jp: "スミスという名前です。二泊です。",
          romaji: "Sumisu to iu namae desu. Nihaku desu.",
          en: "The name is Smith. Two nights.",
          parts: [
            { jp: "スミス", romaji: "Sumisu", en: "Smith", role: "a foreign name, so katakana" },
            { jp: "という", romaji: "to iu", en: "called", role: "introduces a name: \"a name called Smith\"" },
            { jp: "名前", romaji: "namae", en: "name", role: "the noun being described" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
            { jp: "二泊", romaji: "nihaku", en: "two nights", role: "泊 counts nights of a stay; three is sanpaku" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
          ],
        },
        {
          speaker: "Desk",
          jp: "かしこまりました。禁煙の部屋です。",
          romaji: "Kashikomarimashita. Kin'en no heya desu.",
          en: "Certainly. It's a non-smoking room.",
          parts: [
            { jp: "かしこまりました", romaji: "kashikomarimashita", en: "certainly", role: "a very polite \"understood\", used to customers" },
            { jp: "禁煙", romaji: "kin'en", en: "non-smoking", role: "literally \"smoking prohibited\"" },
            { jp: "の", romaji: "no", en: "—", role: "links the two nouns" },
            { jp: "部屋", romaji: "heya", en: "room", role: "the noun" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
          ],
        },
        {
          speaker: "Guest",
          jp: "朝食は何時からですか。",
          romaji: "Choushoku wa nanji kara desu ka.",
          en: "What time does breakfast start?",
          parts: [
            { jp: "朝食", romaji: "choushoku", en: "breakfast", role: "the noun" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker: as for breakfast" },
            { jp: "何時", romaji: "nanji", en: "what time", role: "literally \"what hour\"" },
            { jp: "から", romaji: "kara", en: "from", role: "makes this the starting-time question" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus question marker" },
          ],
        },
        {
          speaker: "Desk",
          jp: "七時から十時までです。二階のレストランです。",
          romaji: "Shichiji kara juuji made desu. Nikai no resutoran desu.",
          en: "From seven until ten. In the restaurant on the second floor.",
          parts: [
            { jp: "七時", romaji: "shichiji", en: "seven o'clock", role: "number plus 時, the hour counter" },
            { jp: "から", romaji: "kara", en: "from", role: "the start of the range" },
            { jp: "十時", romaji: "juuji", en: "ten o'clock", role: "number plus 時" },
            { jp: "まで", romaji: "made", en: "until", role: "the end of the range; から and まで come as a pair" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
            { jp: "二階", romaji: "nikai", en: "second floor", role: "階 counts floors of a building" },
            { jp: "の", romaji: "no", en: "—", role: "links the two nouns" },
            { jp: "レストラン", romaji: "resutoran", en: "restaurant", role: "a borrowed word" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
          ],
        },
        {
          speaker: "Guest",
          jp: "Wi-Fiのパスワードは何ですか。",
          romaji: "Waifai no pasuwaado wa nan desu ka.",
          en: "What's the Wi-Fi password?",
          parts: [
            { jp: "Wi-Fi", romaji: "waifai", en: "Wi-Fi", role: "left in Latin letters, as signs and menus do" },
            { jp: "の", romaji: "no", en: "of", role: "links two nouns: the password of the Wi-Fi" },
            { jp: "パスワード", romaji: "pasuwaado", en: "password", role: "a borrowed word" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker" },
            { jp: "何", romaji: "nan", en: "what", role: "なに becomes なん before です" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
            { jp: "か", romaji: "ka", en: "—", role: "question marker" },
          ],
        },
        {
          speaker: "Desk",
          jp: "こちらに書いてあります。",
          romaji: "Kochira ni kaite arimasu.",
          en: "It's written here.",
          parts: [
            { jp: "こちら", romaji: "kochira", en: "here", role: "the polite ここ; a card is being handed over" },
            { jp: "に", romaji: "ni", en: "on", role: "marks where the writing sits" },
            { jp: "書いてあります", romaji: "kaite arimasu", en: "is written", role: "書く plus てあります: a state someone left in place" },
          ],
        },
        {
          speaker: "Guest",
          jp: "荷物を預かってもらえますか。",
          romaji: "Nimotsu o azukatte moraemasu ka.",
          en: "Could you hold my luggage?",
          parts: [
            { jp: "荷物", romaji: "nimotsu", en: "luggage", role: "the noun" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "預かって", romaji: "azukatte", en: "hold, keep", role: "te-form of 預かる, to look after something for someone" },
            { jp: "もらえますか", romaji: "moraemasu ka", en: "could you", role: "te-form plus もらえますか asks a favour — softer than ください" },
          ],
        },
        {
          speaker: "Desk",
          jp: "はい、大丈夫です。チェックアウトは十一時までです。",
          romaji: "Hai, daijoubu desu. Chekku-auto wa juuichiji made desu.",
          en: "Yes, that's fine. Check-out is by eleven.",
          parts: [
            { jp: "はい", romaji: "hai", en: "yes", role: "agreement" },
            { jp: "大丈夫", romaji: "daijoubu", en: "fine", role: "here it accepts, rather than declines" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
            { jp: "チェックアウト", romaji: "chekku-auto", en: "check-out", role: "a borrowed noun" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker" },
            { jp: "十一時", romaji: "juuichiji", en: "eleven o'clock", role: "number plus 時" },
            { jp: "まで", romaji: "made", en: "until", role: "makes it a deadline" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
          ],
        },
        {
          speaker: "Guest",
          jp: "ありがとうございます。",
          romaji: "Arigatou gozaimasu.",
          en: "Thank you.",
          parts: [
            { jp: "ありがとうございます", romaji: "arigatou gozaimasu", en: "thank you", role: "the full polite form" },
          ],
        },
      ],
      takeaway:
        "Every question here is a noun plus a set ending, and the answers all turn on the same pair: **から** (from) and **まで** (until). Ask *nanji kara* for an opening time and *nanji made* for a deadline, and you can read any Japanese timetable out loud.",
    },
    {
      id: "konbini",
      title: "At the Convenience Store",
      jpTitle: "コンビニのレジ",
      icon: "🏪",
      blurb: "Four questions at the till, all of them yes-or-no.",
      cast: "A customer · a shop assistant",
      lines: [
        {
          jp: "お弁当とお茶を買います。",
          romaji: "O-bentou to ocha o kaimasu.",
          en: "He buys a lunch box and some tea.",
          parts: [
            { jp: "お弁当", romaji: "o-bentou", en: "lunch box", role: "the お- has become part of the word" },
            { jp: "と", romaji: "to", en: "and", role: "joins nouns into a complete list" },
            { jp: "お茶", romaji: "ocha", en: "tea", role: "another word that keeps its polite お-" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "買います", romaji: "kaimasu", en: "buys", role: "買う (to buy), polite present" },
          ],
        },
        {
          speaker: "Assistant",
          jp: "いらっしゃいませ。温めますか。",
          romaji: "Irasshaimase. Atatamemasu ka.",
          en: "Welcome! Shall I heat it up?",
          parts: [
            { jp: "いらっしゃいませ", romaji: "irasshaimase", en: "welcome", role: "no reply needed — a nod is plenty" },
            { jp: "温めます", romaji: "atatamemasu", en: "heat up", role: "温める (to warm something), polite" },
            { jp: "か", romaji: "ka", en: "—", role: "question marker" },
          ],
        },
        {
          speaker: "Customer",
          jp: "はい、お願いします。",
          romaji: "Hai, onegai shimasu.",
          en: "Yes, please.",
          parts: [
            { jp: "はい", romaji: "hai", en: "yes", role: "accepts the offer" },
            { jp: "お願いします", romaji: "onegai shimasu", en: "please", role: "the standard way to accept an offer of service" },
          ],
        },
        {
          speaker: "Assistant",
          jp: "お箸はおつけしますか。",
          romaji: "O-hashi wa otsuke shimasu ka.",
          en: "Would you like chopsticks?",
          parts: [
            { jp: "お箸", romaji: "o-hashi", en: "chopsticks", role: "the polite お- again" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker: as for chopsticks" },
            { jp: "おつけします", romaji: "otsuke shimasu", en: "shall I attach", role: "a humble form of つける — staff language for adding something" },
            { jp: "か", romaji: "ka", en: "—", role: "question marker" },
          ],
        },
        {
          speaker: "Customer",
          jp: "はい、お願いします。",
          romaji: "Hai, onegai shimasu.",
          en: "Yes, please.",
          parts: [
            { jp: "はい", romaji: "hai", en: "yes", role: "the same answer works for every offer" },
            { jp: "お願いします", romaji: "onegai shimasu", en: "please", role: "accepts it" },
          ],
        },
        {
          speaker: "Assistant",
          jp: "袋はご利用ですか。",
          romaji: "Fukuro wa go-riyou desu ka.",
          en: "Do you need a bag?",
          parts: [
            { jp: "袋", romaji: "fukuro", en: "bag", role: "the noun" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker" },
            { jp: "ご利用", romaji: "go-riyou", en: "use", role: "利用 (use) with the honorific ご-, because it is your use of it" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus question marker" },
          ],
        },
        {
          speaker: "Customer",
          jp: "袋は大丈夫です。",
          romaji: "Fukuro wa daijoubu desu.",
          en: "I don't need a bag.",
          parts: [
            { jp: "袋", romaji: "fukuro", en: "bag", role: "repeated back as the topic" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker" },
            { jp: "大丈夫", romaji: "daijoubu", en: "fine", role: "here it declines — the polite no" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
          ],
        },
        {
          speaker: "Assistant",
          jp: "六百五十円になります。",
          romaji: "Roppyaku gojuu en ni narimasu.",
          en: "That comes to ¥650.",
          parts: [
            { jp: "六百五十円", romaji: "roppyaku gojuu en", en: "650 yen", role: "六百 becomes roppyaku, not rokuhyaku" },
            { jp: "に", romaji: "ni", en: "to", role: "marks the result" },
            { jp: "なります", romaji: "narimasu", en: "becomes", role: "a soft retail \"it comes to\"; the total is also on the display" },
          ],
        },
        {
          speaker: "Customer",
          jp: "カードで払えますか。",
          romaji: "Kaado de haraemasu ka.",
          en: "Can I pay by card?",
          parts: [
            { jp: "カード", romaji: "kaado", en: "card", role: "a borrowed word" },
            { jp: "で", romaji: "de", en: "by", role: "marks the means of payment" },
            { jp: "払えます", romaji: "haraemasu", en: "can pay", role: "potential form of 払う (to pay)" },
            { jp: "か", romaji: "ka", en: "—", role: "question marker" },
          ],
        },
        {
          speaker: "Assistant",
          jp: "はい、こちらにお願いします。",
          romaji: "Hai, kochira ni onegai shimasu.",
          en: "Yes — here, please.",
          parts: [
            { jp: "はい", romaji: "hai", en: "yes", role: "confirms it" },
            { jp: "こちら", romaji: "kochira", en: "here", role: "the card reader is being indicated" },
            { jp: "に", romaji: "ni", en: "—", role: "marks where the card goes" },
            { jp: "お願いします", romaji: "onegai shimasu", en: "please", role: "turns a gesture into a polite instruction" },
          ],
        },
        {
          speaker: "Assistant",
          jp: "ありがとうございました。",
          romaji: "Arigatou gozaimashita.",
          en: "Thank you very much.",
          parts: [
            { jp: "ありがとうございました", romaji: "arigatou gozaimashita", en: "thank you", role: "the past form thanks you for a completed transaction" },
          ],
        },
        {
          speaker: "Customer",
          jp: "どうも。",
          romaji: "Doumo.",
          en: "Thanks.",
          parts: [
            { jp: "どうも", romaji: "doumo", en: "thanks", role: "a compact acknowledgement on the way out" },
          ],
        },
      ],
      takeaway:
        "The till asks four yes-or-no questions and you can survive all of them with two answers: *onegai shimasu* to accept and **大丈夫です** to decline. Notice the customer repeating the noun as a topic — *fukuro wa daijoubu desu* — which makes the refusal unmistakable.",
    },
    {
      id: "kippu",
      title: "Buying a Ticket",
      jpTitle: "切符を買います",
      icon: "🚆",
      blurb: "Price, transfer, platform, time — in that order.",
      cast: "A traveller · a station attendant",
      lines: [
        {
          speaker: "Traveller",
          jp: "すみません、切符はどこで買えますか。",
          romaji: "Sumimasen, kippu wa doko de kaemasu ka.",
          en: "Excuse me, where can I buy a ticket?",
          parts: [
            { jp: "すみません", romaji: "sumimasen", en: "excuse me", role: "gets attention" },
            { jp: "切符", romaji: "kippu", en: "ticket", role: "the noun" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker" },
            { jp: "どこ", romaji: "doko", en: "where", role: "the question word" },
            { jp: "で", romaji: "de", en: "at", role: "marks where an action happens — not に, because buying is an action" },
            { jp: "買えます", romaji: "kaemasu", en: "can buy", role: "potential form of 買う" },
            { jp: "か", romaji: "ka", en: "—", role: "question marker" },
          ],
        },
        {
          speaker: "Attendant",
          jp: "あの機械で買えます。",
          romaji: "Ano kikai de kaemasu.",
          en: "You can buy one at that machine.",
          parts: [
            { jp: "あの", romaji: "ano", en: "that … over there", role: "away from both of you" },
            { jp: "機械", romaji: "kikai", en: "machine", role: "the noun" },
            { jp: "で", romaji: "de", en: "at", role: "where the buying happens" },
            { jp: "買えます", romaji: "kaemasu", en: "can buy", role: "the same potential form, answering in kind" },
          ],
        },
        {
          speaker: "Traveller",
          jp: "大阪までいくらですか。",
          romaji: "Osaka made ikura desu ka.",
          en: "How much is it to Osaka?",
          parts: [
            { jp: "大阪", romaji: "Osaka", en: "Osaka", role: "the destination" },
            { jp: "まで", romaji: "made", en: "as far as", role: "marks the end point" },
            { jp: "いくら", romaji: "ikura", en: "how much", role: "the question word for money" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus question marker" },
          ],
        },
        {
          speaker: "Attendant",
          jp: "五百七十円です。",
          romaji: "Gohyaku nanajuu en desu.",
          en: "It's ¥570.",
          parts: [
            { jp: "五百七十円", romaji: "gohyaku nanajuu en", en: "570 yen", role: "hundreds, then tens, then 円" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
          ],
        },
        {
          speaker: "Traveller",
          jp: "乗り換えは必要ですか。",
          romaji: "Norikae wa hitsuyou desu ka.",
          en: "Do I need to change trains?",
          parts: [
            { jp: "乗り換え", romaji: "norikae", en: "transfer", role: "a noun made from 乗り換える, to change trains" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker" },
            { jp: "必要", romaji: "hitsuyou", en: "necessary", role: "a na-adjective, used here with です" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus question marker" },
          ],
        },
        {
          speaker: "Attendant",
          jp: "はい、京都で乗り換えてください。",
          romaji: "Hai, Kyoto de norikaete kudasai.",
          en: "Yes — change at Kyoto.",
          parts: [
            { jp: "はい", romaji: "hai", en: "yes", role: "answers the yes-or-no question" },
            { jp: "京都", romaji: "Kyoto", en: "Kyoto", role: "the place" },
            { jp: "で", romaji: "de", en: "at", role: "where the changing happens" },
            { jp: "乗り換えて", romaji: "norikaete", en: "change", role: "te-form of 乗り換える" },
            { jp: "ください", romaji: "kudasai", en: "please", role: "makes it a polite instruction" },
          ],
        },
        {
          speaker: "Traveller",
          jp: "何番線ですか。",
          romaji: "Nanbansen desu ka.",
          en: "Which platform?",
          parts: [
            { jp: "何番線", romaji: "nanbansen", en: "which platform", role: "何 plus 番線, the counter for platform tracks" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus question marker" },
          ],
        },
        {
          speaker: "Attendant",
          jp: "三番線です。次の電車は二時十分です。",
          romaji: "Sanbansen desu. Tsugi no densha wa niji juppun desu.",
          en: "Platform three. The next train is at 2:10.",
          parts: [
            { jp: "三番線", romaji: "sanbansen", en: "platform three", role: "the answer, in the same counter" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
            { jp: "次", romaji: "tsugi", en: "next", role: "used as a noun" },
            { jp: "の", romaji: "no", en: "—", role: "links the two nouns" },
            { jp: "電車", romaji: "densha", en: "train", role: "the noun" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker" },
            { jp: "二時十分", romaji: "niji juppun", en: "2:10", role: "hour plus minutes; 十分 is juppun, with the p sound" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
          ],
        },
        {
          speaker: "Traveller",
          jp: "どのくらいかかりますか。",
          romaji: "Dono kurai kakarimasu ka.",
          en: "How long does it take?",
          parts: [
            { jp: "どのくらい", romaji: "dono kurai", en: "how much / how long", role: "asks about an amount without naming the unit" },
            { jp: "かかります", romaji: "kakarimasu", en: "takes", role: "かかる covers both time taken and money cost" },
            { jp: "か", romaji: "ka", en: "—", role: "question marker" },
          ],
        },
        {
          speaker: "Attendant",
          jp: "一時間ぐらいです。",
          romaji: "Ichijikan gurai desu.",
          en: "About an hour.",
          parts: [
            { jp: "一時間", romaji: "ichijikan", en: "one hour", role: "時間 counts a length of time; 時 alone is a clock time" },
            { jp: "ぐらい", romaji: "gurai", en: "about", role: "makes the number approximate" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
          ],
        },
        {
          speaker: "Traveller",
          jp: "わかりました。ありがとうございます。",
          romaji: "Wakarimashita. Arigatou gozaimasu.",
          en: "Got it. Thank you.",
          parts: [
            { jp: "わかりました", romaji: "wakarimashita", en: "understood", role: "the polite past — the understanding has already happened" },
            { jp: "ありがとうございます", romaji: "arigatou gozaimasu", en: "thank you", role: "the full polite form" },
          ],
        },
      ],
      takeaway:
        "One pattern carries the whole exchange: **まで** for the destination, **で** for where an action happens, and a counter question — *nanbansen* — that the answer simply fills in. Note *niji* (a clock time) against *ichijikan* (a length of time): 時 and 時間 are not interchangeable.",
    },
    {
      id: "shichaku",
      title: "Trying It On",
      jpTitle: "試着してもいいですか",
      icon: "👕",
      blurb: "A jacket, a size problem, and the word that stands in for a noun.",
      cast: "A shopper · a shop assistant",
      lines: [
        {
          jp: "店で青いジャケットを見ています。",
          romaji: "Mise de aoi jaketto o mite imasu.",
          en: "She's looking at a blue jacket in a shop.",
          parts: [
            { jp: "店", romaji: "mise", en: "shop", role: "the noun" },
            { jp: "で", romaji: "de", en: "in", role: "marks where the action happens" },
            { jp: "青い", romaji: "aoi", en: "blue", role: "an i-adjective, straight in front of the noun" },
            { jp: "ジャケット", romaji: "jaketto", en: "jacket", role: "a borrowed word" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "見ています", romaji: "mite imasu", en: "is looking at", role: "an action in progress" },
          ],
        },
        {
          speaker: "Assistant",
          jp: "いらっしゃいませ。どうぞ見てください。",
          romaji: "Irasshaimase. Douzo mite kudasai.",
          en: "Welcome. Please have a look.",
          parts: [
            { jp: "いらっしゃいませ", romaji: "irasshaimase", en: "welcome", role: "the shop greeting" },
            { jp: "どうぞ", romaji: "douzo", en: "please, go ahead", role: "invites you to proceed" },
            { jp: "見て", romaji: "mite", en: "look", role: "te-form of 見る" },
            { jp: "ください", romaji: "kudasai", en: "please", role: "a polite invitation rather than an order" },
          ],
        },
        {
          speaker: "Shopper",
          jp: "これはいくらですか。",
          romaji: "Kore wa ikura desu ka.",
          en: "How much is this?",
          parts: [
            { jp: "これ", romaji: "kore", en: "this one", role: "the thing near the speaker" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker" },
            { jp: "いくら", romaji: "ikura", en: "how much", role: "the price question word" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus question marker" },
          ],
        },
        {
          speaker: "Assistant",
          jp: "八千円です。",
          romaji: "Hassen en desu.",
          en: "¥8,000.",
          parts: [
            { jp: "八千円", romaji: "hassen en", en: "8,000 yen", role: "八千 becomes hassen, not hachisen" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
          ],
        },
        {
          speaker: "Shopper",
          jp: "試着してもいいですか。",
          romaji: "Shichaku shite mo ii desu ka.",
          en: "May I try it on?",
          parts: [
            { jp: "試着して", romaji: "shichaku shite", en: "trying on", role: "te-form of 試着する, to try on clothes" },
            { jp: "も", romaji: "mo", en: "even", role: "part of the fixed permission pattern てもいいですか" },
            { jp: "いい", romaji: "ii", en: "all right", role: "the adjective at the centre of the pattern" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
            { jp: "か", romaji: "ka", en: "—", role: "question marker" },
          ],
        },
        {
          speaker: "Assistant",
          jp: "はい、こちらへどうぞ。",
          romaji: "Hai, kochira e douzo.",
          en: "Of course — this way.",
          parts: [
            { jp: "はい", romaji: "hai", en: "yes", role: "grants permission" },
            { jp: "こちら", romaji: "kochira", en: "this way", role: "the polite ここ" },
            { jp: "へ", romaji: "e", en: "to", role: "marks the direction" },
            { jp: "どうぞ", romaji: "douzo", en: "please", role: "invites you to go ahead" },
          ],
        },
        {
          speaker: "Shopper",
          jp: "ちょっと小さいです。もっと大きいのはありますか。",
          romaji: "Chotto chiisai desu. Motto ookii no wa arimasu ka.",
          en: "It's a bit small. Do you have a bigger one?",
          parts: [
            { jp: "ちょっと", romaji: "chotto", en: "a bit", role: "softens the complaint" },
            { jp: "小さい", romaji: "chiisai", en: "small", role: "an i-adjective" },
            { jp: "です", romaji: "desu", en: "is", role: "polite ending" },
            { jp: "もっと", romaji: "motto", en: "more", role: "makes the adjective comparative" },
            { jp: "大きい", romaji: "ookii", en: "big", role: "an i-adjective" },
            { jp: "の", romaji: "no", en: "one", role: "stands in for the noun: \"a big one\"" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker" },
            { jp: "あります", romaji: "arimasu", en: "there is", role: "existence of a thing" },
            { jp: "か", romaji: "ka", en: "—", role: "question marker" },
          ],
        },
        {
          speaker: "Assistant",
          jp: "Lサイズがあります。他の色もありますよ。",
          romaji: "Eru saizu ga arimasu. Hoka no iro mo arimasu yo.",
          en: "We have a large. We have other colours too.",
          parts: [
            { jp: "Lサイズ", romaji: "eru saizu", en: "size L", role: "Latin letter plus a borrowed word, as clothing labels do" },
            { jp: "が", romaji: "ga", en: "—", role: "marks the thing that exists — new information" },
            { jp: "あります", romaji: "arimasu", en: "there is", role: "existence of a thing" },
            { jp: "他", romaji: "hoka", en: "other", role: "used as a noun" },
            { jp: "の", romaji: "no", en: "—", role: "links the two nouns" },
            { jp: "色", romaji: "iro", en: "colour", role: "the noun" },
            { jp: "も", romaji: "mo", en: "also", role: "adds to what was already offered; it replaces が" },
            { jp: "あります", romaji: "arimasu", en: "there is", role: "existence of a thing" },
            { jp: "よ", romaji: "yo", en: "—", role: "tells you something you did not know" },
          ],
        },
        {
          speaker: "Shopper",
          jp: "黒はありますか。",
          romaji: "Kuro wa arimasu ka.",
          en: "Do you have it in black?",
          parts: [
            { jp: "黒", romaji: "kuro", en: "black", role: "the colour as a noun" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker: as for black" },
            { jp: "あります", romaji: "arimasu", en: "there is", role: "existence of a thing" },
            { jp: "か", romaji: "ka", en: "—", role: "question marker" },
          ],
        },
        {
          speaker: "Assistant",
          jp: "はい、黒もあります。",
          romaji: "Hai, kuro mo arimasu.",
          en: "Yes, we have black too.",
          parts: [
            { jp: "はい", romaji: "hai", en: "yes", role: "confirms it" },
            { jp: "黒", romaji: "kuro", en: "black", role: "the noun" },
            { jp: "も", romaji: "mo", en: "also", role: "black as well as the blue you were holding" },
            { jp: "あります", romaji: "arimasu", en: "there is", role: "existence of a thing" },
          ],
        },
        {
          speaker: "Shopper",
          jp: "これにします。カードでお願いします。",
          romaji: "Kore ni shimasu. Kaado de onegai shimasu.",
          en: "I'll take this one. By card, please.",
          parts: [
            { jp: "これ", romaji: "kore", en: "this one", role: "the item you have chosen" },
            { jp: "に", romaji: "ni", en: "—", role: "marks the choice you settle on" },
            { jp: "します", romaji: "shimasu", en: "will do", role: "にします is the fixed way to announce a decision" },
            { jp: "カード", romaji: "kaado", en: "card", role: "a borrowed word" },
            { jp: "で", romaji: "de", en: "by", role: "marks the means of payment" },
            { jp: "お願いします", romaji: "onegai shimasu", en: "please", role: "asks for it politely" },
          ],
        },
        {
          speaker: "Assistant",
          jp: "かしこまりました。こちらにサインをお願いします。",
          romaji: "Kashikomarimashita. Kochira ni sain o onegai shimasu.",
          en: "Certainly. Please sign here.",
          parts: [
            { jp: "かしこまりました", romaji: "kashikomarimashita", en: "certainly", role: "the very polite \"understood\"" },
            { jp: "こちら", romaji: "kochira", en: "here", role: "the polite ここ" },
            { jp: "に", romaji: "ni", en: "on", role: "marks where the signature goes" },
            { jp: "サイン", romaji: "sain", en: "signature", role: "a false friend: サイン is a signature, not a sign" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "お願いします", romaji: "onegai shimasu", en: "please", role: "asks you to do it" },
          ],
        },
      ],
      takeaway:
        "Two small words do most of the work. **の** stands in for a noun you have already established — *motto ookii no* is \"a bigger one\" — and **も** adds to what is already on the table, replacing が or は rather than joining them.",
    },
    {
      id: "hashi",
      title: "Do Not Cross This Bridge",
      jpTitle: "このはしわたるな",
      icon: "🌉",
      blurb: "A famous Ikkyū riddle. Eight lines, one pun.",
      cast: "Ikkyū, a boy monk · a guard",
      lines: [
        {
          jp: "一休さんは、小さな橋の前に立ちました。",
          romaji: "Ikkyuu-san wa, chiisana hashi no mae ni tachimashita.",
          en: "Ikkyū stopped in front of a small bridge.",
          parts: [
            { jp: "一休さん", romaji: "Ikkyuu-san", en: "Ikkyū", role: "a name plus さん, the standard polite suffix" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker: this is who the sentence is about" },
            { jp: "小さな", romaji: "chiisana", en: "small", role: "describes the noun that follows" },
            { jp: "橋", romaji: "hashi", en: "bridge", role: "the noun" },
            { jp: "の", romaji: "no", en: "of", role: "links two nouns: the front of the bridge" },
            { jp: "前", romaji: "mae", en: "front", role: "a position word, used like a noun" },
            { jp: "に", romaji: "ni", en: "at", role: "marks where the action happens" },
            { jp: "立ちました", romaji: "tachimashita", en: "stood", role: "立つ (to stand), polite past" },
          ],
        },
        {
          jp: "立て札に「このはしわたるな」と書いてあります。",
          romaji: "Tatefuda ni \"kono hashi wataru na\" to kaite arimasu.",
          en: "A sign read: \"Do not cross this bridge.\"",
          parts: [
            { jp: "立て札", romaji: "tatefuda", en: "signboard", role: "the noun" },
            { jp: "に", romaji: "ni", en: "on", role: "marks where the writing sits" },
            { jp: "このはしわたるな", romaji: "kono hashi wataru na", en: "do not cross this bridge", role: "the words on the sign; plain verb plus な is a blunt prohibition" },
            { jp: "と", romaji: "to", en: "—", role: "quotative marker: closes off the quoted words" },
            { jp: "書いてあります", romaji: "kaite arimasu", en: "is written", role: "書く (to write) plus てあります, a state someone left in place" },
          ],
        },
        {
          speaker: "Guard",
          jp: "読めますか。この橋を渡ってはいけません。",
          romaji: "Yomemasu ka. Kono hashi o watatte wa ikemasen.",
          en: "Can you read? You must not cross this bridge.",
          parts: [
            { jp: "読めます", romaji: "yomemasu", en: "can read", role: "potential form of 読む (to read), polite" },
            { jp: "か", romaji: "ka", en: "—", role: "question marker: turns the statement into a question" },
            { jp: "この", romaji: "kono", en: "this", role: "points at something near the speaker" },
            { jp: "橋", romaji: "hashi", en: "bridge", role: "the noun" },
            { jp: "を", romaji: "o", en: "—", role: "object marker: the thing being crossed" },
            { jp: "渡って", romaji: "watatte", en: "crossing", role: "te-form of 渡る (to cross)" },
            { jp: "はいけません", romaji: "wa ikemasen", en: "must not", role: "てはいけません: the standard prohibition" },
          ],
        },
        {
          speaker: "Ikkyū",
          jp: "はい、読めます。",
          romaji: "Hai, yomemasu.",
          en: "Yes, I can read.",
          parts: [
            { jp: "はい", romaji: "hai", en: "yes", role: "agreement — closer to \"I hear you\" than to \"correct\"" },
            { jp: "読めます", romaji: "yomemasu", en: "I can read", role: "potential of 読む; the subject is dropped, as usual" },
          ],
        },
        {
          jp: "そう言って、一休さんは橋の真ん中を歩いて渡りました。",
          romaji: "Sou itte, Ikkyuu-san wa hashi no man-naka o aruite watarimashita.",
          en: "Saying that, Ikkyū walked across the middle of the bridge.",
          parts: [
            { jp: "そう", romaji: "sou", en: "so", role: "that way, like that" },
            { jp: "言って", romaji: "itte", en: "saying", role: "te-form of 言う (to say), chaining to the next action" },
            { jp: "一休さんは", romaji: "Ikkyuu-san wa", en: "Ikkyū", role: "the topic again" },
            { jp: "橋", romaji: "hashi", en: "bridge", role: "the noun" },
            { jp: "の", romaji: "no", en: "of", role: "links bridge to middle" },
            { jp: "真ん中", romaji: "man-naka", en: "the middle", role: "the exact centre" },
            { jp: "を", romaji: "o", en: "—", role: "object marker: the ground being crossed" },
            { jp: "歩いて", romaji: "aruite", en: "on foot", role: "te-form of 歩く (to walk): how he crossed" },
            { jp: "渡りました", romaji: "watarimashita", en: "crossed", role: "渡る, polite past" },
          ],
        },
        {
          speaker: "Guard",
          jp: "こら。渡るなと書いてありますよ。",
          romaji: "Kora. Wataru na to kaite arimasu yo.",
          en: "Hey! It says do not cross!",
          parts: [
            { jp: "こら", romaji: "kora", en: "hey!", role: "a shout used to scold" },
            { jp: "渡るな", romaji: "wataru na", en: "do not cross", role: "plain verb plus な, a blunt order not to" },
            { jp: "と", romaji: "to", en: "—", role: "quotative marker: what the sign says" },
            { jp: "書いてあります", romaji: "kaite arimasu", en: "is written", role: "the same state-of-affairs form as before" },
            { jp: "よ", romaji: "yo", en: "—", role: "sentence-final: telling you something you seem to have missed" },
          ],
        },
        {
          speaker: "Ikkyū",
          jp: "はい。だから、端は渡りませんでした。",
          romaji: "Hai. Dakara, hashi wa watarimasen deshita.",
          en: "Yes. That's why I didn't cross the edge.",
          parts: [
            { jp: "はい", romaji: "hai", en: "yes", role: "agreement" },
            { jp: "だから", romaji: "dakara", en: "that is why", role: "gives the reason for what follows" },
            { jp: "端", romaji: "hashi", en: "the edge", role: "a different word, said exactly the same way" },
            { jp: "は", romaji: "wa", en: "as for", role: "topic marker used for contrast: the edge, specifically" },
            { jp: "渡りませんでした", romaji: "watarimasen deshita", en: "did not cross", role: "渡る, polite past negative" },
          ],
        },
      ],
      catch:
        "Written in kana, はし *hashi* is two words: 橋 (bridge) and 端 (edge). Read the second way, the sign forbids only the edges — so the middle was never off limits.",
    },
    {
      id: "byoubu",
      title: "The Tiger in the Screen",
      jpTitle: "屏風の虎",
      icon: "🐯",
      blurb: "Ikkyū is handed an impossible job, and accepts it.",
      cast: "The shogun · Ikkyū",
      lines: [
        {
          jp: "将軍が一休さんを呼びました。",
          romaji: "Shougun ga Ikkyuu-san o yobimashita.",
          en: "The shogun summoned Ikkyū.",
          parts: [
            { jp: "将軍", romaji: "shougun", en: "the shogun", role: "the noun" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: who performed the action" },
            { jp: "一休さん", romaji: "Ikkyuu-san", en: "Ikkyū", role: "the name" },
            { jp: "を", romaji: "o", en: "—", role: "object marker: who was summoned" },
            { jp: "呼びました", romaji: "yobimashita", en: "summoned", role: "呼ぶ (to call), polite past" },
          ],
        },
        {
          speaker: "Shogun",
          jp: "この屏風の虎が、毎晩出てきて困ります。",
          romaji: "Kono byoubu no tora ga, maiban dete kite komarimasu.",
          en: "The tiger in this screen comes out every night and troubles me.",
          parts: [
            { jp: "この", romaji: "kono", en: "this", role: "points at the screen in front of them" },
            { jp: "屏風", romaji: "byoubu", en: "folding screen", role: "the noun" },
            { jp: "の", romaji: "no", en: "of", role: "links screen to tiger" },
            { jp: "虎", romaji: "tora", en: "tiger", role: "the noun" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: the tiger is what acts" },
            { jp: "毎晩", romaji: "maiban", en: "every night", role: "a time word; needs no particle" },
            { jp: "出てきて", romaji: "dete kite", en: "comes out", role: "出る (to exit) plus くる (to come): out towards the speaker" },
            { jp: "困ります", romaji: "komarimasu", en: "it troubles me", role: "困る, polite present" },
          ],
        },
        {
          speaker: "Shogun",
          jp: "縛ってください。",
          romaji: "Shibatte kudasai.",
          en: "Tie it up, please.",
          parts: [
            { jp: "縛って", romaji: "shibatte", en: "tie", role: "te-form of 縛る (to tie)" },
            { jp: "ください", romaji: "kudasai", en: "please", role: "てください: the everyday polite request" },
          ],
        },
        {
          speaker: "Ikkyū",
          jp: "わかりました。縄を貸してください。",
          romaji: "Wakarimashita. Nawa o kashite kudasai.",
          en: "Understood. Please lend me a rope.",
          parts: [
            { jp: "わかりました", romaji: "wakarimashita", en: "understood", role: "分かる, polite past — the standard \"got it\"" },
            { jp: "縄", romaji: "nawa", en: "rope", role: "the noun" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "貸して", romaji: "kashite", en: "lend", role: "te-form of 貸す (to lend)" },
            { jp: "ください", romaji: "kudasai", en: "please", role: "the polite request again" },
          ],
        },
        {
          jp: "一休さんは縄を持って、屏風の前に座りました。",
          romaji: "Ikkyuu-san wa nawa o motte, byoubu no mae ni suwarimashita.",
          en: "Ikkyū took the rope and sat down in front of the screen.",
          parts: [
            { jp: "一休さんは", romaji: "Ikkyuu-san wa", en: "Ikkyū", role: "the topic" },
            { jp: "縄", romaji: "nawa", en: "rope", role: "the noun" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "持って", romaji: "motte", en: "holding", role: "te-form of 持つ (to hold), chaining to the next action" },
            { jp: "屏風", romaji: "byoubu", en: "screen", role: "the noun" },
            { jp: "の前", romaji: "no mae", en: "in front of", role: "position phrase" },
            { jp: "に", romaji: "ni", en: "at", role: "marks where he sat" },
            { jp: "座りました", romaji: "suwarimashita", en: "sat down", role: "座る, polite past" },
          ],
        },
        {
          speaker: "Ikkyū",
          jp: "準備ができました。では、虎を出してください。",
          romaji: "Junbi ga dekimashita. Dewa, tora o dashite kudasai.",
          en: "I'm ready. Now please drive the tiger out.",
          parts: [
            { jp: "準備", romaji: "junbi", en: "preparation", role: "the noun" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: what is ready" },
            { jp: "できました", romaji: "dekimashita", en: "is done", role: "できる (to be ready), polite past" },
            { jp: "では", romaji: "dewa", en: "well then", role: "moves the conversation on" },
            { jp: "虎", romaji: "tora", en: "the tiger", role: "the noun" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "出して", romaji: "dashite", en: "send out", role: "te-form of 出す (to put something out)" },
            { jp: "ください", romaji: "kudasai", en: "please", role: "polite request" },
          ],
        },
        {
          speaker: "Shogun",
          jp: "絵の虎は出せません。",
          romaji: "E no tora wa dasemasen.",
          en: "I can't make a painted tiger come out.",
          parts: [
            { jp: "絵", romaji: "e", en: "a painting", role: "the noun" },
            { jp: "の", romaji: "no", en: "of", role: "links painting to tiger" },
            { jp: "虎", romaji: "tora", en: "tiger", role: "the noun" },
            { jp: "は", romaji: "wa", en: "as for", role: "topic marker, with a hint of contrast" },
            { jp: "出せません", romaji: "dasemasen", en: "cannot be sent out", role: "potential negative of 出す" },
          ],
        },
        {
          speaker: "Ikkyū",
          jp: "出てこない虎は、縛れません。",
          romaji: "Dete konai tora wa, shibaremasen.",
          en: "A tiger that doesn't come out can't be tied up.",
          parts: [
            { jp: "出てこない", romaji: "dete konai", en: "that does not come out", role: "plain negative of 出てくる, placed before the noun to describe it" },
            { jp: "虎", romaji: "tora", en: "tiger", role: "the noun being described" },
            { jp: "は", romaji: "wa", en: "as for", role: "topic marker" },
            { jp: "縛れません", romaji: "shibaremasen", en: "cannot be tied", role: "potential negative of 縛る" },
          ],
        },
      ],
      catch:
        "Ikkyū never argues that the task is impossible. He agrees to it completely, and hands back the half that was impossible all along.",
    },
    {
      id: "hae",
      title: "The Fly in the Soup",
      jpTitle: "スープの中のハエ",
      icon: "🍲",
      blurb: "A complaint, handled with total professionalism.",
      cast: "A customer · a waiter",
      lines: [
        {
          speaker: "Customer",
          jp: "すみません。スープにハエが入っています。",
          romaji: "Sumimasen. Suupu ni hae ga haitte imasu.",
          en: "Excuse me. There's a fly in my soup.",
          parts: [
            { jp: "すみません", romaji: "sumimasen", en: "excuse me", role: "also how you call staff over" },
            { jp: "スープ", romaji: "suupu", en: "soup", role: "a borrowed word, written in katakana" },
            { jp: "に", romaji: "ni", en: "in", role: "marks where the fly is" },
            { jp: "ハエ", romaji: "hae", en: "a fly", role: "the noun" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: new information, so が rather than は" },
            { jp: "入っています", romaji: "haitte imasu", en: "has got in", role: "入る plus ています: the resulting state, not the moment" },
          ],
        },
        {
          speaker: "Waiter",
          jp: "少々お待ちください。",
          romaji: "Shoushou omachi kudasai.",
          en: "One moment, please.",
          parts: [
            { jp: "少々", romaji: "shoushou", en: "a moment", role: "more formal than ちょっと" },
            { jp: "お待ちください", romaji: "omachi kudasai", en: "please wait", role: "honorific request built on 待つ; standard service Japanese" },
          ],
        },
        {
          jp: "店員は小さい声で言いました。",
          romaji: "Ten'in wa chiisai koe de iimashita.",
          en: "The waiter said, in a small voice:",
          parts: [
            { jp: "店員", romaji: "ten'in", en: "the waiter", role: "literally shop staff" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker" },
            { jp: "小さい", romaji: "chiisai", en: "small", role: "an i-adjective before its noun" },
            { jp: "声", romaji: "koe", en: "voice", role: "the noun" },
            { jp: "で", romaji: "de", en: "with", role: "means marker: the manner of speaking" },
            { jp: "言いました", romaji: "iimashita", en: "said", role: "言う, polite past" },
          ],
        },
        {
          speaker: "Waiter",
          jp: "お客様、大きい声で言わないでください。",
          romaji: "Okyaku-sama, ookii koe de iwanaide kudasai.",
          en: "Sir, please don't say it so loudly.",
          parts: [
            { jp: "お客様", romaji: "okyaku-sama", en: "sir", role: "the honorific for a customer" },
            { jp: "大きい", romaji: "ookii", en: "loud", role: "literally big" },
            { jp: "声", romaji: "koe", en: "voice", role: "the noun" },
            { jp: "で", romaji: "de", en: "with", role: "means marker" },
            { jp: "言わないでください", romaji: "iwanaide kudasai", en: "please do not say", role: "negative request: 〜ないでください" },
          ],
        },
        {
          speaker: "Customer",
          jp: "なぜですか。",
          romaji: "Naze desu ka.",
          en: "Why?",
          parts: [
            { jp: "なぜ", romaji: "naze", en: "why", role: "a little more formal than どうして" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus the question marker" },
          ],
        },
        {
          speaker: "Waiter",
          jp: "みんなが一つ欲しくなりますから。",
          romaji: "Minna ga hitotsu hoshiku narimasu kara.",
          en: "Because everyone will want one.",
          parts: [
            { jp: "みんな", romaji: "minna", en: "everyone", role: "the noun" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker" },
            { jp: "一つ", romaji: "hitotsu", en: "one", role: "the universal counter, good for any object" },
            { jp: "欲しく", romaji: "hoshiku", en: "wanting", role: "adverb form of 欲しい, needed before なる" },
            { jp: "なります", romaji: "narimasu", en: "will become", role: "なる, polite present — Japanese has no separate future" },
            { jp: "から", romaji: "kara", en: "because", role: "gives the reason, and lands last" },
          ],
        },
      ],
      catch:
        "The waiter never denies the fly. He reclassifies it — from a mistake into the house speciality, in short supply.",
    },
    {
      id: "itai",
      title: "It Hurts When I Press",
      jpTitle: "押すと痛いです",
      icon: "🩺",
      blurb: "A thorough examination reaches a diagnosis.",
      cast: "A patient · a doctor",
      lines: [
        {
          speaker: "Patient",
          jp: "先生、ここを押すと痛いです。",
          romaji: "Sensei, koko o osu to itai desu.",
          en: "Doctor, when I press here it hurts.",
          parts: [
            { jp: "先生", romaji: "sensei", en: "doctor", role: "literally teacher; used for doctors, lawyers and teachers alike" },
            { jp: "ここ", romaji: "koko", en: "here", role: "the spot nearest the speaker" },
            { jp: "を", romaji: "o", en: "—", role: "object marker: the place being pressed" },
            { jp: "押す", romaji: "osu", en: "press", role: "plain form of 押す — と demands the plain form" },
            { jp: "と", romaji: "to", en: "whenever", role: "marks a reliable consequence: press, and it hurts" },
            { jp: "痛い", romaji: "itai", en: "painful", role: "an i-adjective; on its own it means \"ouch\"" },
            { jp: "です", romaji: "desu", en: "—", role: "polite copula, closing the sentence" },
          ],
        },
        {
          speaker: "Doctor",
          jp: "ここもですか。",
          romaji: "Koko mo desu ka.",
          en: "Here too?",
          parts: [
            { jp: "ここ", romaji: "koko", en: "here", role: "the spot being pressed" },
            { jp: "も", romaji: "mo", en: "too", role: "replaces は or が rather than joining them" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus question marker" },
          ],
        },
        {
          speaker: "Patient",
          jp: "はい、そこも痛いです。",
          romaji: "Hai, soko mo itai desu.",
          en: "Yes, that hurts too.",
          parts: [
            { jp: "はい", romaji: "hai", en: "yes", role: "agreement" },
            { jp: "そこ", romaji: "soko", en: "there", role: "the spot near the listener — the doctor" },
            { jp: "も", romaji: "mo", en: "too", role: "adds to the previous spot" },
            { jp: "痛い", romaji: "itai", en: "painful", role: "the same adjective" },
            { jp: "です", romaji: "desu", en: "—", role: "polite copula" },
          ],
        },
        {
          speaker: "Doctor",
          jp: "じゃあ、ここはどうですか。",
          romaji: "Jaa, koko wa dou desu ka.",
          en: "And how about here?",
          parts: [
            { jp: "じゃあ", romaji: "jaa", en: "well then", role: "a spoken contraction of では" },
            { jp: "ここ", romaji: "koko", en: "here", role: "a new spot" },
            { jp: "は", romaji: "wa", en: "as for", role: "topic marker, contrasting with the last spot" },
            { jp: "どう", romaji: "dou", en: "how", role: "the question word" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus question marker" },
          ],
        },
        {
          speaker: "Patient",
          jp: "そこも痛いです。とても心配です。",
          romaji: "Soko mo itai desu. Totemo shinpai desu.",
          en: "That hurts too. I'm very worried.",
          parts: [
            { jp: "そこ", romaji: "soko", en: "there", role: "the doctor's new spot" },
            { jp: "も", romaji: "mo", en: "too", role: "yet another one" },
            { jp: "痛いです", romaji: "itai desu", en: "it is painful", role: "adjective plus polite copula" },
            { jp: "とても", romaji: "totemo", en: "very", role: "intensifier" },
            { jp: "心配", romaji: "shinpai", en: "worry", role: "a noun used like an adjective with です" },
            { jp: "です", romaji: "desu", en: "—", role: "polite copula" },
          ],
        },
        {
          speaker: "Doctor",
          jp: "わかりました。指が折れていますね。",
          romaji: "Wakarimashita. Yubi ga orete imasu ne.",
          en: "I see. Your finger is broken.",
          parts: [
            { jp: "わかりました", romaji: "wakarimashita", en: "I see", role: "分かる, polite past" },
            { jp: "指", romaji: "yubi", en: "your finger", role: "the patient's finger; the owner is obvious from context" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: what is broken" },
            { jp: "折れています", romaji: "orete imasu", en: "is broken", role: "折れる plus ています: the resulting state" },
            { jp: "ね", romaji: "ne", en: "is it not", role: "sentence-final, inviting agreement" },
          ],
        },
      ],
      catch:
        "Every answer was true, but the painful spots were a distraction. The pain followed the patient's broken finger doing the pressing, not the different parts of the body being pressed.",
    },
    {
      id: "kagi",
      title: "Where Is the Key?",
      jpTitle: "鍵はどこですか",
      icon: "🔑",
      blurb: "A search conducted in the best available conditions.",
      cast: "A man · a friend",
      lines: [
        {
          jp: "男が街灯の下で何かを探しています。",
          romaji: "Otoko ga gaitou no shita de nanika o sagashite imasu.",
          en: "A man is looking for something under a streetlight.",
          parts: [
            { jp: "男", romaji: "otoko", en: "a man", role: "the noun" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: he is new to the story, so が not は" },
            { jp: "街灯", romaji: "gaitou", en: "streetlight", role: "the noun" },
            { jp: "の下", romaji: "no shita", en: "under", role: "position phrase" },
            { jp: "で", romaji: "de", en: "at", role: "marks where an action takes place — に would mark mere location" },
            { jp: "何か", romaji: "nanika", en: "something", role: "何 (what) plus か makes it indefinite" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "探しています", romaji: "sagashite imasu", en: "is looking for", role: "探す plus ています: an action in progress" },
          ],
        },
        {
          speaker: "Friend",
          jp: "何を探しているんですか。",
          romaji: "Nani o sagashite iru n desu ka.",
          en: "What are you looking for?",
          parts: [
            { jp: "何", romaji: "nani", en: "what", role: "the question word" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "探している", romaji: "sagashite iru", en: "are looking for", role: "the plain form of 探しています" },
            { jp: "んですか", romaji: "n desu ka", en: "—", role: "softens the question to \"so what is it you are looking for?\"" },
          ],
        },
        {
          speaker: "Man",
          jp: "家の鍵をなくしました。",
          romaji: "Ie no kagi o nakushimashita.",
          en: "I lost my house key.",
          parts: [
            { jp: "家", romaji: "ie", en: "house", role: "the noun" },
            { jp: "の", romaji: "no", en: "of", role: "links house to key" },
            { jp: "鍵", romaji: "kagi", en: "key", role: "the noun" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "なくしました", romaji: "nakushimashita", en: "lost", role: "なくす, polite past" },
          ],
        },
        {
          jp: "二人で三十分探しました。",
          romaji: "Futari de sanjuppun sagashimashita.",
          en: "The two of them searched for thirty minutes.",
          parts: [
            { jp: "二人", romaji: "futari", en: "two people", role: "the counter for people is irregular here" },
            { jp: "で", romaji: "de", en: "—", role: "marks the group acting together: as a pair" },
            { jp: "三十分", romaji: "sanjuppun", en: "thirty minutes", role: "a duration needs no particle" },
            { jp: "探しました", romaji: "sagashimashita", en: "searched", role: "探す, polite past" },
          ],
        },
        {
          speaker: "Friend",
          jp: "本当にここでなくしましたか。",
          romaji: "Hontou ni koko de nakushimashita ka.",
          en: "Did you really lose it here?",
          parts: [
            { jp: "本当に", romaji: "hontou ni", en: "really", role: "本当 (truth) plus に makes it an adverb" },
            { jp: "ここ", romaji: "koko", en: "here", role: "under the light" },
            { jp: "で", romaji: "de", en: "at", role: "marks where the losing happened" },
            { jp: "なくしました", romaji: "nakushimashita", en: "lost it", role: "なくす, polite past" },
            { jp: "か", romaji: "ka", en: "—", role: "question marker" },
          ],
        },
        {
          speaker: "Man",
          jp: "いいえ、家の中でなくしました。",
          romaji: "Iie, ie no naka de nakushimashita.",
          en: "No, I lost it inside the house.",
          parts: [
            { jp: "いいえ", romaji: "iie", en: "no", role: "the plain denial" },
            { jp: "家", romaji: "ie", en: "house", role: "the noun" },
            { jp: "の中", romaji: "no naka", en: "inside", role: "position phrase" },
            { jp: "で", romaji: "de", en: "at", role: "marks where it happened — somewhere else entirely" },
            { jp: "なくしました", romaji: "nakushimashita", en: "lost it", role: "polite past" },
          ],
        },
        {
          speaker: "Friend",
          jp: "じゃあ、なぜここを探すんですか。",
          romaji: "Jaa, naze koko o sagasu n desu ka.",
          en: "Then why are we searching here?",
          parts: [
            { jp: "じゃあ", romaji: "jaa", en: "then", role: "picking up on what was just said" },
            { jp: "なぜ", romaji: "naze", en: "why", role: "the question word" },
            { jp: "ここ", romaji: "koko", en: "here", role: "the lit patch of ground" },
            { jp: "を", romaji: "o", en: "—", role: "object marker: the place being searched" },
            { jp: "探す", romaji: "sagasu", en: "search", role: "plain form, required before んです" },
            { jp: "んですか", romaji: "n desu ka", en: "—", role: "softened question, asking for an explanation" },
          ],
        },
        {
          speaker: "Man",
          jp: "ここのほうが明るいですから。",
          romaji: "Koko no hou ga akarui desu kara.",
          en: "Because it's brighter here.",
          parts: [
            { jp: "ここ", romaji: "koko", en: "here", role: "this spot" },
            { jp: "のほうが", romaji: "no hou ga", en: "—", role: "comparison frame: this side, more than the other" },
            { jp: "明るい", romaji: "akarui", en: "bright", role: "an i-adjective" },
            { jp: "です", romaji: "desu", en: "—", role: "polite copula" },
            { jp: "から", romaji: "kara", en: "because", role: "the reason, landing last as always" },
          ],
        },
      ],
      catch:
        "He is not searching where the key is. He is searching where searching is easy — which is a different task with the same name.",
    },
    {
      id: "onaji",
      title: "The Same as That, Please",
      jpTitle: "同じものをください",
      icon: "🍜",
      blurb: "A textbook restaurant phrase, taken at its word.",
      cast: "A tourist · a waiter",
      lines: [
        {
          speaker: "Tourist",
          jp: "すみません、おすすめは何ですか。",
          romaji: "Sumimasen, osusume wa nan desu ka.",
          en: "Excuse me, what do you recommend?",
          parts: [
            { jp: "すみません", romaji: "sumimasen", en: "excuse me", role: "how you open with staff" },
            { jp: "おすすめ", romaji: "osusume", en: "the recommendation", role: "from 勧める (to recommend), with the polite お" },
            { jp: "は", romaji: "wa", en: "as for", role: "topic marker" },
            { jp: "何", romaji: "nan", en: "what", role: "何 is read nan before です" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus question marker" },
          ],
        },
        {
          speaker: "Waiter",
          jp: "今日は、これがおすすめです。",
          romaji: "Kyou wa, kore ga osusume desu.",
          en: "Today, this is our recommendation.",
          parts: [
            { jp: "今日", romaji: "kyou", en: "today", role: "the noun" },
            { jp: "は", romaji: "wa", en: "as for", role: "topic marker: setting today as the frame" },
            { jp: "これ", romaji: "kore", en: "this one", role: "the thing nearest the speaker" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: singles this one out from the rest" },
            { jp: "おすすめ", romaji: "osusume", en: "the recommendation", role: "the noun" },
            { jp: "です", romaji: "desu", en: "—", role: "polite copula" },
          ],
        },
        {
          speaker: "Tourist",
          jp: "でも、あの人が食べているものが美味しそうです。",
          romaji: "Demo, ano hito ga tabete iru mono ga oishisou desu.",
          en: "But what that person is eating looks delicious.",
          parts: [
            { jp: "でも", romaji: "demo", en: "but", role: "contradicts what was just said" },
            { jp: "あの人", romaji: "ano hito", en: "that person", role: "あの points at someone away from both speakers" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker inside the describing clause" },
            { jp: "食べている", romaji: "tabete iru", en: "is eating", role: "plain form of 食べています" },
            { jp: "もの", romaji: "mono", en: "the thing", role: "the noun the whole clause describes" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker of the main sentence" },
            { jp: "美味しそう", romaji: "oishisou", en: "looks delicious", role: "美味しい plus そう: it appears to be" },
            { jp: "です", romaji: "desu", en: "—", role: "polite copula" },
          ],
        },
        {
          speaker: "Tourist",
          jp: "同じものをください。",
          romaji: "Onaji mono o kudasai.",
          en: "The same as that, please.",
          parts: [
            { jp: "同じ", romaji: "onaji", en: "the same", role: "sits before the noun with no の" },
            { jp: "もの", romaji: "mono", en: "thing", role: "the noun — and the ambiguity the story turns on" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "ください", romaji: "kudasai", en: "please give me", role: "the standard way to order" },
          ],
        },
        {
          speaker: "Waiter",
          jp: "かしこまりました。少々お待ちください。",
          romaji: "Kashikomarimashita. Shoushou omachi kudasai.",
          en: "Certainly. One moment, please.",
          parts: [
            { jp: "かしこまりました", romaji: "kashikomarimashita", en: "certainly", role: "the most formal \"understood\" — you hear it in restaurants and shops" },
            { jp: "少々", romaji: "shoushou", en: "a moment", role: "formal register" },
            { jp: "お待ちください", romaji: "omachi kudasai", en: "please wait", role: "honorific request from 待つ" },
          ],
        },
        {
          jp: "三十分待ちました。何も来ません。",
          romaji: "Sanjuppun machimashita. Nani mo kimasen.",
          en: "Thirty minutes passed. Nothing came.",
          parts: [
            { jp: "三十分", romaji: "sanjuppun", en: "thirty minutes", role: "a duration, no particle needed" },
            { jp: "待ちました", romaji: "machimashita", en: "waited", role: "待つ, polite past" },
            { jp: "何も", romaji: "nani mo", en: "nothing", role: "何 plus も means \"nothing at all\" when the verb is negative" },
            { jp: "来ません", romaji: "kimasen", en: "does not come", role: "来る, polite negative — irregular" },
          ],
        },
        {
          speaker: "Tourist",
          jp: "すみません、私の料理はまだですか。",
          romaji: "Sumimasen, watashi no ryouri wa mada desu ka.",
          en: "Excuse me, is my food not ready yet?",
          parts: [
            { jp: "すみません", romaji: "sumimasen", en: "excuse me", role: "calling the waiter over" },
            { jp: "私", romaji: "watashi", en: "I", role: "the pronoun" },
            { jp: "の", romaji: "no", en: "—", role: "possessive marker: my" },
            { jp: "料理", romaji: "ryouri", en: "food", role: "a cooked dish" },
            { jp: "は", romaji: "wa", en: "as for", role: "topic marker" },
            { jp: "まだ", romaji: "mada", en: "not yet", role: "with です it asks \"still nothing?\"" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus question marker" },
          ],
        },
        {
          speaker: "Waiter",
          jp: "あのお客様がもう一度注文するまで、お待ちください。",
          romaji: "Ano okyaku-sama ga mou ichido chuumon suru made, omachi kudasai.",
          en: "Please wait until that customer orders again.",
          parts: [
            { jp: "あの", romaji: "ano", en: "that", role: "pointing across the room" },
            { jp: "お客様", romaji: "okyaku-sama", en: "customer", role: "the honorific form" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker inside the until-clause" },
            { jp: "もう一度", romaji: "mou ichido", en: "once more", role: "literally already one time" },
            { jp: "注文する", romaji: "chuumon suru", en: "to order", role: "注文 (an order) plus する; plain form, as まで requires" },
            { jp: "まで", romaji: "made", en: "until", role: "marks the end point of the waiting" },
            { jp: "お待ちください", romaji: "omachi kudasai", en: "please wait", role: "the same honorific request, now doing real damage" },
          ],
        },
      ],
      catch:
        "同じもの *onaji mono* means \"the same thing\" — and the waiter heard it as the same plate, not another one like it. The phrase is real and useful; the reading is not the one you wanted.",
    },
    {
      id: "soudesuka",
      title: "Is That So?",
      jpTitle: "そうですか",
      icon: "🌾",
      blurb: "A Zen story in which one line does all the work.",
      cast: "A villager · a monk",
      lines: [
        {
          jp: "村の人が、お坊さんの家に来ました。",
          romaji: "Mura no hito ga, obousan no ie ni kimashita.",
          en: "A villager came to the monk's house.",
          parts: [
            { jp: "村", romaji: "mura", en: "village", role: "the noun" },
            { jp: "の", romaji: "no", en: "of", role: "links village to person" },
            { jp: "人", romaji: "hito", en: "person", role: "the noun" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: someone new arriving" },
            { jp: "お坊さん", romaji: "obousan", en: "the monk", role: "坊 with both the polite お and さん" },
            { jp: "の家", romaji: "no ie", en: "the house of", role: "possessive の plus 家" },
            { jp: "に", romaji: "ni", en: "to", role: "marks the destination" },
            { jp: "来ました", romaji: "kimashita", en: "came", role: "来る, polite past — irregular" },
          ],
        },
        {
          speaker: "Villager",
          jp: "この子はあなたの子だと、娘が言っています。",
          romaji: "Kono ko wa anata no ko da to, musume ga itte imasu.",
          en: "My daughter says this child is yours.",
          parts: [
            { jp: "この子", romaji: "kono ko", en: "this child", role: "この plus 子" },
            { jp: "は", romaji: "wa", en: "as for", role: "topic marker of the quoted sentence" },
            { jp: "あなた", romaji: "anata", en: "you", role: "used here because the two are strangers; normally avoided" },
            { jp: "の", romaji: "no", en: "—", role: "possessive marker" },
            { jp: "子", romaji: "ko", en: "child", role: "the noun" },
            { jp: "だ", romaji: "da", en: "is", role: "the plain copula — と will not take です" },
            { jp: "と", romaji: "to", en: "—", role: "quotative marker: everything before it is what was said" },
            { jp: "娘", romaji: "musume", en: "my daughter", role: "also the plain word for a girl" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: who is saying it" },
            { jp: "言っています", romaji: "itte imasu", en: "is saying", role: "言う plus ています: an ongoing claim" },
          ],
        },
        {
          speaker: "Monk",
          jp: "そうですか。",
          romaji: "Sou desu ka.",
          en: "Is that so?",
          parts: [
            { jp: "そう", romaji: "sou", en: "so", role: "that way, like that" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus question marker; as a set phrase it accepts what it hears" },
          ],
        },
        {
          jp: "お坊さんは赤ちゃんを育てました。一年たちました。",
          romaji: "Obousan wa akachan o sodatemashita. Ichinen tachimashita.",
          en: "The monk raised the baby. A year passed.",
          parts: [
            { jp: "お坊さん", romaji: "obousan", en: "the monk", role: "the noun" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker" },
            { jp: "赤ちゃん", romaji: "akachan", en: "the baby", role: "literally little red one" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "育てました", romaji: "sodatemashita", en: "raised", role: "育てる (to bring up), polite past" },
            { jp: "一年", romaji: "ichinen", en: "one year", role: "counter 年 for years" },
            { jp: "たちました", romaji: "tachimashita", en: "passed", role: "経つ, used only of time passing" },
          ],
        },
        {
          speaker: "Villager",
          jp: "本当の父親がわかりました。すみませんでした。",
          romaji: "Hontou no chichioya ga wakarimashita. Sumimasen deshita.",
          en: "We have found the real father. I am sorry.",
          parts: [
            { jp: "本当", romaji: "hontou", en: "true", role: "a noun meaning truth" },
            { jp: "の", romaji: "no", en: "—", role: "turns 本当 into a modifier: real, genuine" },
            { jp: "父親", romaji: "chichioya", en: "father", role: "more formal than お父さん" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: what became known" },
            { jp: "わかりました", romaji: "wakarimashita", en: "became known", role: "分かる is \"to be understood\", so the fact is the subject, not the speaker" },
            { jp: "すみませんでした", romaji: "sumimasen deshita", en: "I am sorry", role: "the past form: apologising for something already done" },
          ],
        },
        {
          speaker: "Monk",
          jp: "そうですか。",
          romaji: "Sou desu ka.",
          en: "Is that so?",
          parts: [
            { jp: "そう", romaji: "sou", en: "so", role: "that way, like that" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "the identical phrase, doing the identical work — which is the story" },
          ],
        },
      ],
      catch:
        "The same three words answer the accusation and the apology. Nothing in the monk moved either time — which is the entire story, told twice.",
    },
  ],
}
