// Short dialogue stories. Every one is built around a turn — a pun, a
// reversal, a literal reading — so it pays off in six to nine lines.
//
// Each line is { speaker?, jp, romaji, en, parts }. A line without a speaker is
// narration. `jp` is what speech synthesis reads aloud, so it holds only the
// sentence — the speaker label lives outside it. `catch` explains the turn in
// English and stays hidden until the reader asks for it.
//
// `parts` is the grammar breakdown, shown beside the translation: one entry per
// chunk of the sentence, in order, each `{ jp, romaji, en, role }` where `en` is
// what the chunk means ("—" when it carries no meaning of its own) and `role` is
// the job it does in the sentence. The chunks must concatenate back into `jp`
// exactly, ignoring punctuation — that is what makes the breakdown checkable.
//
// Grammar is kept to what the course teaches: -masu forms, plain particles,
// no keigo beyond the set phrases from Chapter 6.
export default {
  id: "stories",
  title: "Short Stories",
  intro:
    "Seven very short stories, almost all dialogue, each with a sting in the tail. Tap any sentence for its translation and a word-by-word breakdown. Play a line, or let the whole story run.",
  stories: [
    {
      id: "hashi",
      title: "Do Not Cross This Bridge",
      jpTitle: "このはしわたるな",
      icon: "🌉",
      blurb: "A famous Ikkyū riddle. Eight lines, one pun.",
      cast: "Ikkyū, a boy monk · a guard",
      lines: [
        {
          jp: "一休さんは、小さな橋の前に立ちました。",
          romaji: "Ikkyuu-san wa, chiisana hashi no mae ni tachimashita.",
          en: "Ikkyū stopped in front of a small bridge.",
          parts: [
            { jp: "一休さん", romaji: "Ikkyuu-san", en: "Ikkyū", role: "a name plus さん, the standard polite suffix" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker: this is who the sentence is about" },
            { jp: "小さな", romaji: "chiisana", en: "small", role: "describes the noun that follows" },
            { jp: "橋", romaji: "hashi", en: "bridge", role: "the noun" },
            { jp: "の", romaji: "no", en: "of", role: "links two nouns: the front of the bridge" },
            { jp: "前", romaji: "mae", en: "front", role: "a position word, used like a noun" },
            { jp: "に", romaji: "ni", en: "at", role: "marks where the action happens" },
            { jp: "立ちました", romaji: "tachimashita", en: "stood", role: "立つ (to stand), polite past" },
          ],
        },
        {
          jp: "立て札に「このはしわたるな」と書いてあります。",
          romaji: "Tatefuda ni \"kono hashi wataru na\" to kaite arimasu.",
          en: "A sign read: \"Do not cross this bridge.\"",
          parts: [
            { jp: "立て札", romaji: "tatefuda", en: "signboard", role: "the noun" },
            { jp: "に", romaji: "ni", en: "on", role: "marks where the writing sits" },
            { jp: "このはしわたるな", romaji: "kono hashi wataru na", en: "do not cross this bridge", role: "the words on the sign; plain verb plus な is a blunt prohibition" },
            { jp: "と", romaji: "to", en: "—", role: "quotative marker: closes off the quoted words" },
            { jp: "書いてあります", romaji: "kaite arimasu", en: "is written", role: "書く (to write) plus てあります, a state someone left in place" },
          ],
        },
        {
          speaker: "Guard",
          jp: "読めますか。この橋を渡ってはいけません。",
          romaji: "Yomemasu ka. Kono hashi o watatte wa ikemasen.",
          en: "Can you read? You must not cross this bridge.",
          parts: [
            { jp: "読めます", romaji: "yomemasu", en: "can read", role: "potential form of 読む (to read), polite" },
            { jp: "か", romaji: "ka", en: "—", role: "question marker: turns the statement into a question" },
            { jp: "この", romaji: "kono", en: "this", role: "points at something near the speaker" },
            { jp: "橋", romaji: "hashi", en: "bridge", role: "the noun" },
            { jp: "を", romaji: "o", en: "—", role: "object marker: the thing being crossed" },
            { jp: "渡って", romaji: "watatte", en: "crossing", role: "te-form of 渡る (to cross)" },
            { jp: "はいけません", romaji: "wa ikemasen", en: "must not", role: "てはいけません: the standard prohibition" },
          ],
        },
        {
          speaker: "Ikkyū",
          jp: "はい、読めます。",
          romaji: "Hai, yomemasu.",
          en: "Yes, I can read.",
          parts: [
            { jp: "はい", romaji: "hai", en: "yes", role: "agreement — closer to \"I hear you\" than to \"correct\"" },
            { jp: "読めます", romaji: "yomemasu", en: "I can read", role: "potential of 読む; the subject is dropped, as usual" },
          ],
        },
        {
          jp: "そう言って、一休さんは橋の真ん中を歩いて渡りました。",
          romaji: "Sou itte, Ikkyuu-san wa hashi no man-naka o aruite watarimashita.",
          en: "Saying that, Ikkyū walked across the middle of the bridge.",
          parts: [
            { jp: "そう", romaji: "sou", en: "so", role: "that way, like that" },
            { jp: "言って", romaji: "itte", en: "saying", role: "te-form of 言う (to say), chaining to the next action" },
            { jp: "一休さんは", romaji: "Ikkyuu-san wa", en: "Ikkyū", role: "the topic again" },
            { jp: "橋", romaji: "hashi", en: "bridge", role: "the noun" },
            { jp: "の", romaji: "no", en: "of", role: "links bridge to middle" },
            { jp: "真ん中", romaji: "man-naka", en: "the middle", role: "the exact centre" },
            { jp: "を", romaji: "o", en: "—", role: "object marker: the ground being crossed" },
            { jp: "歩いて", romaji: "aruite", en: "on foot", role: "te-form of 歩く (to walk): how he crossed" },
            { jp: "渡りました", romaji: "watarimashita", en: "crossed", role: "渡る, polite past" },
          ],
        },
        {
          speaker: "Guard",
          jp: "こら。渡るなと書いてありますよ。",
          romaji: "Kora. Wataru na to kaite arimasu yo.",
          en: "Hey! It says do not cross!",
          parts: [
            { jp: "こら", romaji: "kora", en: "hey!", role: "a shout used to scold" },
            { jp: "渡るな", romaji: "wataru na", en: "do not cross", role: "plain verb plus な, a blunt order not to" },
            { jp: "と", romaji: "to", en: "—", role: "quotative marker: what the sign says" },
            { jp: "書いてあります", romaji: "kaite arimasu", en: "is written", role: "the same state-of-affairs form as before" },
            { jp: "よ", romaji: "yo", en: "—", role: "sentence-final: telling you something you seem to have missed" },
          ],
        },
        {
          speaker: "Ikkyū",
          jp: "はい。だから、端は渡りませんでした。",
          romaji: "Hai. Dakara, hashi wa watarimasen deshita.",
          en: "Yes. That's why I didn't cross the edge.",
          parts: [
            { jp: "はい", romaji: "hai", en: "yes", role: "agreement" },
            { jp: "だから", romaji: "dakara", en: "that is why", role: "gives the reason for what follows" },
            { jp: "端", romaji: "hashi", en: "the edge", role: "a different word, said exactly the same way" },
            { jp: "は", romaji: "wa", en: "as for", role: "topic marker used for contrast: the edge, specifically" },
            { jp: "渡りませんでした", romaji: "watarimasen deshita", en: "did not cross", role: "渡る, polite past negative" },
          ],
        },
      ],
      catch:
        "Written in kana, はし *hashi* is two words: 橋 (bridge) and 端 (edge). Read the second way, the sign forbids only the edges — so the middle was never off limits.",
    },
    {
      id: "byoubu",
      title: "The Tiger in the Screen",
      jpTitle: "屏風の虎",
      icon: "🐯",
      blurb: "Ikkyū is handed an impossible job, and accepts it.",
      cast: "The shogun · Ikkyū",
      lines: [
        {
          jp: "将軍が一休さんを呼びました。",
          romaji: "Shougun ga Ikkyuu-san o yobimashita.",
          en: "The shogun summoned Ikkyū.",
          parts: [
            { jp: "将軍", romaji: "shougun", en: "the shogun", role: "the noun" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: who performed the action" },
            { jp: "一休さん", romaji: "Ikkyuu-san", en: "Ikkyū", role: "the name" },
            { jp: "を", romaji: "o", en: "—", role: "object marker: who was summoned" },
            { jp: "呼びました", romaji: "yobimashita", en: "summoned", role: "呼ぶ (to call), polite past" },
          ],
        },
        {
          speaker: "Shogun",
          jp: "この屏風の虎が、毎晩出てきて困ります。",
          romaji: "Kono byoubu no tora ga, maiban dete kite komarimasu.",
          en: "The tiger in this screen comes out every night and troubles me.",
          parts: [
            { jp: "この", romaji: "kono", en: "this", role: "points at the screen in front of them" },
            { jp: "屏風", romaji: "byoubu", en: "folding screen", role: "the noun" },
            { jp: "の", romaji: "no", en: "of", role: "links screen to tiger" },
            { jp: "虎", romaji: "tora", en: "tiger", role: "the noun" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: the tiger is what acts" },
            { jp: "毎晩", romaji: "maiban", en: "every night", role: "a time word; needs no particle" },
            { jp: "出てきて", romaji: "dete kite", en: "comes out", role: "出る (to exit) plus くる (to come): out towards the speaker" },
            { jp: "困ります", romaji: "komarimasu", en: "it troubles me", role: "困る, polite present" },
          ],
        },
        {
          speaker: "Shogun",
          jp: "縛ってください。",
          romaji: "Shibatte kudasai.",
          en: "Tie it up, please.",
          parts: [
            { jp: "縛って", romaji: "shibatte", en: "tie", role: "te-form of 縛る (to tie)" },
            { jp: "ください", romaji: "kudasai", en: "please", role: "てください: the everyday polite request" },
          ],
        },
        {
          speaker: "Ikkyū",
          jp: "わかりました。縄を貸してください。",
          romaji: "Wakarimashita. Nawa o kashite kudasai.",
          en: "Understood. Please lend me a rope.",
          parts: [
            { jp: "わかりました", romaji: "wakarimashita", en: "understood", role: "分かる, polite past — the standard \"got it\"" },
            { jp: "縄", romaji: "nawa", en: "rope", role: "the noun" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "貸して", romaji: "kashite", en: "lend", role: "te-form of 貸す (to lend)" },
            { jp: "ください", romaji: "kudasai", en: "please", role: "the polite request again" },
          ],
        },
        {
          jp: "一休さんは縄を持って、屏風の前に座りました。",
          romaji: "Ikkyuu-san wa nawa o motte, byoubu no mae ni suwarimashita.",
          en: "Ikkyū took the rope and sat down in front of the screen.",
          parts: [
            { jp: "一休さんは", romaji: "Ikkyuu-san wa", en: "Ikkyū", role: "the topic" },
            { jp: "縄", romaji: "nawa", en: "rope", role: "the noun" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "持って", romaji: "motte", en: "holding", role: "te-form of 持つ (to hold), chaining to the next action" },
            { jp: "屏風", romaji: "byoubu", en: "screen", role: "the noun" },
            { jp: "の前", romaji: "no mae", en: "in front of", role: "position phrase" },
            { jp: "に", romaji: "ni", en: "at", role: "marks where he sat" },
            { jp: "座りました", romaji: "suwarimashita", en: "sat down", role: "座る, polite past" },
          ],
        },
        {
          speaker: "Ikkyū",
          jp: "準備ができました。では、虎を出してください。",
          romaji: "Junbi ga dekimashita. Dewa, tora o dashite kudasai.",
          en: "I'm ready. Now please drive the tiger out.",
          parts: [
            { jp: "準備", romaji: "junbi", en: "preparation", role: "the noun" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: what is ready" },
            { jp: "できました", romaji: "dekimashita", en: "is done", role: "できる (to be ready), polite past" },
            { jp: "では", romaji: "dewa", en: "well then", role: "moves the conversation on" },
            { jp: "虎", romaji: "tora", en: "the tiger", role: "the noun" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "出して", romaji: "dashite", en: "send out", role: "te-form of 出す (to put something out)" },
            { jp: "ください", romaji: "kudasai", en: "please", role: "polite request" },
          ],
        },
        {
          speaker: "Shogun",
          jp: "絵の虎は出せません。",
          romaji: "E no tora wa dasemasen.",
          en: "I can't make a painted tiger come out.",
          parts: [
            { jp: "絵", romaji: "e", en: "a painting", role: "the noun" },
            { jp: "の", romaji: "no", en: "of", role: "links painting to tiger" },
            { jp: "虎", romaji: "tora", en: "tiger", role: "the noun" },
            { jp: "は", romaji: "wa", en: "as for", role: "topic marker, with a hint of contrast" },
            { jp: "出せません", romaji: "dasemasen", en: "cannot be sent out", role: "potential negative of 出す" },
          ],
        },
        {
          speaker: "Ikkyū",
          jp: "出てこない虎は、縛れません。",
          romaji: "Dete konai tora wa, shibaremasen.",
          en: "A tiger that doesn't come out can't be tied up.",
          parts: [
            { jp: "出てこない", romaji: "dete konai", en: "that does not come out", role: "plain negative of 出てくる, placed before the noun to describe it" },
            { jp: "虎", romaji: "tora", en: "tiger", role: "the noun being described" },
            { jp: "は", romaji: "wa", en: "as for", role: "topic marker" },
            { jp: "縛れません", romaji: "shibaremasen", en: "cannot be tied", role: "potential negative of 縛る" },
          ],
        },
      ],
      catch:
        "Ikkyū never argues that the task is impossible. He agrees to it completely, and hands back the half that was impossible all along.",
    },
    {
      id: "hae",
      title: "The Fly in the Soup",
      jpTitle: "スープの中のハエ",
      icon: "🍲",
      blurb: "A complaint, handled with total professionalism.",
      cast: "A customer · a waiter",
      lines: [
        {
          speaker: "Customer",
          jp: "すみません。スープにハエが入っています。",
          romaji: "Sumimasen. Suupu ni hae ga haitte imasu.",
          en: "Excuse me. There's a fly in my soup.",
          parts: [
            { jp: "すみません", romaji: "sumimasen", en: "excuse me", role: "also how you call staff over" },
            { jp: "スープ", romaji: "suupu", en: "soup", role: "a borrowed word, written in katakana" },
            { jp: "に", romaji: "ni", en: "in", role: "marks where the fly is" },
            { jp: "ハエ", romaji: "hae", en: "a fly", role: "the noun" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: new information, so が rather than は" },
            { jp: "入っています", romaji: "haitte imasu", en: "has got in", role: "入る plus ています: the resulting state, not the moment" },
          ],
        },
        {
          speaker: "Waiter",
          jp: "少々お待ちください。",
          romaji: "Shoushou omachi kudasai.",
          en: "One moment, please.",
          parts: [
            { jp: "少々", romaji: "shoushou", en: "a moment", role: "more formal than ちょっと" },
            { jp: "お待ちください", romaji: "omachi kudasai", en: "please wait", role: "honorific request built on 待つ; standard service Japanese" },
          ],
        },
        {
          jp: "店員は小さい声で言いました。",
          romaji: "Ten'in wa chiisai koe de iimashita.",
          en: "The waiter said, in a small voice:",
          parts: [
            { jp: "店員", romaji: "ten'in", en: "the waiter", role: "literally shop staff" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker" },
            { jp: "小さい", romaji: "chiisai", en: "small", role: "an i-adjective before its noun" },
            { jp: "声", romaji: "koe", en: "voice", role: "the noun" },
            { jp: "で", romaji: "de", en: "with", role: "means marker: the manner of speaking" },
            { jp: "言いました", romaji: "iimashita", en: "said", role: "言う, polite past" },
          ],
        },
        {
          speaker: "Waiter",
          jp: "お客様、大きい声で言わないでください。",
          romaji: "Okyaku-sama, ookii koe de iwanaide kudasai.",
          en: "Sir, please don't say it so loudly.",
          parts: [
            { jp: "お客様", romaji: "okyaku-sama", en: "sir", role: "the honorific for a customer" },
            { jp: "大きい", romaji: "ookii", en: "loud", role: "literally big" },
            { jp: "声", romaji: "koe", en: "voice", role: "the noun" },
            { jp: "で", romaji: "de", en: "with", role: "means marker" },
            { jp: "言わないでください", romaji: "iwanaide kudasai", en: "please do not say", role: "negative request: 〜ないでください" },
          ],
        },
        {
          speaker: "Customer",
          jp: "なぜですか。",
          romaji: "Naze desu ka.",
          en: "Why?",
          parts: [
            { jp: "なぜ", romaji: "naze", en: "why", role: "a little more formal than どうして" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus the question marker" },
          ],
        },
        {
          speaker: "Waiter",
          jp: "みんなが一つ欲しくなりますから。",
          romaji: "Minna ga hitotsu hoshiku narimasu kara.",
          en: "Because everyone will want one.",
          parts: [
            { jp: "みんな", romaji: "minna", en: "everyone", role: "the noun" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker" },
            { jp: "一つ", romaji: "hitotsu", en: "one", role: "the universal counter, good for any object" },
            { jp: "欲しく", romaji: "hoshiku", en: "wanting", role: "adverb form of 欲しい, needed before なる" },
            { jp: "なります", romaji: "narimasu", en: "will become", role: "なる, polite present — Japanese has no separate future" },
            { jp: "から", romaji: "kara", en: "because", role: "gives the reason, and lands last" },
          ],
        },
      ],
      catch:
        "The waiter never denies the fly. He reclassifies it — from a mistake into the house speciality, in short supply.",
    },
    {
      id: "itai",
      title: "It Hurts When I Press",
      jpTitle: "押すと痛いです",
      icon: "🩺",
      blurb: "A thorough examination reaches a diagnosis.",
      cast: "A patient · a doctor",
      lines: [
        {
          speaker: "Patient",
          jp: "先生、ここを押すと痛いです。",
          romaji: "Sensei, koko o osu to itai desu.",
          en: "Doctor, when I press here it hurts.",
          parts: [
            { jp: "先生", romaji: "sensei", en: "doctor", role: "literally teacher; used for doctors, lawyers and teachers alike" },
            { jp: "ここ", romaji: "koko", en: "here", role: "the spot nearest the speaker" },
            { jp: "を", romaji: "o", en: "—", role: "object marker: the place being pressed" },
            { jp: "押す", romaji: "osu", en: "press", role: "plain form of 押す — と demands the plain form" },
            { jp: "と", romaji: "to", en: "whenever", role: "marks a reliable consequence: press, and it hurts" },
            { jp: "痛い", romaji: "itai", en: "painful", role: "an i-adjective; on its own it means \"ouch\"" },
            { jp: "です", romaji: "desu", en: "—", role: "polite copula, closing the sentence" },
          ],
        },
        {
          speaker: "Doctor",
          jp: "ここもですか。",
          romaji: "Koko mo desu ka.",
          en: "Here too?",
          parts: [
            { jp: "ここ", romaji: "koko", en: "here", role: "the spot being pressed" },
            { jp: "も", romaji: "mo", en: "too", role: "replaces は or が rather than joining them" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus question marker" },
          ],
        },
        {
          speaker: "Patient",
          jp: "はい、そこも痛いです。",
          romaji: "Hai, soko mo itai desu.",
          en: "Yes, that hurts too.",
          parts: [
            { jp: "はい", romaji: "hai", en: "yes", role: "agreement" },
            { jp: "そこ", romaji: "soko", en: "there", role: "the spot near the listener — the doctor" },
            { jp: "も", romaji: "mo", en: "too", role: "adds to the previous spot" },
            { jp: "痛い", romaji: "itai", en: "painful", role: "the same adjective" },
            { jp: "です", romaji: "desu", en: "—", role: "polite copula" },
          ],
        },
        {
          speaker: "Doctor",
          jp: "じゃあ、ここはどうですか。",
          romaji: "Jaa, koko wa dou desu ka.",
          en: "And how about here?",
          parts: [
            { jp: "じゃあ", romaji: "jaa", en: "well then", role: "a spoken contraction of では" },
            { jp: "ここ", romaji: "koko", en: "here", role: "a new spot" },
            { jp: "は", romaji: "wa", en: "as for", role: "topic marker, contrasting with the last spot" },
            { jp: "どう", romaji: "dou", en: "how", role: "the question word" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus question marker" },
          ],
        },
        {
          speaker: "Patient",
          jp: "そこも痛いです。とても心配です。",
          romaji: "Soko mo itai desu. Totemo shinpai desu.",
          en: "That hurts too. I'm very worried.",
          parts: [
            { jp: "そこ", romaji: "soko", en: "there", role: "the doctor's new spot" },
            { jp: "も", romaji: "mo", en: "too", role: "yet another one" },
            { jp: "痛いです", romaji: "itai desu", en: "it is painful", role: "adjective plus polite copula" },
            { jp: "とても", romaji: "totemo", en: "very", role: "intensifier" },
            { jp: "心配", romaji: "shinpai", en: "worry", role: "a noun used like an adjective with です" },
            { jp: "です", romaji: "desu", en: "—", role: "polite copula" },
          ],
        },
        {
          speaker: "Doctor",
          jp: "わかりました。指が折れていますね。",
          romaji: "Wakarimashita. Yubi ga orete imasu ne.",
          en: "I see. Your finger is broken.",
          parts: [
            { jp: "わかりました", romaji: "wakarimashita", en: "I see", role: "分かる, polite past" },
            { jp: "指", romaji: "yubi", en: "your finger", role: "the patient's finger; the owner is obvious from context" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: what is broken" },
            { jp: "折れています", romaji: "orete imasu", en: "is broken", role: "折れる plus ています: the resulting state" },
            { jp: "ね", romaji: "ne", en: "is it not", role: "sentence-final, inviting agreement" },
          ],
        },
      ],
      catch:
        "Every answer was true, but the painful spots were a distraction. The pain followed the patient's broken finger doing the pressing, not the different parts of the body being pressed.",
    },
    {
      id: "kagi",
      title: "Where Is the Key?",
      jpTitle: "鍵はどこですか",
      icon: "🔑",
      blurb: "A search conducted in the best available conditions.",
      cast: "A man · a friend",
      lines: [
        {
          jp: "男が街灯の下で何かを探しています。",
          romaji: "Otoko ga gaitou no shita de nanika o sagashite imasu.",
          en: "A man is looking for something under a streetlight.",
          parts: [
            { jp: "男", romaji: "otoko", en: "a man", role: "the noun" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: he is new to the story, so が not は" },
            { jp: "街灯", romaji: "gaitou", en: "streetlight", role: "the noun" },
            { jp: "の下", romaji: "no shita", en: "under", role: "position phrase" },
            { jp: "で", romaji: "de", en: "at", role: "marks where an action takes place — に would mark mere location" },
            { jp: "何か", romaji: "nanika", en: "something", role: "何 (what) plus か makes it indefinite" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "探しています", romaji: "sagashite imasu", en: "is looking for", role: "探す plus ています: an action in progress" },
          ],
        },
        {
          speaker: "Friend",
          jp: "何を探しているんですか。",
          romaji: "Nani o sagashite iru n desu ka.",
          en: "What are you looking for?",
          parts: [
            { jp: "何", romaji: "nani", en: "what", role: "the question word" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "探している", romaji: "sagashite iru", en: "are looking for", role: "the plain form of 探しています" },
            { jp: "んですか", romaji: "n desu ka", en: "—", role: "softens the question to \"so what is it you are looking for?\"" },
          ],
        },
        {
          speaker: "Man",
          jp: "家の鍵をなくしました。",
          romaji: "Ie no kagi o nakushimashita.",
          en: "I lost my house key.",
          parts: [
            { jp: "家", romaji: "ie", en: "house", role: "the noun" },
            { jp: "の", romaji: "no", en: "of", role: "links house to key" },
            { jp: "鍵", romaji: "kagi", en: "key", role: "the noun" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "なくしました", romaji: "nakushimashita", en: "lost", role: "なくす, polite past" },
          ],
        },
        {
          jp: "二人で三十分探しました。",
          romaji: "Futari de sanjuppun sagashimashita.",
          en: "The two of them searched for thirty minutes.",
          parts: [
            { jp: "二人", romaji: "futari", en: "two people", role: "the counter for people is irregular here" },
            { jp: "で", romaji: "de", en: "—", role: "marks the group acting together: as a pair" },
            { jp: "三十分", romaji: "sanjuppun", en: "thirty minutes", role: "a duration needs no particle" },
            { jp: "探しました", romaji: "sagashimashita", en: "searched", role: "探す, polite past" },
          ],
        },
        {
          speaker: "Friend",
          jp: "本当にここでなくしましたか。",
          romaji: "Hontou ni koko de nakushimashita ka.",
          en: "Did you really lose it here?",
          parts: [
            { jp: "本当に", romaji: "hontou ni", en: "really", role: "本当 (truth) plus に makes it an adverb" },
            { jp: "ここ", romaji: "koko", en: "here", role: "under the light" },
            { jp: "で", romaji: "de", en: "at", role: "marks where the losing happened" },
            { jp: "なくしました", romaji: "nakushimashita", en: "lost it", role: "なくす, polite past" },
            { jp: "か", romaji: "ka", en: "—", role: "question marker" },
          ],
        },
        {
          speaker: "Man",
          jp: "いいえ、家の中でなくしました。",
          romaji: "Iie, ie no naka de nakushimashita.",
          en: "No, I lost it inside the house.",
          parts: [
            { jp: "いいえ", romaji: "iie", en: "no", role: "the plain denial" },
            { jp: "家", romaji: "ie", en: "house", role: "the noun" },
            { jp: "の中", romaji: "no naka", en: "inside", role: "position phrase" },
            { jp: "で", romaji: "de", en: "at", role: "marks where it happened — somewhere else entirely" },
            { jp: "なくしました", romaji: "nakushimashita", en: "lost it", role: "polite past" },
          ],
        },
        {
          speaker: "Friend",
          jp: "じゃあ、なぜここを探すんですか。",
          romaji: "Jaa, naze koko o sagasu n desu ka.",
          en: "Then why are we searching here?",
          parts: [
            { jp: "じゃあ", romaji: "jaa", en: "then", role: "picking up on what was just said" },
            { jp: "なぜ", romaji: "naze", en: "why", role: "the question word" },
            { jp: "ここ", romaji: "koko", en: "here", role: "the lit patch of ground" },
            { jp: "を", romaji: "o", en: "—", role: "object marker: the place being searched" },
            { jp: "探す", romaji: "sagasu", en: "search", role: "plain form, required before んです" },
            { jp: "んですか", romaji: "n desu ka", en: "—", role: "softened question, asking for an explanation" },
          ],
        },
        {
          speaker: "Man",
          jp: "ここのほうが明るいですから。",
          romaji: "Koko no hou ga akarui desu kara.",
          en: "Because it's brighter here.",
          parts: [
            { jp: "ここ", romaji: "koko", en: "here", role: "this spot" },
            { jp: "のほうが", romaji: "no hou ga", en: "—", role: "comparison frame: this side, more than the other" },
            { jp: "明るい", romaji: "akarui", en: "bright", role: "an i-adjective" },
            { jp: "です", romaji: "desu", en: "—", role: "polite copula" },
            { jp: "から", romaji: "kara", en: "because", role: "the reason, landing last as always" },
          ],
        },
      ],
      catch:
        "He is not searching where the key is. He is searching where searching is easy — which is a different task with the same name.",
    },
    {
      id: "onaji",
      title: "The Same as That, Please",
      jpTitle: "同じものをください",
      icon: "🍜",
      blurb: "A textbook restaurant phrase, taken at its word.",
      cast: "A tourist · a waiter",
      lines: [
        {
          speaker: "Tourist",
          jp: "すみません、おすすめは何ですか。",
          romaji: "Sumimasen, osusume wa nan desu ka.",
          en: "Excuse me, what do you recommend?",
          parts: [
            { jp: "すみません", romaji: "sumimasen", en: "excuse me", role: "how you open with staff" },
            { jp: "おすすめ", romaji: "osusume", en: "the recommendation", role: "from 勧める (to recommend), with the polite お" },
            { jp: "は", romaji: "wa", en: "as for", role: "topic marker" },
            { jp: "何", romaji: "nan", en: "what", role: "何 is read nan before です" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus question marker" },
          ],
        },
        {
          speaker: "Waiter",
          jp: "今日は、これがおすすめです。",
          romaji: "Kyou wa, kore ga osusume desu.",
          en: "Today, this is our recommendation.",
          parts: [
            { jp: "今日", romaji: "kyou", en: "today", role: "the noun" },
            { jp: "は", romaji: "wa", en: "as for", role: "topic marker: setting today as the frame" },
            { jp: "これ", romaji: "kore", en: "this one", role: "the thing nearest the speaker" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: singles this one out from the rest" },
            { jp: "おすすめ", romaji: "osusume", en: "the recommendation", role: "the noun" },
            { jp: "です", romaji: "desu", en: "—", role: "polite copula" },
          ],
        },
        {
          speaker: "Tourist",
          jp: "でも、あの人が食べているものが美味しそうです。",
          romaji: "Demo, ano hito ga tabete iru mono ga oishisou desu.",
          en: "But what that person is eating looks delicious.",
          parts: [
            { jp: "でも", romaji: "demo", en: "but", role: "contradicts what was just said" },
            { jp: "あの人", romaji: "ano hito", en: "that person", role: "あの points at someone away from both speakers" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker inside the describing clause" },
            { jp: "食べている", romaji: "tabete iru", en: "is eating", role: "plain form of 食べています" },
            { jp: "もの", romaji: "mono", en: "the thing", role: "the noun the whole clause describes" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker of the main sentence" },
            { jp: "美味しそう", romaji: "oishisou", en: "looks delicious", role: "美味しい plus そう: it appears to be" },
            { jp: "です", romaji: "desu", en: "—", role: "polite copula" },
          ],
        },
        {
          speaker: "Tourist",
          jp: "同じものをください。",
          romaji: "Onaji mono o kudasai.",
          en: "The same as that, please.",
          parts: [
            { jp: "同じ", romaji: "onaji", en: "the same", role: "sits before the noun with no の" },
            { jp: "もの", romaji: "mono", en: "thing", role: "the noun — and the ambiguity the story turns on" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "ください", romaji: "kudasai", en: "please give me", role: "the standard way to order" },
          ],
        },
        {
          speaker: "Waiter",
          jp: "かしこまりました。少々お待ちください。",
          romaji: "Kashikomarimashita. Shoushou omachi kudasai.",
          en: "Certainly. One moment, please.",
          parts: [
            { jp: "かしこまりました", romaji: "kashikomarimashita", en: "certainly", role: "the most formal \"understood\" — you hear it in restaurants and shops" },
            { jp: "少々", romaji: "shoushou", en: "a moment", role: "formal register" },
            { jp: "お待ちください", romaji: "omachi kudasai", en: "please wait", role: "honorific request from 待つ" },
          ],
        },
        {
          jp: "三十分待ちました。何も来ません。",
          romaji: "Sanjuppun machimashita. Nani mo kimasen.",
          en: "Thirty minutes passed. Nothing came.",
          parts: [
            { jp: "三十分", romaji: "sanjuppun", en: "thirty minutes", role: "a duration, no particle needed" },
            { jp: "待ちました", romaji: "machimashita", en: "waited", role: "待つ, polite past" },
            { jp: "何も", romaji: "nani mo", en: "nothing", role: "何 plus も means \"nothing at all\" when the verb is negative" },
            { jp: "来ません", romaji: "kimasen", en: "does not come", role: "来る, polite negative — irregular" },
          ],
        },
        {
          speaker: "Tourist",
          jp: "すみません、私の料理はまだですか。",
          romaji: "Sumimasen, watashi no ryouri wa mada desu ka.",
          en: "Excuse me, is my food not ready yet?",
          parts: [
            { jp: "すみません", romaji: "sumimasen", en: "excuse me", role: "calling the waiter over" },
            { jp: "私", romaji: "watashi", en: "I", role: "the pronoun" },
            { jp: "の", romaji: "no", en: "—", role: "possessive marker: my" },
            { jp: "料理", romaji: "ryouri", en: "food", role: "a cooked dish" },
            { jp: "は", romaji: "wa", en: "as for", role: "topic marker" },
            { jp: "まだ", romaji: "mada", en: "not yet", role: "with です it asks \"still nothing?\"" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus question marker" },
          ],
        },
        {
          speaker: "Waiter",
          jp: "あのお客様がもう一度注文するまで、お待ちください。",
          romaji: "Ano okyaku-sama ga mou ichido chuumon suru made, omachi kudasai.",
          en: "Please wait until that customer orders again.",
          parts: [
            { jp: "あの", romaji: "ano", en: "that", role: "pointing across the room" },
            { jp: "お客様", romaji: "okyaku-sama", en: "customer", role: "the honorific form" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker inside the until-clause" },
            { jp: "もう一度", romaji: "mou ichido", en: "once more", role: "literally already one time" },
            { jp: "注文する", romaji: "chuumon suru", en: "to order", role: "注文 (an order) plus する; plain form, as まで requires" },
            { jp: "まで", romaji: "made", en: "until", role: "marks the end point of the waiting" },
            { jp: "お待ちください", romaji: "omachi kudasai", en: "please wait", role: "the same honorific request, now doing real damage" },
          ],
        },
      ],
      catch:
        "同じもの *onaji mono* means \"the same thing\" — and the waiter heard it as the same plate, not another one like it. The phrase is real and useful; the reading is not the one you wanted.",
    },
    {
      id: "soudesuka",
      title: "Is That So?",
      jpTitle: "そうですか",
      icon: "🌾",
      blurb: "A Zen story in which one line does all the work.",
      cast: "A villager · a monk",
      lines: [
        {
          jp: "村の人が、お坊さんの家に来ました。",
          romaji: "Mura no hito ga, obousan no ie ni kimashita.",
          en: "A villager came to the monk's house.",
          parts: [
            { jp: "村", romaji: "mura", en: "village", role: "the noun" },
            { jp: "の", romaji: "no", en: "of", role: "links village to person" },
            { jp: "人", romaji: "hito", en: "person", role: "the noun" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: someone new arriving" },
            { jp: "お坊さん", romaji: "obousan", en: "the monk", role: "坊 with both the polite お and さん" },
            { jp: "の家", romaji: "no ie", en: "the house of", role: "possessive の plus 家" },
            { jp: "に", romaji: "ni", en: "to", role: "marks the destination" },
            { jp: "来ました", romaji: "kimashita", en: "came", role: "来る, polite past — irregular" },
          ],
        },
        {
          speaker: "Villager",
          jp: "この子はあなたの子だと、娘が言っています。",
          romaji: "Kono ko wa anata no ko da to, musume ga itte imasu.",
          en: "My daughter says this child is yours.",
          parts: [
            { jp: "この子", romaji: "kono ko", en: "this child", role: "この plus 子" },
            { jp: "は", romaji: "wa", en: "as for", role: "topic marker of the quoted sentence" },
            { jp: "あなた", romaji: "anata", en: "you", role: "used here because the two are strangers; normally avoided" },
            { jp: "の", romaji: "no", en: "—", role: "possessive marker" },
            { jp: "子", romaji: "ko", en: "child", role: "the noun" },
            { jp: "だ", romaji: "da", en: "is", role: "the plain copula — と will not take です" },
            { jp: "と", romaji: "to", en: "—", role: "quotative marker: everything before it is what was said" },
            { jp: "娘", romaji: "musume", en: "my daughter", role: "also the plain word for a girl" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: who is saying it" },
            { jp: "言っています", romaji: "itte imasu", en: "is saying", role: "言う plus ています: an ongoing claim" },
          ],
        },
        {
          speaker: "Monk",
          jp: "そうですか。",
          romaji: "Sou desu ka.",
          en: "Is that so?",
          parts: [
            { jp: "そう", romaji: "sou", en: "so", role: "that way, like that" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "polite copula plus question marker; as a set phrase it accepts what it hears" },
          ],
        },
        {
          jp: "お坊さんは赤ちゃんを育てました。一年たちました。",
          romaji: "Obousan wa akachan o sodatemashita. Ichinen tachimashita.",
          en: "The monk raised the baby. A year passed.",
          parts: [
            { jp: "お坊さん", romaji: "obousan", en: "the monk", role: "the noun" },
            { jp: "は", romaji: "wa", en: "—", role: "topic marker" },
            { jp: "赤ちゃん", romaji: "akachan", en: "the baby", role: "literally little red one" },
            { jp: "を", romaji: "o", en: "—", role: "object marker" },
            { jp: "育てました", romaji: "sodatemashita", en: "raised", role: "育てる (to bring up), polite past" },
            { jp: "一年", romaji: "ichinen", en: "one year", role: "counter 年 for years" },
            { jp: "たちました", romaji: "tachimashita", en: "passed", role: "経つ, used only of time passing" },
          ],
        },
        {
          speaker: "Villager",
          jp: "本当の父親がわかりました。すみませんでした。",
          romaji: "Hontou no chichioya ga wakarimashita. Sumimasen deshita.",
          en: "We have found the real father. I am sorry.",
          parts: [
            { jp: "本当", romaji: "hontou", en: "true", role: "a noun meaning truth" },
            { jp: "の", romaji: "no", en: "—", role: "turns 本当 into a modifier: real, genuine" },
            { jp: "父親", romaji: "chichioya", en: "father", role: "more formal than お父さん" },
            { jp: "が", romaji: "ga", en: "—", role: "subject marker: what became known" },
            { jp: "わかりました", romaji: "wakarimashita", en: "became known", role: "分かる is \"to be understood\", so the fact is the subject, not the speaker" },
            { jp: "すみませんでした", romaji: "sumimasen deshita", en: "I am sorry", role: "the past form: apologising for something already done" },
          ],
        },
        {
          speaker: "Monk",
          jp: "そうですか。",
          romaji: "Sou desu ka.",
          en: "Is that so?",
          parts: [
            { jp: "そう", romaji: "sou", en: "so", role: "that way, like that" },
            { jp: "ですか", romaji: "desu ka", en: "—", role: "the identical phrase, doing the identical work — which is the story" },
          ],
        },
      ],
      catch:
        "The same three words answer the accusation and the apology. Nothing in the monk moved either time — which is the entire story, told twice.",
    },
  ],
}
