// Word decks for the "Common Words" section — pure vocabulary, no prose.
//
// Each word is { jp, romaji, en, note? }:
//   jp     — the Japanese as it is actually written (used for the 🔊 audio)
//   romaji — long vowels written out (biiru, arigatou), per the course convention
//   en     — the English meaning
//   note   — optional one-line usage warning, shown under the meaning
export default {
  id: 'common-words',
  title: 'Common Words',
  intro:
    'Pure vocabulary, grouped by where you will need it. Pick a scenario, then flip the ' +
    'cards. Tap 🔊 on any card to hear it spoken.',
  scenarios: [
    {
      id: 'essentials',
      title: 'Essentials',
      icon: '🎒',
      blurb: 'The words that work everywhere, in every scenario below.',
      words: [
        { jp: 'ありがとうございます', romaji: 'arigatou gozaimasu', en: 'thank you (polite)' },
        { jp: 'ありがとう', romaji: 'arigatou', en: 'thanks (casual)' },
        { jp: 'すみません', romaji: 'sumimasen', en: 'excuse me / sorry', note: 'Also how you call a waiter or a shop assistant — say it out loud.' },
        { jp: 'ごめんなさい', romaji: 'gomen nasai', en: 'I am sorry (apology)' },
        { jp: 'お願いします', romaji: 'onegai shimasu', en: 'please (when asking for something)' },
        { jp: 'ください', romaji: 'kudasai', en: 'please give me …' },
        { jp: 'はい', romaji: 'hai', en: 'yes / I hear you', note: 'Closer to "I am listening" than to agreement.' },
        { jp: 'いいえ', romaji: 'iie', en: 'no' },
        { jp: '大丈夫', romaji: 'daijoubu', en: 'fine / OK / no thanks', note: 'The all-purpose word. Often a polite refusal.' },
        { jp: 'ちょっと', romaji: 'chotto', en: 'a little / hmm, no', note: 'Trailing off with chotto… is a soft "no".' },
        { jp: 'わかりません', romaji: 'wakarimasen', en: 'I do not understand' },
        { jp: '英語', romaji: 'eigo', en: 'English (the language)' },
        { jp: '日本語', romaji: 'nihongo', en: 'Japanese (the language)' },
        { jp: 'これ', romaji: 'kore', en: 'this one (near me)' },
        { jp: 'それ', romaji: 'sore', en: 'that one (near you)' },
        { jp: 'あれ', romaji: 'are', en: 'that one over there' },
        { jp: 'どこ', romaji: 'doko', en: 'where' },
        { jp: 'いくら', romaji: 'ikura', en: 'how much' },
        { jp: '何', romaji: 'nani', en: 'what' },
        { jp: 'トイレ', romaji: 'toire', en: 'toilet' },
      ],
    },
    {
      id: 'restaurant',
      title: 'Restaurant',
      icon: '🍜',
      blurb: 'Enough to order, to avoid what you cannot eat, and to pay.',
      words: [
        { jp: 'メニュー', romaji: 'menyuu', en: 'menu' },
        { jp: 'おすすめ', romaji: 'osusume', en: 'the recommendation' },
        { jp: '水', romaji: 'mizu', en: 'water' },
        { jp: 'お茶', romaji: 'ocha', en: 'tea' },
        { jp: 'ビール', romaji: 'biiru', en: 'beer', note: 'Two beats on the ii — biru (one beat) is a building.' },
        { jp: 'ご飯', romaji: 'gohan', en: 'rice / a meal' },
        { jp: '肉', romaji: 'niku', en: 'meat' },
        { jp: '鶏肉', romaji: 'toriniku', en: 'chicken' },
        { jp: '豚肉', romaji: 'butaniku', en: 'pork' },
        { jp: '牛肉', romaji: 'gyuuniku', en: 'beef' },
        { jp: '魚', romaji: 'sakana', en: 'fish' },
        { jp: '野菜', romaji: 'yasai', en: 'vegetables' },
        { jp: '卵', romaji: 'tamago', en: 'egg' },
        { jp: 'だし', romaji: 'dashi', en: 'fish stock', note: 'Hides in most "vegetable" dishes — worth knowing if you avoid fish.' },
        { jp: 'アレルギー', romaji: 'arerugii', en: 'allergy' },
        { jp: '辛い', romaji: 'karai', en: 'spicy' },
        { jp: '美味しい', romaji: 'oishii', en: 'delicious' },
        { jp: '一つ', romaji: 'hitotsu', en: 'one (of anything)' },
        { jp: '二つ', romaji: 'futatsu', en: 'two (of anything)' },
        { jp: '箸', romaji: 'hashi', en: 'chopsticks' },
        { jp: '席', romaji: 'seki', en: 'seat / table' },
        { jp: '持ち帰り', romaji: 'mochikaeri', en: 'takeaway' },
        { jp: 'お会計', romaji: 'okaikei', en: 'the bill' },
        { jp: '以上です', romaji: 'ijou desu', en: 'that is all (order finished)' },
      ],
    },
    {
      id: 'hotel',
      title: 'Hotel',
      icon: '🛏️',
      blurb: 'Checking in, asking for things, and reporting what is broken.',
      words: [
        { jp: '予約', romaji: 'yoyaku', en: 'reservation' },
        { jp: 'チェックイン', romaji: 'chekku-in', en: 'check-in' },
        { jp: 'チェックアウト', romaji: 'chekku-auto', en: 'check-out' },
        { jp: '部屋', romaji: 'heya', en: 'room' },
        { jp: '鍵', romaji: 'kagi', en: 'key' },
        { jp: '一泊', romaji: 'ippaku', en: 'one night (of a stay)' },
        { jp: '二人', romaji: 'futari', en: 'two people' },
        { jp: '荷物', romaji: 'nimotsu', en: 'luggage' },
        { jp: 'フロント', romaji: 'furonto', en: 'front desk / reception' },
        { jp: 'タオル', romaji: 'taoru', en: 'towel' },
        { jp: '枕', romaji: 'makura', en: 'pillow' },
        { jp: '朝食', romaji: 'choushoku', en: 'breakfast' },
        { jp: 'お風呂', romaji: 'ofuro', en: 'bath' },
        { jp: 'シャワー', romaji: 'shawaa', en: 'shower' },
        { jp: 'エアコン', romaji: 'eakon', en: 'air conditioning' },
        { jp: 'パスワード', romaji: 'pasuwaado', en: 'password (Wi-Fi)' },
        { jp: 'エレベーター', romaji: 'erebeetaa', en: 'lift / elevator' },
        { jp: '何階', romaji: 'nan-gai', en: 'which floor' },
        { jp: '禁煙', romaji: "kin'en", en: 'non-smoking' },
        { jp: '故障', romaji: 'koshou', en: 'broken / out of order' },
        { jp: '洗濯', romaji: 'sentaku', en: 'laundry' },
        { jp: 'コインロッカー', romaji: 'koin-rokkaa', en: 'coin locker' },
      ],
    },
    {
      id: 'shop',
      title: 'Shop',
      icon: '🛍️',
      blurb: 'Prices, sizes, paying, and the tax-free counter.',
      words: [
        { jp: '店', romaji: 'mise', en: 'shop' },
        { jp: 'コンビニ', romaji: 'konbini', en: 'convenience store' },
        { jp: '薬局', romaji: 'yakkyoku', en: 'pharmacy' },
        { jp: 'お金', romaji: 'okane', en: 'money' },
        { jp: '円', romaji: 'en', en: 'yen', note: 'Said "en", not "yen".' },
        { jp: '現金', romaji: 'genkin', en: 'cash' },
        { jp: 'カード', romaji: 'kaado', en: 'card' },
        { jp: '税込', romaji: 'zeikomi', en: 'tax included' },
        { jp: '免税', romaji: 'menzei', en: 'tax-free' },
        { jp: 'レシート', romaji: 'reshiito', en: 'receipt' },
        { jp: '袋', romaji: 'fukuro', en: 'bag' },
        { jp: '安い', romaji: 'yasui', en: 'cheap' },
        { jp: '高い', romaji: 'takai', en: 'expensive (also: tall)' },
        { jp: '大きい', romaji: 'ookii', en: 'big' },
        { jp: '小さい', romaji: 'chiisai', en: 'small' },
        { jp: 'サイズ', romaji: 'saizu', en: 'size' },
        { jp: '色', romaji: 'iro', en: 'colour' },
        { jp: '他の', romaji: 'hoka no', en: 'another / a different one' },
        { jp: '試着', romaji: 'shichaku', en: 'trying clothes on' },
        { jp: '全部', romaji: 'zenbu', en: 'all of it / everything' },
        { jp: '売り切れ', romaji: 'urikire', en: 'sold out' },
        { jp: 'お土産', romaji: 'omiyage', en: 'souvenir / gift to take home' },
      ],
    },
    {
      id: 'street',
      title: 'Street',
      icon: '🚉',
      blurb: 'Stations, tickets, and the words in every answer to "where is …?".',
      words: [
        { jp: '駅', romaji: 'eki', en: 'station' },
        { jp: '電車', romaji: 'densha', en: 'train' },
        { jp: '地下鉄', romaji: 'chikatetsu', en: 'subway' },
        { jp: 'バス', romaji: 'basu', en: 'bus' },
        { jp: 'タクシー', romaji: 'takushii', en: 'taxi' },
        { jp: '空港', romaji: 'kuukou', en: 'airport' },
        { jp: '切符', romaji: 'kippu', en: 'ticket' },
        { jp: '片道', romaji: 'katamichi', en: 'one way' },
        { jp: '往復', romaji: 'oufuku', en: 'return / round trip' },
        { jp: '乗り換え', romaji: 'norikae', en: 'changing trains' },
        { jp: 'ホーム', romaji: 'hoomu', en: 'platform' },
        { jp: '出口', romaji: 'deguchi', en: 'exit' },
        { jp: '入口', romaji: 'iriguchi', en: 'entrance' },
        { jp: '右', romaji: 'migi', en: 'right' },
        { jp: '左', romaji: 'hidari', en: 'left' },
        { jp: 'まっすぐ', romaji: 'massugu', en: 'straight ahead' },
        { jp: '次', romaji: 'tsugi', en: 'the next one' },
        { jp: '角', romaji: 'kado', en: 'corner' },
        { jp: '信号', romaji: 'shingou', en: 'traffic light' },
        { jp: '近い', romaji: 'chikai', en: 'near' },
        { jp: '遠い', romaji: 'tooi', en: 'far' },
        { jp: '地図', romaji: 'chizu', en: 'map' },
        { jp: '住所', romaji: 'juusho', en: 'address' },
        { jp: '何時', romaji: 'nanji', en: 'what time' },
      ],
    },
    {
      id: 'trouble',
      title: 'Trouble',
      icon: '🩹',
      blurb: 'Illness, loss and emergencies — the deck you hope stays unused.',
      words: [
        { jp: '助けて', romaji: 'tasukete', en: 'help!' },
        { jp: '病院', romaji: 'byouin', en: 'hospital' },
        { jp: '医者', romaji: 'isha', en: 'doctor' },
        { jp: '薬', romaji: 'kusuri', en: 'medicine' },
        { jp: '痛い', romaji: 'itai', en: 'it hurts / painful' },
        { jp: '頭', romaji: 'atama', en: 'head' },
        { jp: 'お腹', romaji: 'onaka', en: 'stomach' },
        { jp: '熱', romaji: 'netsu', en: 'a fever' },
        { jp: '風邪', romaji: 'kaze', en: 'a cold (illness)' },
        { jp: '気分が悪い', romaji: 'kibun ga warui', en: 'I feel unwell' },
        { jp: '警察', romaji: 'keisatsu', en: 'police' },
        { jp: '財布', romaji: 'saifu', en: 'wallet' },
        { jp: 'なくしました', romaji: 'nakushimashita', en: 'I have lost (it)' },
        { jp: '忘れました', romaji: 'wasuremashita', en: 'I have left / forgotten (it)' },
        { jp: '道に迷いました', romaji: 'michi ni mayoimashita', en: 'I am lost' },
        { jp: '危ない', romaji: 'abunai', en: 'dangerous / watch out!' },
        { jp: '大使館', romaji: 'taishikan', en: 'embassy' },
        { jp: '保険', romaji: 'hoken', en: 'insurance' },
        { jp: '交番', romaji: 'kouban', en: 'police box', note: 'The small neighbourhood police post — your first stop for lost items.' },
      ],
    },
    {
      id: 'people',
      title: 'People',
      icon: '🙂',
      blurb: 'Greetings and the small talk that follows "where are you from?".',
      words: [
        { jp: 'おはようございます', romaji: 'ohayou gozaimasu', en: 'good morning' },
        { jp: 'こんにちは', romaji: 'konnichiwa', en: 'hello (daytime)' },
        { jp: 'こんばんは', romaji: 'konbanwa', en: 'good evening' },
        { jp: 'はじめまして', romaji: 'hajimemashite', en: 'nice to meet you (first time only)' },
        { jp: 'よろしくお願いします', romaji: 'yoroshiku onegai shimasu', en: 'pleased to be dealing with you' },
        { jp: 'さようなら', romaji: 'sayounara', en: 'goodbye', note: 'Heavier than English "bye" — for real partings.' },
        { jp: 'また明日', romaji: 'mata ashita', en: 'see you tomorrow' },
        { jp: 'お名前', romaji: 'onamae', en: 'your name' },
        { jp: '私', romaji: 'watashi', en: 'I / me' },
        { jp: '旅行', romaji: 'ryokou', en: 'a trip / travel' },
        { jp: '観光', romaji: 'kankou', en: 'sightseeing' },
        { jp: '仕事', romaji: 'shigoto', en: 'work / job' },
        { jp: '好き', romaji: 'suki', en: 'like / fond of' },
        { jp: '楽しい', romaji: 'tanoshii', en: 'fun / enjoyable' },
        { jp: '綺麗', romaji: 'kirei', en: 'beautiful / clean' },
        { jp: 'すごい', romaji: 'sugoi', en: 'wow / amazing' },
        { jp: '暑い', romaji: 'atsui', en: 'hot (weather)' },
        { jp: '寒い', romaji: 'samui', en: 'cold (weather)' },
        { jp: '天気', romaji: 'tenki', en: 'weather' },
        { jp: 'そうですね', romaji: 'sou desu ne', en: 'that is true / hmm, yes', note: 'The universal time-buying agreement noise.' },
      ],
    },
  ],
}
