// Word decks for the "Common Words" section — pure vocabulary, no prose.
//
// Each word is { jp, romaji, en, note?, example? }:
//   jp     — the Japanese as it is actually written (used for the 🔊 audio)
//   romaji — long vowels written out (biiru, arigatou), per the course convention
//   en     — the English meaning
//   note   — optional one-line usage warning, shown under the meaning
//   example — optional { jp, before, focus, after, en }; the three romaji pieces
//             are rendered in italics, with `focus` bolded
export default {
  id: 'common-words',
  title: 'Common Words',
  intro:
    'Pure vocabulary, grouped by where you will need it. Pick a scenario, then flip the ' +
    'cards. Tap 🔊 on any card to hear it spoken.',
  scenarios: [
    {
      id: 'particles',
      title: 'Particles',
      icon: '🧩',
      blurb: 'The small words that show how each part of a sentence fits together.',
      words: [
        { jp: 'は', romaji: 'wa', en: 'topic marker: as for …', note: 'Written は but pronounced wa.', example: { jp: '私はアンナです。', before: 'Watashi ', focus: 'wa', after: ' Anna desu.', en: 'I am Anna.' } },
        { jp: 'が', romaji: 'ga', en: 'subject marker', example: { jp: '水があります。', before: 'Mizu ', focus: 'ga', after: ' arimasu.', en: 'There is water.' } },
        { jp: 'を', romaji: 'o', en: 'direct-object marker', note: 'Written を but pronounced o.', example: { jp: '寿司を食べます。', before: 'Sushi ', focus: 'o', after: ' tabemasu.', en: 'I eat sushi.' } },
        { jp: 'に', romaji: 'ni', en: 'to / at (destination or time)', example: { jp: '店に行きます。', before: 'Mise ', focus: 'ni', after: ' ikimasu.', en: 'I am going to the shop.' } },
        { jp: 'で', romaji: 'de', en: 'at / by (place or means of an action)', example: { jp: 'ここで食べます。', before: 'Koko ', focus: 'de', after: ' tabemasu.', en: 'I will eat here.' } },
        { jp: 'へ', romaji: 'e', en: 'toward / to', note: 'Written へ but pronounced e.', example: { jp: '駅へ行きます。', before: 'Eki ', focus: 'e', after: ' ikimasu.', en: 'I am going to the station.' } },
        { jp: 'と', romaji: 'to', en: 'with / and', example: { jp: '寿司とラーメンを食べます。', before: 'Sushi ', focus: 'to', after: ' raamen o tabemasu.', en: 'I eat sushi and ramen.' } },
        { jp: 'も', romaji: 'mo', en: 'also / too', example: { jp: '水もください。', before: 'Mizu ', focus: 'mo', after: ' kudasai.', en: 'Water too, please.' } },
        { jp: 'の', romaji: 'no', en: "of / 's (possession or description)", example: { jp: '私のです。', before: 'Watashi ', focus: 'no', after: ' desu.', en: 'It is mine.' } },
        { jp: 'から', romaji: 'kara', en: 'from / because', example: { jp: 'ここから行きます。', before: 'Koko ', focus: 'kara', after: ' ikimasu.', en: 'I will go from here.' } },
        { jp: 'まで', romaji: 'made', en: 'until / as far as', example: { jp: '駅まで行きます。', before: 'Eki ', focus: 'made', after: ' ikimasu.', en: 'I will go as far as the station.' } },
        { jp: 'や', romaji: 'ya', en: 'and things like …', example: { jp: '寿司やラーメンを食べます。', before: 'Sushi ', focus: 'ya', after: ' raamen o tabemasu.', en: 'I eat things like sushi and ramen.' } },
        { jp: 'か', romaji: 'ka', en: 'question marker', example: { jp: '大丈夫ですか。', before: 'Daijoubu desu ', focus: 'ka', after: '?', en: 'Are you OK?' } },
        { jp: 'ね', romaji: 'ne', en: "isn't it? / shared feeling", example: { jp: '美味しいですね。', before: 'Oishii desu ', focus: 'ne', after: '.', en: "It is delicious, isn't it?" } },
        { jp: 'よ', romaji: 'yo', en: 'emphasis / new information', example: { jp: '安いですよ。', before: 'Yasui desu ', focus: 'yo', after: '.', en: 'It is cheap, you know.' } },
      ],
    },
    {
      id: 'relationships',
      title: 'With & Where',
      icon: '🧭',
      blurb: 'Company, absence and relative position. In Japanese-first mode: example first, then meaning.',
      words: [
        { jp: '一緒に', romaji: 'issho ni', en: 'together / with someone', note: 'Name the companion with と: person + to + issho ni.', example: { jp: '友達と一緒に行きます。', before: 'Tomodachi to ', focus: 'issho ni', after: ' ikimasu.', en: 'I will go with a friend.' } },
        { jp: 'なしで', romaji: 'nashi de', en: 'without', note: 'Put the thing being left out directly before nashi de.', example: { jp: '砂糖なしでお願いします。', before: 'Satou ', focus: 'nashi de', after: ' onegai shimasu.', en: 'Without sugar, please.' } },
        { jp: '上に', romaji: 'ue ni', en: 'over / above / on top of', note: 'Pattern: reference + no + ue ni.', example: { jp: '椅子の上に鞄があります。', before: 'Isu no ', focus: 'ue ni', after: ' kaban ga arimasu.', en: 'There is a bag on the chair.' } },
        { jp: '下に', romaji: 'shita ni', en: 'under / below', note: 'Pattern: reference + no + shita ni.', example: { jp: 'テーブルの下に靴があります。', before: 'Teeburu no ', focus: 'shita ni', after: ' kutsu ga arimasu.', en: 'There are shoes under the table.' } },
        { jp: '中に', romaji: 'naka ni', en: 'in / inside', note: 'Pattern: container + no + naka ni.', example: { jp: '鞄の中にパスポートがあります。', before: 'Kaban no ', focus: 'naka ni', after: ' pasupooto ga arimasu.', en: 'The passport is inside the bag.' } },
        { jp: '外で', romaji: 'soto de', en: 'outside', note: 'Use de here because waiting is an action.', example: { jp: '駅の外で待ちます。', before: 'Eki no ', focus: 'soto de', after: ' machimasu.', en: 'I will wait outside the station.' } },
        { jp: '前に', romaji: 'mae ni', en: 'in front of / before', note: 'Mae can describe either space or time.', example: { jp: 'ホテルの前にタクシーがいます。', before: 'Hoteru no ', focus: 'mae ni', after: ' takushii ga imasu.', en: 'There is a taxi in front of the hotel.' } },
        { jp: '後ろに', romaji: 'ushiro ni', en: 'behind', example: { jp: '駅の後ろに公園があります。', before: 'Eki no ', focus: 'ushiro ni', after: ' kouen ga arimasu.', en: 'There is a park behind the station.' } },
        { jp: '隣に', romaji: 'tonari ni', en: 'next to / neighbouring', note: 'Best for neighbours of the same general kind: buildings, rooms or people.', example: { jp: '銀行の隣にコンビニがあります。', before: 'Ginkou no ', focus: 'tonari ni', after: ' konbini ga arimasu.', en: 'There is a convenience store next to the bank.' } },
        { jp: '横に', romaji: 'yoko ni', en: 'beside / at the side of', note: 'Use yoko for physical side-by-side position, even for unlike things.', example: { jp: 'ドアの横に椅子があります。', before: 'Doa no ', focus: 'yoko ni', after: ' isu ga arimasu.', en: 'There is a chair beside the door.' } },
        { jp: '間に', romaji: 'aida ni', en: 'between', note: 'Pattern: A to B no aida ni.', example: { jp: '銀行とホテルの間に店があります。', before: 'Ginkou to hoteru no ', focus: 'aida ni', after: ' mise ga arimasu.', en: 'There is a shop between the bank and the hotel.' } },
        { jp: '近くに', romaji: 'chikaku ni', en: 'near / nearby', example: { jp: '駅の近くにホテルがあります。', before: 'Eki no ', focus: 'chikaku ni', after: ' hoteru ga arimasu.', en: 'There is a hotel near the station.' } },
        { jp: '向かいに', romaji: 'mukai ni', en: 'opposite / across from', example: { jp: '駅の向かいに銀行があります。', before: 'Eki no ', focus: 'mukai ni', after: ' ginkou ga arimasu.', en: 'There is a bank opposite the station.' } },
        { jp: '周りに', romaji: 'mawari ni', en: 'around / surrounding', example: { jp: 'ホテルの周りに店がたくさんあります。', before: 'Hoteru no ', focus: 'mawari ni', after: ' mise ga takusan arimasu.', en: 'There are many shops around the hotel.' } },
        { jp: '中を', romaji: 'naka o', en: 'through / within (a route)', note: 'Movement through a place uses o, not ni or de.', example: { jp: '公園の中を歩きます。', before: 'Kouen no ', focus: 'naka o', after: ' arukimasu.', en: 'I will walk through the park.' } },
      ],
    },
    {
      id: 'questions',
      title: 'Questions',
      icon: '❓',
      blurb: 'The question words that unlock the information you need while travelling.',
      words: [
        { jp: '何', romaji: 'nani / nan', en: 'what', note: 'Often nan before desu or a counter.', example: { jp: 'これは何ですか。', before: 'Kore wa ', focus: 'nan', after: ' desu ka?', en: 'What is this?' } },
        { jp: '誰', romaji: 'dare', en: 'who', example: { jp: '誰ですか。', before: '', focus: 'Dare', after: ' desu ka?', en: 'Who is it?' } },
        { jp: 'どこ', romaji: 'doko', en: 'where', example: { jp: '駅はどこですか。', before: 'Eki wa ', focus: 'doko', after: ' desu ka?', en: 'Where is the station?' } },
        { jp: 'いつ', romaji: 'itsu', en: 'when', example: { jp: 'いつですか。', before: '', focus: 'Itsu', after: ' desu ka?', en: 'When is it?' } },
        { jp: 'どうして', romaji: 'doushite', en: 'why', example: { jp: 'どうしてですか。', before: '', focus: 'Doushite', after: ' desu ka?', en: 'Why is that?' } },
        { jp: 'どう', romaji: 'dou', en: 'how / what do you think', example: { jp: 'どうですか。', before: '', focus: 'Dou', after: ' desu ka?', en: 'How is it?' } },
        { jp: 'どれ', romaji: 'dore', en: 'which one', example: { jp: 'どれですか。', before: '', focus: 'Dore', after: ' desu ka?', en: 'Which one is it?' } },
        { jp: 'どの', romaji: 'dono', en: 'which … (before a noun)', example: { jp: 'どの電車ですか。', before: '', focus: 'Dono', after: ' densha desu ka?', en: 'Which train is it?' } },
        { jp: 'どちら', romaji: 'dochira', en: 'which way / which one (polite)', example: { jp: 'トイレはどちらですか。', before: 'Toire wa ', focus: 'dochira', after: ' desu ka?', en: 'Which way is the toilet?' } },
        { jp: 'いくら', romaji: 'ikura', en: 'how much', example: { jp: 'これはいくらですか。', before: 'Kore wa ', focus: 'ikura', after: ' desu ka?', en: 'How much is this?' } },
        { jp: '何時', romaji: 'nanji', en: 'what time', example: { jp: '何時ですか。', before: '', focus: 'Nanji', after: ' desu ka?', en: 'What time is it?' } },
        { jp: '何人', romaji: 'nannin', en: 'how many people', example: { jp: '何人ですか。', before: '', focus: 'Nannin', after: ' desu ka?', en: 'How many people?' } },
        { jp: 'いくつ', romaji: 'ikutsu', en: 'how many / how old', example: { jp: 'いくつありますか。', before: '', focus: 'Ikutsu', after: ' arimasu ka?', en: 'How many are there?' } },
        { jp: 'どのくらい', romaji: 'dono kurai', en: 'how long / how much', example: { jp: 'どのくらいですか。', before: '', focus: 'Dono kurai', after: ' desu ka?', en: 'About how much or how long?' } },
      ],
    },
    {
      id: 'essentials',
      title: 'Essentials',
      icon: '🎒',
      blurb: 'The words that work everywhere, in every scenario below.',
      words: [
        { jp: 'ありがとうございます', romaji: 'arigatou gozaimasu', en: 'thank you (polite)', example: { jp: 'ありがとうございます、田中さん。', before: '', focus: 'Arigatou gozaimasu', after: ', Tanaka-san.', en: 'Thank you, Mr Tanaka.' } },
        { jp: 'ありがとう', romaji: 'arigatou', en: 'thanks (casual)', example: { jp: 'ありがとう、アンナ。', before: '', focus: 'Arigatou', after: ', Anna.', en: 'Thanks, Anna.' } },
        { jp: 'すみません', romaji: 'sumimasen', en: 'excuse me / sorry', note: 'Also how you call a waiter or a shop assistant — say it out loud.', example: { jp: 'すみません、トイレはどこですか。', before: '', focus: 'Sumimasen', after: ', toire wa doko desu ka?', en: 'Excuse me, where is the toilet?' } },
        { jp: 'ごめんなさい', romaji: 'gomen nasai', en: 'I am sorry (apology)', example: { jp: 'ごめんなさい、わかりません。', before: '', focus: 'Gomen nasai', after: ', wakarimasen.', en: 'I am sorry, I do not understand.' } },
        { jp: 'お願いします', romaji: 'onegai shimasu', en: 'please (when asking for something)', example: { jp: '水をお願いします。', before: 'Mizu o ', focus: 'onegai shimasu', after: '.', en: 'Water, please.' } },
        { jp: 'ください', romaji: 'kudasai', en: 'please give me …', example: { jp: '水をください。', before: 'Mizu o ', focus: 'kudasai', after: '.', en: 'Water, please.' } },
        { jp: 'はい', romaji: 'hai', en: 'yes / I hear you', note: 'Closer to "I am listening" than to agreement.', example: { jp: 'はい、大丈夫です。', before: '', focus: 'Hai', after: ', daijoubu desu.', en: 'Yes, I am fine.' } },
        { jp: 'いいえ', romaji: 'iie', en: 'no', example: { jp: 'いいえ、大丈夫です。', before: '', focus: 'Iie', after: ', daijoubu desu.', en: 'No, I am fine.' } },
        { jp: '大丈夫', romaji: 'daijoubu', en: 'fine / OK / no thanks', note: 'The all-purpose word. Often a polite refusal.', example: { jp: 'はい、大丈夫です。', before: 'Hai, ', focus: 'daijoubu', after: ' desu.', en: 'Yes, I am fine.' } },
        { jp: 'ちょっと', romaji: 'chotto', en: 'a little / hmm, no', note: 'Trailing off with chotto… is a soft "no".', example: { jp: 'ちょっとわかりません。', before: '', focus: 'Chotto', after: ' wakarimasen.', en: 'I do not quite understand.' } },
        { jp: 'わかりません', romaji: 'wakarimasen', en: 'I do not understand', example: { jp: '日本語はわかりません。', before: 'Nihongo wa ', focus: 'wakarimasen', after: '.', en: 'I do not understand Japanese.' } },
        { jp: '英語', romaji: 'eigo', en: 'English (the language)', example: { jp: '英語はわかりますか。', before: '', focus: 'Eigo', after: ' wa wakarimasu ka?', en: 'Do you understand English?' } },
        { jp: '日本語', romaji: 'nihongo', en: 'Japanese (the language)', example: { jp: '日本語はわかりません。', before: '', focus: 'Nihongo', after: ' wa wakarimasen.', en: 'I do not understand Japanese.' } },
        { jp: 'これ', romaji: 'kore', en: 'this one (near me)', example: { jp: 'これをください。', before: '', focus: 'Kore', after: ' o kudasai.', en: 'This one, please.' } },
        { jp: 'それ', romaji: 'sore', en: 'that one (near you)', example: { jp: 'それはいくらですか。', before: '', focus: 'Sore', after: ' wa ikura desu ka?', en: 'How much is that?' } },
        { jp: 'あれ', romaji: 'are', en: 'that one over there', example: { jp: 'あれは何ですか。', before: '', focus: 'Are', after: ' wa nan desu ka?', en: 'What is that over there?' } },
        { jp: 'どこ', romaji: 'doko', en: 'where', example: { jp: '駅はどこですか。', before: 'Eki wa ', focus: 'doko', after: ' desu ka?', en: 'Where is the station?' } },
        { jp: 'いくら', romaji: 'ikura', en: 'how much', example: { jp: 'これはいくらですか。', before: 'Kore wa ', focus: 'ikura', after: ' desu ka?', en: 'How much is this?' } },
        { jp: '何', romaji: 'nani', en: 'what', example: { jp: 'これは何ですか。', before: 'Kore wa ', focus: 'nan', after: ' desu ka?', en: 'What is this?' } },
        { jp: 'トイレ', romaji: 'toire', en: 'toilet', example: { jp: 'トイレはどこですか。', before: '', focus: 'Toire', after: ' wa doko desu ka?', en: 'Where is the toilet?' } },
      ],
    },
    {
      id: 'restaurant',
      title: 'Restaurant',
      icon: '🍜',
      blurb: 'Enough to order, to avoid what you cannot eat, and to pay.',
      words: [
        { jp: 'メニュー', romaji: 'menyuu', en: 'menu' },
        { jp: 'おすすめ', romaji: 'osusume', en: 'the recommendation' },
        { jp: '水', romaji: 'mizu', en: 'water' },
        { jp: 'お茶', romaji: 'ocha', en: 'tea' },
        { jp: 'ビール', romaji: 'biiru', en: 'beer', note: 'Two beats on the ii — biru (one beat) is a building.' },
        { jp: 'ご飯', romaji: 'gohan', en: 'rice / a meal' },
        { jp: '肉', romaji: 'niku', en: 'meat' },
        { jp: '鶏肉', romaji: 'toriniku', en: 'chicken' },
        { jp: '豚肉', romaji: 'butaniku', en: 'pork' },
        { jp: '牛肉', romaji: 'gyuuniku', en: 'beef' },
        { jp: '魚', romaji: 'sakana', en: 'fish' },
        { jp: '野菜', romaji: 'yasai', en: 'vegetables' },
        { jp: '卵', romaji: 'tamago', en: 'egg' },
        { jp: 'だし', romaji: 'dashi', en: 'fish stock', note: 'Hides in most "vegetable" dishes — worth knowing if you avoid fish.' },
        { jp: 'アレルギー', romaji: 'arerugii', en: 'allergy' },
        { jp: '辛い', romaji: 'karai', en: 'spicy' },
        { jp: '美味しい', romaji: 'oishii', en: 'delicious' },
        { jp: '一つ', romaji: 'hitotsu', en: 'one (of anything)' },
        { jp: '二つ', romaji: 'futatsu', en: 'two (of anything)' },
        { jp: '箸', romaji: 'hashi', en: 'chopsticks' },
        { jp: '席', romaji: 'seki', en: 'seat / table' },
        { jp: '持ち帰り', romaji: 'mochikaeri', en: 'takeaway' },
        { jp: 'お会計', romaji: 'okaikei', en: 'the bill' },
        { jp: '以上です', romaji: 'ijou desu', en: 'that is all (order finished)' },
      ],
    },
    {
      id: 'hotel',
      title: 'Hotel',
      icon: '🛏️',
      blurb: 'Checking in, asking for things, and reporting what is broken.',
      words: [
        { jp: '予約', romaji: 'yoyaku', en: 'reservation' },
        { jp: 'チェックイン', romaji: 'chekku-in', en: 'check-in' },
        { jp: 'チェックアウト', romaji: 'chekku-auto', en: 'check-out' },
        { jp: '部屋', romaji: 'heya', en: 'room' },
        { jp: '鍵', romaji: 'kagi', en: 'key' },
        { jp: '一泊', romaji: 'ippaku', en: 'one night (of a stay)' },
        { jp: '二人', romaji: 'futari', en: 'two people' },
        { jp: '荷物', romaji: 'nimotsu', en: 'luggage' },
        { jp: 'フロント', romaji: 'furonto', en: 'front desk / reception' },
        { jp: 'タオル', romaji: 'taoru', en: 'towel' },
        { jp: '枕', romaji: 'makura', en: 'pillow' },
        { jp: '朝食', romaji: 'choushoku', en: 'breakfast' },
        { jp: 'お風呂', romaji: 'ofuro', en: 'bath' },
        { jp: 'シャワー', romaji: 'shawaa', en: 'shower' },
        { jp: 'エアコン', romaji: 'eakon', en: 'air conditioning' },
        { jp: 'パスワード', romaji: 'pasuwaado', en: 'password (Wi-Fi)' },
        { jp: 'エレベーター', romaji: 'erebeetaa', en: 'lift / elevator' },
        { jp: '何階', romaji: 'nan-gai', en: 'which floor' },
        { jp: '禁煙', romaji: "kin'en", en: 'non-smoking' },
        { jp: '故障', romaji: 'koshou', en: 'broken / out of order' },
        { jp: '洗濯', romaji: 'sentaku', en: 'laundry' },
        { jp: 'コインロッカー', romaji: 'koin-rokkaa', en: 'coin locker' },
      ],
    },
    {
      id: 'shop',
      title: 'Shop',
      icon: '🛍️',
      blurb: 'Prices, sizes, paying, and the tax-free counter.',
      words: [
        { jp: '店', romaji: 'mise', en: 'shop' },
        { jp: 'コンビニ', romaji: 'konbini', en: 'convenience store' },
        { jp: '薬局', romaji: 'yakkyoku', en: 'pharmacy' },
        { jp: 'お金', romaji: 'okane', en: 'money' },
        { jp: '円', romaji: 'en', en: 'yen', note: 'Said "en", not "yen".' },
        { jp: '現金', romaji: 'genkin', en: 'cash' },
        { jp: 'カード', romaji: 'kaado', en: 'card' },
        { jp: '税込', romaji: 'zeikomi', en: 'tax included' },
        { jp: '免税', romaji: 'menzei', en: 'tax-free' },
        { jp: 'レシート', romaji: 'reshiito', en: 'receipt' },
        { jp: '袋', romaji: 'fukuro', en: 'bag' },
        { jp: '安い', romaji: 'yasui', en: 'cheap' },
        { jp: '高い', romaji: 'takai', en: 'expensive (also: tall)' },
        { jp: '大きい', romaji: 'ookii', en: 'big' },
        { jp: '小さい', romaji: 'chiisai', en: 'small' },
        { jp: 'サイズ', romaji: 'saizu', en: 'size' },
        { jp: '色', romaji: 'iro', en: 'colour' },
        { jp: '他の', romaji: 'hoka no', en: 'another / a different one' },
        { jp: '試着', romaji: 'shichaku', en: 'trying clothes on' },
        { jp: '全部', romaji: 'zenbu', en: 'all of it / everything' },
        { jp: '売り切れ', romaji: 'urikire', en: 'sold out' },
        { jp: 'お土産', romaji: 'omiyage', en: 'souvenir / gift to take home' },
      ],
    },
    {
      id: 'street',
      title: 'Street',
      icon: '🚉',
      blurb: 'Stations, tickets, and the words in every answer to "where is …?".',
      words: [
        { jp: '駅', romaji: 'eki', en: 'station' },
        { jp: '電車', romaji: 'densha', en: 'train' },
        { jp: '地下鉄', romaji: 'chikatetsu', en: 'subway' },
        { jp: 'バス', romaji: 'basu', en: 'bus' },
        { jp: 'タクシー', romaji: 'takushii', en: 'taxi' },
        { jp: '空港', romaji: 'kuukou', en: 'airport' },
        { jp: '切符', romaji: 'kippu', en: 'ticket' },
        { jp: '片道', romaji: 'katamichi', en: 'one way' },
        { jp: '往復', romaji: 'oufuku', en: 'return / round trip' },
        { jp: '乗り換え', romaji: 'norikae', en: 'changing trains' },
        { jp: 'ホーム', romaji: 'hoomu', en: 'platform' },
        { jp: '出口', romaji: 'deguchi', en: 'exit' },
        { jp: '入口', romaji: 'iriguchi', en: 'entrance' },
        { jp: '右', romaji: 'migi', en: 'right' },
        { jp: '左', romaji: 'hidari', en: 'left' },
        { jp: 'まっすぐ', romaji: 'massugu', en: 'straight ahead' },
        { jp: '次', romaji: 'tsugi', en: 'the next one' },
        { jp: '角', romaji: 'kado', en: 'corner' },
        { jp: '信号', romaji: 'shingou', en: 'traffic light' },
        { jp: '近い', romaji: 'chikai', en: 'near' },
        { jp: '遠い', romaji: 'tooi', en: 'far' },
        { jp: '地図', romaji: 'chizu', en: 'map' },
        { jp: '住所', romaji: 'juusho', en: 'address' },
        { jp: '何時', romaji: 'nanji', en: 'what time' },
      ],
    },
    {
      id: 'trouble',
      title: 'Trouble',
      icon: '🩹',
      blurb: 'Illness, loss and emergencies — the deck you hope stays unused.',
      words: [
        { jp: '助けて', romaji: 'tasukete', en: 'help!' },
        { jp: '病院', romaji: 'byouin', en: 'hospital' },
        { jp: '医者', romaji: 'isha', en: 'doctor' },
        { jp: '薬', romaji: 'kusuri', en: 'medicine' },
        { jp: '痛い', romaji: 'itai', en: 'it hurts / painful' },
        { jp: '頭', romaji: 'atama', en: 'head' },
        { jp: 'お腹', romaji: 'onaka', en: 'stomach' },
        { jp: '熱', romaji: 'netsu', en: 'a fever' },
        { jp: '風邪', romaji: 'kaze', en: 'a cold (illness)' },
        { jp: '気分が悪い', romaji: 'kibun ga warui', en: 'I feel unwell' },
        { jp: '警察', romaji: 'keisatsu', en: 'police' },
        { jp: '財布', romaji: 'saifu', en: 'wallet' },
        { jp: 'なくしました', romaji: 'nakushimashita', en: 'I have lost (it)' },
        { jp: '忘れました', romaji: 'wasuremashita', en: 'I have left / forgotten (it)' },
        { jp: '道に迷いました', romaji: 'michi ni mayoimashita', en: 'I am lost' },
        { jp: '危ない', romaji: 'abunai', en: 'dangerous / watch out!' },
        { jp: '大使館', romaji: 'taishikan', en: 'embassy' },
        { jp: '保険', romaji: 'hoken', en: 'insurance' },
        { jp: '交番', romaji: 'kouban', en: 'police box', note: 'The small neighbourhood police post — your first stop for lost items.' },
      ],
    },
    {
      id: 'people',
      title: 'People',
      icon: '🙂',
      blurb: 'Greetings and the small talk that follows "where are you from?".',
      words: [
        { jp: 'おはようございます', romaji: 'ohayou gozaimasu', en: 'good morning' },
        { jp: 'こんにちは', romaji: 'konnichiwa', en: 'hello (daytime)' },
        { jp: 'こんばんは', romaji: 'konbanwa', en: 'good evening' },
        { jp: 'はじめまして', romaji: 'hajimemashite', en: 'nice to meet you (first time only)' },
        { jp: 'よろしくお願いします', romaji: 'yoroshiku onegai shimasu', en: 'pleased to be dealing with you' },
        { jp: 'さようなら', romaji: 'sayounara', en: 'goodbye', note: 'Heavier than English "bye" — for real partings.' },
        { jp: 'また明日', romaji: 'mata ashita', en: 'see you tomorrow' },
        { jp: 'お名前', romaji: 'onamae', en: 'your name' },
        { jp: '私', romaji: 'watashi', en: 'I / me' },
        { jp: '旅行', romaji: 'ryokou', en: 'a trip / travel' },
        { jp: '観光', romaji: 'kankou', en: 'sightseeing' },
        { jp: '仕事', romaji: 'shigoto', en: 'work / job' },
        { jp: '好き', romaji: 'suki', en: 'like / fond of' },
        { jp: '楽しい', romaji: 'tanoshii', en: 'fun / enjoyable' },
        { jp: '綺麗', romaji: 'kirei', en: 'beautiful / clean' },
        { jp: 'すごい', romaji: 'sugoi', en: 'wow / amazing' },
        { jp: '暑い', romaji: 'atsui', en: 'hot (weather)' },
        { jp: '寒い', romaji: 'samui', en: 'cold (weather)' },
        { jp: '天気', romaji: 'tenki', en: 'weather' },
        { jp: 'そうですね', romaji: 'sou desu ne', en: 'that is true / hmm, yes', note: 'The universal time-buying agreement noise.' },
      ],
    },
  ],
}
